/*
 * Copyright (c) 2026 erik <erik@erik.xyz> — https://erik.xyz
 */

import { COLUMN_TITLES_EXTRA } from './column-titles-extra';

/**
 * 列标题词典：字段名 → 中文标题（只给中文原文，翻译交给模板 | tr，语言切换才会重渲染）。
 *
 * 四层来源，按优先级合并（同名键只留高优先级）：
 * 1) 引擎原有通用档（编号/名称/合计… 32 条）—— 少了它们 no/total/subtotal 等会退回驼峰英文；
 * 2) 各域 config/domains/*.ts 表单字段的 {key,label}（按 key 去重，同 key 取出现最多者）；
 * 3) 常见外键与时间戳补充档（订单号/客户/创建时间…）；
 * 4) install.sql 列注释生成的全量补充档（`config/column-titles-extra/`，勿手改）。
 *
 * 键是中文 → core/zh-*.ts 词典能查到 → 各语种正常翻译。
 */
const BASE: Record<string, string> = {
  acceptor: '承兑人',
  account_id: '费用科目',
  address: '地址',
  amount: '金额',
  app_id: '所属应用',
  app_name: '应用名称',
  apply_user_id: '申请人',
  assignee_id: '负责人',
  assignee_user_id: '指派人',
  attrs: '规格属性',
  bank_account: '银行账号',
  bank_account_id: '收款账户',
  bank_name: '开户行',
  barcode: '条码',
  base_salary: '基本工资',
  bill_no: '票据号',
  bom_id: 'BOM',
  brand_id: '品牌',
  candidate_id: '候选人',
  carrier_service_id: '承运商服务',
  category: '工单分类',
  category_id: '分类',
  channel: '渠道',
  city: '城市',
  code: '编号',
  contact_person: '联系人',
  content: '文档内容',
  cost: '成本',
  course_type: '课程类型',
  created_at: '创建时间',
  credit_days: '信用账期(天)',
  credit_limit: '信用额度',
  credits: '学分',
  currency: '币种',
  customer_id: '客户',
  dashboard_id: '所属看板',
  date: '日期',
  days: '天数',
  deduction: '扣款',
  defect_qty: '缺陷数量',
  defect_type: '缺陷类型',
  deleted_at: '删除时间',
  delivery_id: '发货单',
  department: '申请部门',
  department_id: '部门',
  depreciation_method: '折旧方法',
  description: '说明',
  discount: '折扣',
  drawer: '出票人',
  due_date: '到期日',
  duration_hours: '课时(小时)',
  effective_date: '生效日期',
  email: '邮箱',
  employee_id: '员工',
  enabled: '是否启用',
  end_date: '结束日期',
  entry_date: '归集日期',
  entry_type: '费用类型',
  equipment_id: '设备',
  event: '订阅事件',
  expected_salary: '期望薪资',
  fault_description: '故障描述',
  follow_user_id: '跟进人',
  frequency: '保养频率',
  from_currency_id: '来源币种',
  group: '分组',
  headcount: '招聘人数',
  hours: '工时数',
  icon: '图标',
  inspected_qty: '检验数量',
  interview_date: '面试日期',
  issue_date: '出票日期',
  job_id: '应聘职位',
  job_title: '职位名称',
  key: '配置键',
  lecturer: '讲师',
  level: '等级',
  level_id: '等级',
  location_id: '库位',
  logo: 'LOGO 地址',
  manager: '负责人',
  manager_user_id: '负责人',
  max_quantity: '最大库存阈值',
  method: '收款方式',
  min_quantity: '最小库存阈值',
  module: '所属模块',
  name: '名称',
  no: '编号',
  note: '备注',
  offered_salary: 'Offer 薪资',
  onboard_date: '入职日期',
  order_id: '生产工单',
  order_no: '订单号',
  overtime: '加班费',
  owner: '负责人',
  owner_user_id: '负责人',
  parent_id: '上级部门',
  partner_id: '往来方',
  password: '密码',
  path: '路径',
  payee: '收款人',
  performance: '绩效工资',
  period_month: '计划月份',
  period_type: '周期类型',
  period_year: '预算年度',
  permission_ids: '权限',
  phone: '手机',
  planned_quantity: '计划数量',
  position_id: '职位',
  price: '单价',
  priority: '优先级',
  product_id: '产品',
  project_id: '所属项目',
  purchase_amount: '购置金额',
  purchase_date: '购置日期',
  qualified_qty: '合格数量',
  quantity: '数量',
  rate: '汇率值',
  real_name: '姓名',
  receipt_payment_id: '付款单',
  receive_date: '收料日期',
  receive_id: '收货单',
  received_at: '收款日期',
  remark: '备注',
  repair_type: '维修类型',
  report_date: '报工日期',
  requirement: '任职要求',
  result: '检验结果',
  round_no: '轮次',
  routing_id: '工序',
  rule_name: '规则名称',
  salvage_value: '残值',
  seq: '工序序号',
  sign_date: '签订日期',
  sku_id: 'SKU ID',
  slug: '标识',
  social_base_max: '缴费基数上限',
  social_base_min: '缴费基数下限',
  sort: '排序',
  source: '来源渠道',
  spec: '规格型号',
  stage: '阶段',
  start_date: '开始日期',
  status: '状态',
  subcontract_id: '委外订单',
  subtotal: '小计',
  summary: '摘要',
  supplier_id: '供应商',
  target_type: '目标类型',
  target_url: '回调地址',
  task_date: '点检日期',
  task_id: '关联任务',
  tax: '税额',
  tax_number: '税号',
  tax_rate: '税率',
  template_id: '报表模板',
  time: '时间',
  title: '标题',
  to_currency_id: '目标币种',
  total: '合计',
  total_amount: '金额',
  total_price: '总金额',
  type: '类型',
  unit: '单位',
  unit_id: '单位',
  unit_price: '加工单价',
  updated_at: '更新时间',
  useful_life: '使用年限',
  user_id: '用户',
  username: '用户名',
  valid_from: '生效日期',
  value: '值',
  warehouse_id: '仓库',
  work_date: '工作日期',
  workstation_id: '工作站',
  zone_id: '库区',
};

/** 上表（人工档）优先，补充档只补缺 —— 两端同源，见 scripts/gen-column-titles.mjs */
export const COLUMN_TITLES: Record<string, string> = { ...COLUMN_TITLES_EXTRA, ...BASE };
