/*
 * Copyright (c) 2026 erik <erik@erik.xyz> — https://erik.xyz
 */

// 词典切片 3/4，由 ./index 合并导出；查找词条请 grep 整个目录。

export const zhEnPart3: Record<string, string> = {
  维修: 'Repair',
  维修人: 'Repairer',
  维修工单: 'Repair Orders',
  维修类型: 'Repair Type',
  维修费用: 'Repair Cost',
  编号: 'No.',
  编码: 'Code',
  编辑: 'Edit',
  编辑OMS订单: 'Edit OMS Order',
  编辑图表: 'Edit Chart',
  编辑报价单: 'Edit Quotation',
  '编辑收货单（仅备注）': 'Edit Receiving Record (remark only)',
  编辑汇率: 'Edit Exchange Rate',
  编辑用户: 'Edit User',
  编辑薪资: 'Edit Payroll Record',
  编辑薪资项: 'Edit Salary Item',
  编辑角色: 'Edit Role',
  编辑记账凭证: 'Edit Voucher',
  编辑请假: 'Edit Leave',
  编辑跟进记录: 'Edit Follow-up',
  编辑配置: 'Edit Setting',
  编辑采购申请: 'Edit Purchase Request',
  编辑采购结算: 'Edit Purchase Settlement',
  编辑采购订单: 'Edit Purchase Order',
  编辑银行账户: 'Edit Bank Account',
  编辑销售结算: 'Edit Sales Settlement',
  编辑销售订单: 'Edit Sales Order',
  编辑阶段: 'Edit Stage',
  缺陷数量: 'Defect Qty',
  缺陷类型: 'Defect Type',
  '网络连接失败，请检查网络': 'Network connection failed, please check your network',
  '网络错误，请检查连接': 'Network error, please check your connection',
  考勤: 'Attendance',
  考勤管理: 'Attendance',
  职位: 'Position',
  职位管理: 'Positions',
  联系人: 'Contact',
  草稿: 'Draft',
  营业成本: 'Operating Cost',
  营业收入: 'Operating Revenue',
  营销活动: 'Campaign',
  薪资: 'Salary',
  薪资发放: 'Pay Salaries',
  薪资已发放: 'Salary marked as paid',
  薪资年度: 'Salary Year',
  薪资月份: 'Salary Month',
  薪资管理: 'Payroll',
  薪资试算: 'Salary Calculation',
  薪资项配置: 'Payroll Items',
  行数: 'Rows',
  规格: 'Spec',
  规格名称: 'Spec Name',
  规格型号: 'Model/Spec',
  角色: 'Role',
  角色创建成功: 'Role created',
  角色删除成功: 'Role deleted',
  角色更新成功: 'Role updated',
  角色管理: 'Roles',
  解决: 'Resolve',
  解决工单: 'Resolve Ticket',
  解决说明: 'Resolution Notes',
  计划名称: 'Plan Name',
  计划生产数量: 'Planned Quantity',
  计提折旧: 'Record Depreciation',
  计税: 'Taxable',
  '计算中...': 'Calculating...',
  计算比率: 'Calculate Ratios',
  计算薪资: 'Calculate Salary',
  订单: 'Order',
  订单名称: 'Order Name',
  订单总金额: 'Order Total Amount',
  订单状态分布: 'Order Status Distribution',
  订单管理: 'Order Management',
  订单编号: 'Order No.',
  订单编码: 'Order Code',
  记录不存在: 'Record not found',
  记录已存在: 'Record already exists',
  记账凭证: 'Voucher',
  设备ID: 'Equipment ID',
  设备分类: 'Equipment Category',
  设备台账: 'Equipment Ledger',
  设备名称: 'Equipment Name',
  设备编码: 'Equipment Code',
  试算平衡表: 'Trial Balance',
  试算结果: 'Calculation Result',
  详情: 'Details',
  说明: 'Description',
  请假: 'Leave',
  请假原因: 'Reason',
  请假天数: 'Leave Days',
  请假日期: 'Leave Period',
  请假管理: 'Leave',
  请假类型: 'Leave Type',
  请先选择用户: 'Please select users first',
  请加载验证码: 'Please load the captcha',
  '请按顺序点击图中文字: {text}': 'Click the characters in the image in order: {text}',
  '请按顺序点击图中文字『{text}』': "Click the character \\'{text}\\' in order",
  请求失败: 'Request failed',
  '请求超时，请稍后重试': 'Request timed out, please retry later',
  '请求过于频繁，请稍后重试': 'Too many requests, please try again later',
  请至少填写一行分配明细: 'Add at least one allocation line',
  '请输入{label}': 'Please enter {label}',
  请输入密码: 'Please enter your password',
  请输入用户名和密码: 'Please enter username and password',
  '请输入科目ID（account_subject_id 必填）': 'Enter Account ID (account_subject_id is required)',
  请选择目标状态: 'Please select a target status',
  调休: 'Compensatory Leave',
  负债总计: 'Total Liabilities',
  负责人: 'Assignee',
  财务: 'Finance',
  财务比率: 'Financial Ratios',
  账号已被锁定: 'Account is locked',
  账户余额: 'Account Balance',
  账户名称: 'Account Name',
  购买日期: 'Purchase Date',
  贷: 'Credit',
  贷方合计: 'Total Credits',
  费用: 'Expense',
  费用合计: 'Total Expenses',
  费用报销: 'Expense',
  费用结转: 'Expense Carryforward',
  资产总计: 'Total Assets',
  资产收益率: 'Return on Assets',
  资产负债率: 'Debt-to-Asset Ratio',
  资产负债表: 'Balance Sheet',
  '资产负债表 JSON *': 'Balance Sheet JSON *',
  起始区域: 'Origin Zone',
  起始国家: 'Origin Country',
  '起始重量(kg)': 'Weight From (kg)',
  起步价: 'Base Rate',
  跟进主题: 'Follow-up Subject',
  跟进内容: 'Follow-up Content',
  跟进记录: 'Follow-up',
  路径: 'Path',
  路径筛选: 'Filter by path',
  转合同: 'Convert to Contract',
  输入关键词搜索: 'Enter keywords to search',
  输入密码确认: 'Enter password to confirm',
  '过程检验(IPQC)': 'In-process Inspection (IPQC)',
  运单: 'Shipment',
  运单号: 'Tracking No.',
  运单管理: 'Shipments',
  运费: 'Shipping Fee',
  运费发票: 'Freight Invoice',
  运费费率: 'Freight Rate',
  运输中: 'In Transit',
  运输管理: 'Transport Management',
  退出登录: 'Log Out',
  退回时间: 'Returned At',
  退回运费: 'Return Shipping Fee',
  退换单号: 'RMA No.',
  退换货: 'RMA',
  '退换货(RMA)': 'Returns (RMA)',
  退款: 'Refund',
  退款金额: 'Refund Amount',
  退货: 'Return',
  退货单号: 'Return No.',
  退货时间: 'Returned At',
  选填: 'Optional',
  通知: 'Notification',
  通知中心: 'Notifications',
  通过: 'Approve',
  通过审批: 'Approve',
  邮箱: 'Email',
  部分发货: 'Partially Shipped',
  部分收货: 'Partially Received',
  部分核销: 'Partially Settled',
  部分结算: 'Partially Settled',
  部分退款: 'Partially Refunded',
  部门: 'Department',
  部门ID: 'Department ID',
  部门管理: 'Departments',
  配置JSON: 'Config JSON',
  配送方式: 'Shipping Method',
  采购: 'Purchase',
  采购收货: 'Purchase Receiving',
  采购申请: 'Purchase Requisition',
  采购申请ID: 'Purchase Request ID',
  采购结算: 'Purchase Settlement',
  采购订单: 'Purchase Order',
  采购退货: 'Purchase Return',
  释放回公海: 'Release to Pool',
  重试: 'Retry',
  金额: 'Amount',
  金额超出限额: 'Amount exceeds limit',
  银行: 'Bank',
  银行账号: 'Bank Account Number',
  银行账户: 'Bank Accounts',
  销售: 'Sales',
  销售发货: 'Sales Delivery',
  销售报价: 'Sales Quotations',
  销售渠道: 'Sales Channel',
  销售漏斗: 'Sales Funnel',
  销售结算: 'Sales Settlements',
  销售订单: 'Sales Order',
  '销售趋势（近30天）': 'Sales Trend (Last 30 Days)',
  销售退货: 'Sales Return',
  错误: 'Error',
  键: 'Key',
  阶段: 'Stage',
  阶段名称: 'Stage Name',
  '需已审核的付款单 hashid': 'Hashid of an approved payment record',
  '需已审核的收款单 hashid': 'Hashid of an approved receipt record',
  非流动负债: 'Non-Current Liabilities',
  非流动资产: 'Non-Current Assets',
  '非空 JSON 数组，每项须含 ledger_id 或 company_id（后端数字ID，非 hashid）与 report_year（≥2000）、report_month（1-12）':
    'Non-empty JSON array; each item must have ledger_id or company_id (numeric backend ID, not hashid) plus report_year (≥2000) and report_month (1-12)',
  项目: 'Project',
  项目列表: 'Project List',
  '预到货(ASN)': 'Expected Receipts (ASN)',
  预到货通知: 'ASN',
  预算: 'Budget',
  预算管理: 'Budgets',
  领取: 'Claim',
  领取客户: 'Claim Customer',
  频率: 'Frequency',
  驳回: 'Reject',
  驳回审批: 'Reject',
  驳回请假: 'Reject Leave',
  验证码加载失败: 'Failed to load captcha',
  '验证码错误，请重试': 'Incorrect captcha, please retry',
  旋转图片验证: 'Rotate Image Captcha',
  滑块拼图验证: 'Slider Puzzle Captcha',
  '尝试次数过多，请更换验证码': 'Too many attempts, please refresh the captcha',
  转动图片使其摆正后提交: 'Rotate the image upright, then submit',
  拖动拼图块使其对齐图中缺口: 'Drag the puzzle piece to the gap in the image',
  高库存预警: 'Overstock Alerts',
  高度: 'Height',
  '默认 0': 'Default 0',
  默认金额: 'Default Amount',
  '0 为顶级': '0 for top level',
  '3-50 字符': '3-50 characters',
  '6-32 字符': '6-32 characters',
  '6-32 位': '6-32 characters',
  'BI 看板': 'BI Dashboard',
  'BOM 名称': 'BOM Name',
  'BOM 管理': 'BOM Management',
  'BOM 编码': 'BOM Code',
  'CRM 报价单': 'CRM Quotation',
  'LOGO 地址': 'Logo URL',
  'MRP 计划': 'MRP Plan',
  'MRP 运算': 'Run MRP',
  'Offer 已发出': 'Offer sent',
  'Offer 薪资': 'Offer Salary',
  erp开放平台: 'Open ERP Platform',
  上一页: 'Previous',
  上架: 'Publish',
  上架完成: 'Shelving done',
  上架已完成: 'Shelving completed',
  上次登录: 'Last Login',
  上班打卡: 'Clock In',
  上级部门: 'Parent Department',
  下一页: 'Next',
  下架: 'Unpublish',
  下班打卡: 'Clock Out',
  不合格: 'Reject',
  不合格品单号: 'NCR Number',
  不通过: 'Not Pass',
  '两位小数，如 30000.00': 'Up to 2 decimals, e.g. 30000.00',
  '两位小数，如 5000.00': 'Up to 2 decimals, e.g. 5000.00',
  两次输入的新密码不一致: 'The two new passwords do not match',
  中标转订单: 'Award to Purchase Order',
  产品: 'Product',
  人工: 'Labor',
  仓库名称: 'Warehouse Name',
  仓库管理: 'Warehouse Management',
  仓库编码: 'Warehouse Code',
  付款方式: 'Payment Method',
  付款日期: 'Payment Date',
  付款账户: 'Payment Account',
  任务名称: 'Task Name',
  任职要求: 'Requirements',
  作废: 'Void',
  使用年限: 'Useful Life',
  供应商名称: 'Supplier Name',
  供应商报价: 'Supplier Quotes',
  供应商评估: 'Supplier Assessment',
  保存失败: 'Save failed',
  保存资料: 'Save Profile',
  '信用账期(天)': 'Credit Term (days)',
  信用额度: 'Credit Limit',
  修改失败: 'Update failed',
  候选人: 'Candidate',
  停用: 'Suspend',
  兑付: 'Cash',
  入职日期: 'Onboard Date',
  全部通知已标记为已读: 'All notifications marked as read',
  共: 'of',
  关联任务: 'Linked Task',
  内训: 'Internal',
  再次输入新密码: 'Enter the new password again',
  净值: 'Net Value',
  出库仓库: 'Issue Warehouse',
  出票人: 'Drawer',
  出票日期: 'Issue Date',
  出货检验: 'Final Inspection OQC',
  '出货检验 OQC': 'Final Inspection OQC',
  分类名称: 'Category Name',
  初筛通过: 'Screen Passed',
  利润表: 'Income Statement',
  到期: 'Expired',
  到期预警: 'Expiry Alerts',
  制费: 'Overhead',
  加工单价: 'Processing Price',
  '加载中…': 'Loading...',
  勾选: 'Check',
  协同管理: 'Collaboration',
  原值: 'Original Value',
  发出: 'Send',
  发布: 'Publish',
  发布中: 'Published',
  发料仓库: 'Issue Warehouse',
  发料单号: 'Issue Slip No.',
  发料单已审核: 'Issue slip approved',
  发料日期: 'Issue Date',
  发生日期: 'Occur Date',
  发票号: 'Invoice No.',
  发票管理: 'Invoice Management',
  发货: 'Ship',
  发货单: 'Delivery Note',
  发货日期: 'Ship Date',
  发起审批: 'Start Approval',
  取消点检: 'Cancel Inspection',
  合同号: 'Contract No.',
  合同金额: 'Contract Amount',
  合格: 'Pass',
  合格数: 'Passed Qty',
  合计: 'Total',
  启停: 'Toggle',
  启动: 'Start',
  启用日期: 'In Service Date',
  员工姓名: 'Employee Name',
  员工编码: 'Employee Code',
  周期类型: 'Period Type',
  品牌名称: 'Brand Name',
  品牌描述: 'Brand Description',
  品项数: 'Line Items',
  商品描述: 'Description',
  商品管理: 'Product Management',
  商品资料: 'Product Master',
  商机名称: 'Opportunity Name',
  回复: 'Reply',
  回调地址: 'Callback URL',
  图标: 'Icon',
  图表组件: 'Chart Widget',
  城市: 'City',
  培训社保: 'Training & Social Security',
  培训课程: 'Training Courses',
  基本资料: 'Basic Profile',
  处理中: 'Processing',
  备件管理: 'Spare Parts',
  外训: 'External',
  多币种: 'Currencies',
  多组织公司: 'Companies',
  '如 admin、viewer': 'e.g. admin, viewer',
  '如 monthly': 'e.g. monthly',
  '如 上海': 'e.g. Shanghai',
  '如 人民币': 'e.g. CNY',
  委外产品: 'Outsourced Product',
  委外加工: 'Subcontracting',
  委外发料: 'Subcontract Issue',
  委外收货: 'Subcontract Receiving',
  委外数量: 'Subcontract Qty',
};
