/*
 * Copyright (c) 2026 erik <erik@erik.xyz> — https://erik.xyz
 */

// 词典切片 1/4，由 ./index 合并导出；查找词条请 grep 整个目录。

export const zhEnPart1: Record<string, string> = {
  ':attribute 不存在': 'The :attribute does not exist',
  ':attribute 不能为空': 'The :attribute field is required',
  ':attribute 不能大于 :max': 'The :attribute must not exceed :max',
  ':attribute 不能小于 :min': 'The :attribute must be at least :min',
  ':attribute 值无效': 'The :attribute value is invalid',
  ':attribute 已存在': 'The :attribute already exists',
  ':attribute 必须是字符串': 'The :attribute must be a string',
  ':attribute 必须是数字': 'The :attribute must be a number',
  ':attribute 必须是整数': 'The :attribute must be an integer',
  ':attribute 格式不正确': 'The :attribute format is invalid',
  BOM管理: 'BOM Management',
  'JSON 对象，含 current_assets、current_liabilities、total_liabilities、total_assets 字段，值为数字':
    'JSON object with numeric values for current_assets, current_liabilities, total_liabilities and total_assets',
  'JSON 对象，含 net_profit、revenue 字段，值为数字':
    'JSON object with numeric values for net_profit and revenue',
  MRP计划: 'MRP Planning',
  'OMS 订单': 'OMS Orders',
  OMS订单: 'OMS Order',
  Token已过期: 'Token expired',
  Token无效: 'Invalid token',
  X坐标: 'X Position',
  'YYYY-MM-DD，如 2026-09-05': 'YYYY-MM-DD, e.g. 2026-09-05',
  Y坐标: 'Y Position',
  erp开放管理后台: 'Open ERP Admin',
  erp管理后台: 'Open ERP Admin',
  '{field} 不是合法 JSON': '{field} is not valid JSON',
  '{field} 必须为 JSON 对象': '{field} must be a JSON object',
  '{field} 必须为 JSON 数组': '{field} must be a JSON array',
  '{page} / {pages} ({total}条)': '{page} / {pages} ({total})',
  '一个平台，管好全部业务': 'One platform for all your business',
  上传成功: 'Upload successful',
  上架管理: 'Putaway',
  上次保养日期: 'Last Maintenance Date',
  下单时间: 'Order Date',
  下次保养日期: 'Next Maintenance Date',
  下次日期: 'Next Date',
  不合格品: 'Nonconforming Products',
  不合格数量: 'Rejected Qty',
  不合格编号: 'Defect No.',
  两次密码不一致: 'Passwords do not match',
  严重程度: 'Severity',
  个人中心: 'Profile',
  个人信息更新成功: 'Profile updated successfully',
  个人所得税: 'Individual Income Tax',
  个税: 'Income Tax',
  主题: 'Subject',
  买家备注: 'Buyer Note',
  事假: 'Personal Leave',
  产假: 'Maternity Leave',
  人力资源: 'HR',
  从供应商列表页获取数字ID: 'Numeric ID from the supplier list page',
  从员工列表页获取数字ID: 'Numeric ID from the employee list page',
  从客户列表页获取数字ID: 'Numeric ID from the customer list page',
  '从科目列表获取数字ID，填了则按明细创建':
    'Numeric ID from the account list; when set, the voucher is created with line items',
  从销售订单列表页获取数字ID: 'Numeric ID from the sales order list page',
  仓储管理: 'Warehouse Management',
  仓库: 'Warehouse',
  仓库信息: 'Warehouse Info',
  付款单: 'Payment',
  付款单ID: 'Payment ID',
  付款单号: 'Payment No.',
  付款时间: 'Paid At',
  付款管理: 'Payments',
  仪表盘: 'Dashboard',
  价格: 'Price',
  任务: 'Task',
  任务管理: 'Tasks',
  企业所得税: 'Corporate Income Tax',
  优先级: 'Priority',
  优惠金额: 'Discount Amount',
  会计科目: 'Chart of Accounts',
  低库存预警: 'Low Stock Alerts',
  余额: 'Balance',
  供应商: 'Supplier',
  供应商ID: 'Supplier ID',
  供应商信息: 'Supplier Info',
  保修到期: 'Warranty Expiry',
  保养计划: 'Maintenance Plans',
  保养频率: 'Maintenance Frequency',
  保存: 'Save',
  '保存失败: {error}': 'Save failed: {error}',
  保存成功: 'Saved successfully',
  '修改失败: {error}': 'Change failed: {error}',
  修改密码: 'Change Password',
  借: 'Debit',
  借方合计: 'Total Debits',
  值: 'Value',
  全部: 'All',
  公海池: 'Lead Pool',
  公积金: 'Housing Fund',
  '共 {count} 个': '{count} total',
  '共 {total} 条': '{total} records',
  关联订单: 'Related Order',
  关联销售订单ID: 'Linked Sales Order ID',
  关闭: 'Close',
  其他: 'Other',
  内容: 'Content',
  冻结时间: 'Hold Until',
  净利率: 'Net Margin',
  '凭证ID: {id}': 'Voucher ID: {id}',
  凭证号: 'Voucher No.',
  凭证名称: 'Voucher Name',
  凭证日期: 'Voucher Date',
  出入库流水: 'Stock Movement',
  '出货检验(OQC)': 'Outgoing Inspection (OQC)',
  分区拣货: 'Pick by Zone',
  分类: 'Category',
  分组: 'Group',
  分配中: 'Allocating',
  分配库存: 'Allocate Stock',
  分配数量不能为空: 'Quantity is required',
  分配数量须为正数: 'Quantity must be a positive number',
  '创建失败: {error}': 'Create failed: {error}',
  创建履约: 'Create Fulfillment',
  创建成功: 'Created successfully',
  创建时间: 'Created At',
  删除: 'Delete',
  '删除({count})': 'Delete ({count})',
  '删除失败: {error}': 'Delete failed: {error}',
  删除成功: 'Deleted successfully',
  利润: 'Profit',
  利润中心: 'Profit Center',
  利润报表: 'Profit Report',
  '利润表 JSON *': 'Income Statement JSON *',
  到期日: 'Due Date',
  刷新: 'Refresh',
  加班费: 'Overtime Pay',
  '加载中...': 'Loading...',
  加载失败: 'Failed to load',
  '加载失败: {error}': 'Failed to load: {error}',
  '加载权限列表失败: {error}': 'Failed to load permissions: {error}',
  '加载用户列表失败: {error}': 'Failed to load users: {error}',
  '加载角色列表失败: {error}': 'Failed to load roles: {error}',
  包装类型: 'Package Type',
  单价: 'Price',
  单位: 'Unit',
  单据ID: 'Document ID',
  单据ID必须为数字: 'Document ID must be numeric',
  单据类型: 'Document Type',
  卖家备注: 'Seller Note',
  印花税: 'Stamp Duty',
  原因: 'Reason',
  原币ID: 'Source Currency ID',
  '参数(JSON)': 'Params (JSON)',
  参数验证失败: 'Validation failed',
  发放: 'Pay',
  '发放失败：{error}': 'Payment failed: {error}',
  发货仓库ID: 'Shipping Warehouse ID',
  发货单ID: 'Delivery ID',
  发货单号: 'Delivery No.',
  取消: 'Cancel',
  取消订单: 'Cancel Order',
  变更说明: 'Change Notes',
  合同名称: 'Contract Name',
  合同状态流转: 'Contract Status Transition',
  合同管理: 'Contracts',
  合同编号: 'Contract No.',
  '合并中...': 'Consolidating...',
  合并报表: 'Consolidated Reports',
  合格数量: 'Passed Qty',
  名称: 'Name',
  后端要求提供发货仓库: 'A shipping warehouse is required by the server',
  否: 'No',
  启用: 'Enable',
  员工: 'Employee',
  员工ID: 'Employee ID',
  员工档案: 'Employees',
  品牌: 'Brand',
  品牌管理: 'Brands',
  商品: 'Product',
  商品ID: 'Product ID',
  商品ID须为正整数: 'Product ID must be a positive integer',
  '商品ID（数字）': 'Product ID (numeric)',
  商品信息: 'Product Info',
  商品分类: 'Categories',
  商品列表: 'Product List',
  商品名称: 'Product Name',
  商品明细: 'Items',
  商品编码: 'Product Code',
  商机: 'Opportunity',
  商机管理: 'Opportunities',
  商品规格: 'Product Specs',
  固定: 'Fixed',
  固定资产: 'Fixed Asset',
  图表名称: 'Chart Name',
  图表管理: 'Manage Charts',
  '图表管理 — {name}': 'Manage Charts — {name}',
  图表类型: 'Chart Type',
  地址: 'Address',
  地点: 'Location',
  型号: 'Model',
  基本信息: 'Basic Info',
  基本工资: 'Base Salary',
  增值税: 'Value-Added Tax',
  处置方式: 'Disposition',
  备件: 'Spare Parts',
  备件名称: 'Spare Part Name',
  备件编码: 'Spare Part Code',
  备注: 'Notes',
  '多币种/汇率': 'Multi-Currency / FX Rates',
  天数: 'Days',
  失效日期: 'Valid To',
  '如 1.5': 'e.g. 1.5',
  '如 10.00': 'e.g. 10.00',
  '如 100.00': 'e.g. 100.00',
  '如 1000.00': 'e.g. 1000.00',
  '如 61000000000000001=CNY': 'e.g. 61000000000000001=CNY',
  '如 7.250000': 'e.g. 7.250000',
  '如 8000.00': 'e.g. 8000.00',
  '如 purchase_order / expense': 'e.g. purchase_order / expense',
  '如 {amount}': 'e.g. {amount}',
  姓名: 'Employee Name',
  婚假: 'Marriage Leave',
  '子公司报表 JSON 数组 *': 'Subsidiary Reports JSON Array *',
  存放位置: 'Location',
  季: 'Quarter',
  完成: 'Finish',
  定时调度: 'Schedules',
  实发工资: 'Net Pay',
  实时库存: 'Stock on Hand',
  审批: 'Approve',
  审批中: 'Approving',
  审批工作流: 'Workflow',
  审批意见为必填项: 'An approval comment is required',
  '审批意见（必填）': 'Approval Comment (required)',
  '审批意见（选填）': 'Approval Comment (optional)',
  审批流程: 'Workflow',
  审批记录: 'Approval Records',
  客户: 'Customer',
  客户ID: 'Customer ID',
  客户信息: 'Customer Info',
  客户分析: 'Customer Analytics',
  宽度: 'Width',
  密码: 'Password',
  密码修改成功: 'Password changed successfully',
  密码验证失败: 'Password verification failed',
  导入失败: 'Import failed',
  导入成功: 'Import successful',
  导出: 'Export',
  导出Excel: 'Export Excel',
  导出PDF: 'Export PDF',
  导出成功: 'Export successful',
  展开菜单: 'Expand menu',
  履约: 'Fulfill',
  履约单: 'Fulfillments',
  履约状态: 'Fulfillment Status',
  履约管理: 'Fulfillment',
  工作日期: 'Work Date',
  工作流定义: 'Workflows',
  工作站: 'Workstation',
  工作站ID: 'Workstation ID',
  工单ID: 'Work Order ID',
  工单编码: 'Work Order Code',
  工序号: 'Seq',
  工时: 'Timesheet',
  '工时(小时)': 'Hours',
  工时记录: 'Timesheets',
  工艺路线: 'Routing',
  已付金额: 'Paid Amount',
  已入库: 'Received',
  已关闭: 'Closed',
  已出库: 'Issued',
  已分配: 'Assigned',
  已发放: 'Paid',
  已发货: 'Shipped',
  已取件: 'Picked Up',
  已取消: 'Cancelled',
  已失效: 'Expired',
  已完成: 'Completed',
  已审批: 'Approved',
  已审核: 'Reviewed',
  已打包: 'Packed',
  已打款: 'Paid',
  已批准: 'Approved',
  已报价: 'Quoted',
  已拒绝: 'Rejected',
  已拣货: 'Picked',
  已撤回: 'Withdrawn',
  已支付: 'Paid',
  已收货: 'Received',
  已收金额: 'Received Amount',
  已核销: 'Settled',
  '已点击 {count}/{total}': 'Clicked {count}/{total}',
  已签收: 'Signed For',
  已终止: 'Terminated',
  已结算: 'Settled',
  已转订单: 'Converted to Order',
  已退回: 'Returned',
  已退款: 'Refunded',
  已送达: 'Delivered',
  已通过: 'Approved',
  已驳回: 'Rejected',
  币种: 'Currency',
  '币种列表中的数字ID，如 61000000000000002=USD':
    'Numeric ID from the currency list, e.g. 61000000000000002=USD',
  布局配置: 'Layout Config',
  年: 'Year',
  年份: 'Year',
  年假: 'Annual Leave',
  年度: 'Year',
  序列号: 'Serial Number',
  库位: 'Location',
  库位管理: 'Location Management',
  库区: 'Zone',
  库区管理: 'Zones',
  库存: 'Inventory',
  库存不足: 'Insufficient stock',
  库存总值: 'Inventory Value',
  库存数量: 'Stock Qty',
  库存流水: 'Stock Movements',
  库存调拨: 'Stock Transfer',
  库存预警: 'Stock Alerts',
  应付: 'Payable',
  应付账龄: 'AP Aging',
  应付金额: 'Payable Amount',
  应发工资: 'Gross Pay',
  应收: 'Receivable',
  应收应付: 'AR/AP',
  应收账龄: 'AR Aging',
  应收金额: 'Receivable Amount',
  应纳税所得额: 'Taxable Income',
  开始日期: 'Start Date',
  开始时间: 'Start Time',
  开始维修: 'Start Repair',
  开户银行: 'Bank Name',
  异常: 'Exception',
  当前状态不允许此操作: 'Operation not allowed in current status',
  当前状态无可流转的目标状态: 'No target status available for the current status',
  当前节点: 'Current Node',
  往来单位: 'Counterparty',
  '往来单位与所选类型不匹配，请重新选择':
    'Counterparty does not match the selected type, please re-select',
  待入库: 'Pending Receipt',
  待出库: 'Pending Issue',
  待发货: 'Ready to Ship',
  待处理: 'Pending',
  待审批: 'Pending',
  待审核: 'Pending Review',
  待打包: 'Pending Pack',
  待拣货: 'Pending Pick',
  待支付: 'Pending Payment',
  微信: 'WeChat',
  '必填（后端校验）': 'Required (validated by server)',
  '必填（后端校验），如 OM+时间戳': 'Required (validated by server), e.g. OM+timestamp',
  总览: 'Overview',
  '总账/明细账': 'General / Detail Ledger',
  总金额: 'Total Amount',
  恢复成功: 'Restored successfully',
  成功: 'Success',
  '成本/利润中心': 'Cost / Profit Centers',
  成本中心: 'Cost Center',
  成本价: 'Unit Cost',
  我的审批: 'My Approvals',
  '截止重量(kg)': 'Weight To (kg)',
  所有者权益: "Owner\\'s Equity",
  手机号: 'Phone',
  打包中: 'Packing',
  打包任务: 'Pack Task',
  打包单: 'Pack Task',
  打包管理: 'Packing',
  扣款: 'Deductions',
  执行: 'Run',
};
