/*
 * Copyright (c) 2026 erik <erik@erik.xyz> — https://erik.xyz
 */

// 词典切片 6/6，由 ./index 合并导出；查找词条请 grep 整个目录。
// 后补词条（列标题/状态标签/帮助文案），按中文键码位排序。

export const zhEnPart6: Record<string, string> = {
  'ABC分类': 'ABC Classification',
  'BOM 已生效，同产品其它版本已转失效': 'BOM is now effective; other versions of this product are superseded',
  'Offer 已拒绝，候选人退回面试中': 'Offer rejected, candidate returned to interview',
  'Offer 已接受，候选人已入职': 'Offer accepted, candidate onboarded',
  '上架单': 'Putaway Order',
  '上级': 'Manager Review',
  '下拉': 'Select',
  '专业': 'Professional',
  '两日达': '2-Day',
  '严重': 'Major',
  '使用中': 'In Use',
  '信封': 'Envelope',
  '借方': 'Debit',
  '停职': 'Suspended',
  '先进先出': 'FIFO',
  '入库': 'Inbound',
  '关': 'Closed',
  '关联收款单': 'Linked Receipt',
  '冻结': 'Frozen',
  '凭证已审核': 'Voucher Reviewed',
  '凭证数': 'Voucher Count',
  '出差': 'Business Trip',
  '出库': 'Outbound',
  '加急': 'Rush',
  '动态盘点': 'Dynamic Stocktake',
  '双倍余额递减法': 'Double Declining Balance',
  '发货区': 'Shipping Zone',
  '发货波次': 'Shipping Wave',
  '可用': 'Available',
  '同事360': 'Peer 360',
  '后进先出': 'LIFO',
  '咨询': 'Consultation',
  '售后退货单': 'After-sales Return',
  '固定货位': 'Fixed Bin',
  '在职': 'Active',
  '多行文本': 'Textarea',
  '失败': 'Failed',
  '女': 'Female',
  '委外发料单': 'Subcontract Material Issue',
  '委外收货单': 'Subcontract Receiving Note',
  '存储区': 'Storage Zone',
  '工时归集': 'Timesheet',
  '已出': 'Issued',
  '已勾选待抵扣': 'Checked, Pending Deduction',
  '已处置': 'Disposed',
  '已开具': 'Issued',
  '已红冲': 'Reversed',
  '年数总和法': 'Sum of Years Digits',
  '开': 'Open',
  '异常待维修': 'Awaiting Repair',
  '待执行': 'Pending',
  '待验真': 'Pending Verification',
  '快递': 'Express',
  '手工': 'Manual',
  '手工录入': 'Manual Entry',
  '打包区': 'Packing Zone',
  '托盘': 'Pallet',
  '扣除': 'Deductions',
  '批量导入': 'Bulk Import',
  '技术': 'Technical',
  '投诉': 'Complaint',
  '折线': 'Line',
  '报价': 'Quote',
  '报废': 'Scrap',
  '拜访': 'Visit',
  '拣货区': 'Picking Zone',
  '拣货波次': 'Picking Wave',
  '指标': 'Metric',
  '接受': 'Accept',
  '接口': 'API',
  '推进下一级': 'Advance to Next Stage',
  '收货任务ID': 'Receiving Task ID',
  '收货区': 'Receiving Zone',
  '收货完成时间': 'Receipt Completed At',
  '收货已开始': 'Receiving Started',
  '收货明细': 'Receipt Details',
  '收货月台库位ID': 'Receiving Dock Location ID',
  '收起': 'Collapse',
  '数字': 'Number',
  '数字 ID 或 hashid，留空=不分规格': 'Numeric ID or hashid; leave blank for no variant',
  '数据来源': 'Data Source',
  '数据类型': 'Data Type',
  '数电出口状态': 'E-Invoice Export Status',
  '数电票号码': 'E-Invoice Number',
  '整车': 'FTL',
  '文本': 'Text',
  '文档ID': 'Document ID',
  '新归属人ID': 'New Owner ID',
  '旗舰': 'Enterprise',
  '无跟进自动回收天数': 'Auto-recycle Days Without Follow-up',
  '日记账行ID': 'Journal Line ID',
  '早退': 'Early Leave',
  '早退分钟数': 'Early-leave Minutes',
  '早退宽限分钟数': 'Early-leave Grace Minutes',
  '明细': 'Details',
  '明细行': 'Detail Rows',
  '明细行数': 'Line Items',
  '是否内部': 'Internal',
  '是否可见': 'Visible',
  '是否基本单位': 'Base Unit',
  '是否已读': 'Read',
  '是否必填': 'Is Required',
  '是否成功': 'Succeeded',
  '是否计税': 'Taxable',
  '是否首要联系人': 'Primary Contact',
  '是否默认账套': 'Default Ledger',
  '显示名': 'Display Name',
  '最低价': 'Lowest Price',
  '最低价报价ID': 'Lowest Quote ID',
  '最后登录IP': 'Last Login IP',
  '最后登录时间': 'Last Login',
  '最多 200 字': 'Up to 200 characters',
  '最大容积': 'Max Volume',
  '最大承重': 'Max Load',
  '最小库存': 'Min Stock',
  '最近一次成功投递时间': 'Last Successful Delivery',
  '最近一次投递结果': 'Last Delivery Result',
  '月折旧额': 'Monthly Depreciation',
  '有效': 'Valid',
  '有效期至': 'Valid Until',
  '服务编码': 'Service Code',
  '期初借方余额': 'Opening Debit Balance',
  '期初现金余额': 'Opening Cash Balance',
  '期初贷方余额': 'Opening Credit Balance',
  '期数': 'Periods',
  '期末借方余额': 'Closing Debit Balance',
  '期末现金余额': 'Closing Cash Balance',
  '期末贷方余额': 'Closing Credit Balance',
  '未勾选': 'Not Checked',
  '未开具': 'Not Issued',
  '本期借方发生额': 'Current Period Debit',
  '本期贷方发生额': 'Current Period Credit',
  '权重': 'Weight',
  '权限ID': 'Permission ID',
  '材料成本': 'Material Cost',
  '材料成本差异': 'Material Cost Variance',
  '条件值': 'Condition Value',
  '条件字段': 'Condition Field',
  '条件操作符': 'Condition Operator',
  '来源保养计划ID': 'Source Maintenance Plan ID',
  '来源单据ID': 'Source Document ID',
  '来源工时记录ID': 'Source Timesheet ID',
  '来源成本中心ID': 'Source Cost Center ID',
  '来源明细ID': 'Source Line ID',
  '查询结果数据': 'Query Result Data',
  '查询配置': 'Query Configuration',
  '柱状': 'Bar',
  '标准': 'Standard',
  '标准工时': 'Standard Hours',
  '标准材料成本': 'Standard Material Cost',
  '标题模板': 'Title Template',
  '核销成本快照': 'Write-off Cost Snapshot',
  '核销时间': 'Written Off At',
  '核销来源': 'Write-off Source',
  '检验规格说明': 'Inspection Spec Notes',
  '次日达': 'Next Day',
  '每人最大领取数': 'Max Per Person',
  '每小时产能': 'Capacity per Hour',
  '比价矩阵': 'Comparison Matrix',
  '毛需求量': 'Gross Requirement',
  '波次ID': 'Wave ID',
  '活动': 'Event',
  '活动ID': 'Campaign ID',
  '活跃度': 'Activity',
  '流水后积分快照': 'Points After Transaction Snapshot',
  '海运': 'Ocean',
  '淘汰': 'Eliminate',
  '添加明细': 'Add Line',
  '渠道单号': 'Channel Order No.',
  '渠道编码': 'Channel Code',
  '渠道返回消息ID': 'Channel Response Message ID',
  '满 X 可用': 'Usable over X',
  '满减=减免额': 'Full Reduction = Discount Amount',
  '漏斗阶段': 'Pipeline Stage',
  '漏斗阶段ID': 'Pipeline Stage ID',
  '点检项名称': 'Check Item Name',
  '燃油附加费率': 'Fuel Surcharge Rate',
  '物流单号': 'Tracking No.',
  '物流追踪URL模板': 'Tracking URL Template',
  '状态码': 'Status Code',
  '现有库存量': 'On-hand Stock',
  '甘特图数据JSON': 'Gantt Chart Data JSON',
  '生产中': 'In Production',
  '生产完工单': 'Production Completion',
  '生产日期': 'Production Date',
  '生产领料单': 'Material Requisition',
  '生成收货任务': 'Generate Receipt Task',
  '生效': 'Activate',
  '申报价值': 'Declared Value',
  '电商平台': 'Marketplace',
  '男': 'Male',
  '画布快照': 'Canvas Snapshot',
  '留存率': 'Retention',
  '留空即按商品自动匹配本单明细行': 'Leave blank to auto-match this order\'s lines by product',
  '留空由后端自动生成': 'Leave blank to auto-generate',
  '盘点人ID': 'Counter ID',
  '盘点任务ID': 'Count Task ID',
  '盘点时间': 'Counted At',
  '目标值描述': 'Target Description',
  '目标单价': 'Target Unit Price',
  '目标受众': 'Target Audience',
  '目标总额': 'Target Total',
  '目标成本中心ID': 'Target Cost Center ID',
  '目标金额': 'Target Amount',
  '目的国ISO代码': 'Destination Country ISO Code',
  '直销': 'Direct',
  '省/州': 'State/Province',
  '短信': 'Message',
  '短信通知': 'SMS Notification',
  '社交': 'Social',
  '社保': 'Social Security',
  '离职': 'Resigned',
  '科目编码': 'Account Code',
  '租户编码': 'Tenant Code',
  '积分': 'Points',
  '移动平均前成本': 'Cost Before Moving Average',
  '移动平均后成本': 'Cost After Moving Average',
  '移动端': 'Mobile',
  '税率ID': 'Tax Rate ID',
  '空运': 'Air',
  '站内通知': 'In-app Notification',
  '筛选类型': 'Filter Type',
  '筹资活动净流量': 'Net Cash Flow from Financing',
  '筹资活动现金流入': 'Cash Inflow from Financing',
  '筹资活动现金流出': 'Cash Outflow from Financing',
  '签名密钥': 'Signing Key',
  '简历摘要': 'Resume Summary',
  '紧急': 'Urgent',
  '紧急联系人': 'Emergency Contact',
  '紧急联系电话': 'Emergency Phone',
  '累计折旧': 'Accumulated Depreciation',
  '累计收货数量': 'Cumulative Received Qty',
  '纸张规格': 'Paper Size',
  '纸箱': 'Box',
  '组成件产品ID': 'Component Product ID',
  '组织ID': 'Organization ID',
  '经济': 'Economy',
  '经营活动净流量': 'Net Cash Flow from Operating',
  '经营活动现金流入': 'Cash Inflow from Operating',
  '经营活动现金流出': 'Cash Outflow from Operating',
  '结果行数': 'Result Row Count',
  '维修中': 'Under Repair',
  '缴费基数': 'Contribution Base',
  '缺卡': 'Missing Punch',
  '网页': 'Web',
  '考核周期开始': 'Review Period Start',
  '考核周期结束': 'Review Period End',
  '职级': 'Job Level',
  '联系人ID': 'Contact ID',
  '联系电话': 'Contact Phone',
  '聚合函数': 'Aggregate Function',
  '背书时间': 'Endorsed At',
  '自定义': 'Custom',
  '自评': 'Self Review',
  '致命': 'Critical',
  '营收': 'Revenue',
  '表格': 'Table',
  '袋子': 'Bag',
  '被背书人': 'Endorsee',
  '规划中': 'Planned',
  '规则ID': 'Rule ID',
  '角色ID': 'Role ID',
  '解决时间': 'Resolved At',
  '计件单价': 'Piece Rate',
  '计件工资': 'Piece-rate Wages',
  '计划ID': 'Plan ID',
  '计划中': 'Planned',
  '计划开始': 'Planned Start',
  '计划开始日期': 'Planned Start Date',
  '计划接收量': 'Planned Receipt Qty',
  '计划时间': 'Scheduled At',
  '计划盘点': 'Planned Stocktake',
  '计划结束日期': 'Planned End Date',
  '计划订单量': 'Planned Order Qty',
  '计税金额': 'Taxable Amount',
  '订单明细ID': 'Order Line ID',
  '订单明细行': 'Order Line',
  '订阅ID': 'Subscription ID',
  '让步接收': 'Accept',
  '记账日期': 'Posting Date',
  '评价': 'Rating',
  '评估人ID': 'Assessor ID',
  '评估日期': 'Assessment Date',
  '评分人ID': 'Rater ID',
  '评分人类型': 'Rater Type',
  '评分维度': 'Rating Dimension',
  '询价单ID': 'Inquiry ID',
  '询价单号': 'Inquiry No.',
  '询价单已发布': 'Inquiry Published',
  '询价单明细ID': 'Inquiry Line ID',
  '询价明细': 'Inquiry Details',
  '说明文本（后端字段即文本，非供应商选择）': 'Free-text note (the backend field is plain text, not a supplier picker)',
  '请求参数': 'Request Parameters',
  '请求报文': 'Request Payload',
  '课程ID': 'Course ID',
  '调入仓库': 'Destination Warehouse',
  '调入仓库ID': 'Destination Warehouse ID',
  '调入库位ID': 'Destination Location ID',
  '调出仓库ID': 'Source Warehouse ID',
  '调出库位ID': 'Source Location ID',
  '调拨单ID': 'Transfer Order ID',
  '调拨时间': 'Transferred At',
  '账套ID': 'Ledger ID',
  '账面数量': 'Book Qty',
  '货位': 'Bin',
  '货币符号': 'Currency Symbol',
  '货架': 'Rack',
  '质检区': 'Inspection Zone',
  '购买方名称': 'Buyer Name',
  '购买方税号': 'Buyer Tax No.',
  '贴现息': 'Discount Interest',
  '贴现时间': 'Discounted At',
  '贷方': 'Credit',
  '贷方金额': 'Credit Amount',
  '费率': 'Rate',
  '费用科目 ID': 'Expense Account ID',
  '费用科目无列表接口，按 ID 填写（后端双模解码）': 'No expense-account list endpoint; enter an ID (the backend decodes both forms)',
  '资产ID': 'Asset ID',
  '跟进时间': 'Follow-up Time',
  '身份证号': 'ID Number',
  '转自哪张采购申请，可空；选定后该申请单状态置「已转订单」': 'Purchase request this order was converted from; optional; selecting one sets that request to Converted to Order',
  '轻微': 'Minor',
  '过期日期': 'Expiry Date',
  '过期时间': 'Expires At',
  '运单ID': 'Shipment ID',
  '返修': 'Repair',
  '进度': 'Progress',
  '连续失败计数': 'Consecutive Failure Count',
  '迟到': 'Late',
  '迟到分钟数': 'Late Minutes',
  '迟到宽限分钟数': 'Late Grace Minutes',
  '退换类型': 'Return Type',
  '退货区': 'Return Zone',
  '退货单ID': 'Return Order ID',
  '退货运费': 'Return Shipping Fee',
  '选项': 'Option',
  '通知类型': 'Notification Type',
  '邮件': 'Email',
  '邮编': 'Postal Code',
  '配置': 'Configuration',
  '采购员': 'Buyer',
  '采购员ID': 'Buyer ID',
  '采购收货单': 'Purchase Receiving Note',
  '采购明细': 'Purchase Details',
  '采购订单ID': 'Purchase Order ID',
  '重量': 'Weight',
  '重量止': 'Weight To',
  '重量起': 'Weight From',
  '铁路': 'Rail',
  '银行承兑': 'Bank Acceptance',
  '银行转账': 'Bank Transfer',
  '销售发货单': 'Sales Delivery Note',
  '销售方名称': 'Seller Name',
  '销售方税号': 'Seller Tax No.',
  '销售明细': 'Sales Details',
  '长': 'Length',
  '阅读时间': 'Read At',
  '阶段已推进': 'Stage Advanced',
  '险种': 'Insurance Type',
  '零担': 'LTL',
  '需求日期': 'Required Date',
  '面单URL': 'Shipping Label URL',
  '面试官ID': 'Interviewer ID',
  '页面方向': 'Page Orientation',
  '预估单价': 'Estimated Unit Price',
  '预估工时': 'Estimated Hours',
  '预占数量': 'Reserved Qty',
  '预期数量': 'Expected Qty',
  '预算ID': 'Budget ID',
  '预算编号': 'Budget No.',
  '预算金额': 'Budget Amount',
  '预警类型': 'Alert Type',
  '预计到货时间': 'Estimated Arrival Time',
  '预计成交日期': 'Expected Close Date',
  '预计最多天数': 'Max Expected Days',
  '预计最少天数': 'Min Expected Days',
  '预计赢单率': 'Expected Win Rate',
  '预计送达时间': 'Estimated Delivery Time',
  '领料单ID': 'Material Requisition ID',
  '领料明细': 'Material Requisition Details',
  '饼图': 'Pie',
  '驳回意见': 'Rejection Comment',
  '验真失败': 'Verification Failed',
  '验真时间': 'Verified At',
  '验真状态': 'Verification Status',
  '验真通过': 'Verified',
  '高': 'High',
  '默认值': 'Default Value',
  '默认账簿': 'Default Ledger',
};
