/*
 * Copyright (c) 2026 erik <erik@erik.xyz> — https://erik.xyz
 */

// 词典切片 5/6，由 ./index 合并导出；查找词条请 grep 整个目录。
// 后补词条（列标题/状态标签/帮助文案），按中文键码位排序。

export const zhEnPart5: Record<string, string> = {
  '0 ~ 票面金额': '0 to Face Amount',
  '0-100；等级由后端派生': '0-100; level is derived by the backend',
  'API供应商': 'API Provider',
  'API配置': 'API Configuration',
  'HTTP 状态码': 'HTTP Status Code',
  'JSON 对象，如 {"颜色":["红","蓝"]}；留空为 {}': 'JSON object, e.g. {"Color":["Red","Blue"]}; leave blank for {}',
  'OMS订单ID': 'OMS Order ID',
  'RMA 单号': 'RMA No.',
  'SKU hashid，留空=不分规格': 'SKU hashid; leave blank for no variant',
  'SKU编码': 'SKU Code',
  'TMS退货运单ID': 'TMS Return Shipment ID',
  'WIP台账ID': 'WIP Ledger ID',
  'X 坐标': 'X Coordinate',
  'Y 坐标': 'Y Coordinate',
  '上架中': 'Putting Away',
  '上架任务ID': 'Putaway Task ID',
  '上架已开始': 'Putaway Started',
  '上架库位': 'Putaway Location',
  '上架策略': 'Putaway Strategy',
  '上次执行时间': 'Last Run At',
  '上次维护日期': 'Last Maintained On',
  '上班打卡时间': 'Clock-in Time',
  '下一步计划': 'Next Steps',
  '下次执行时间': 'Next Run At',
  '下次维护日期': 'Next Maintenance Date',
  '下次跟进时间': 'Next Follow-up At',
  '下次重试时间': 'Next Retry At',
  '下班打卡时间': 'Clock-out Time',
  '不含税金额': 'Amount Excl. Tax',
  '业务类型': 'Business Type',
  '个人比例': 'Employee Share',
  '中': 'Medium',
  '中标报价': 'Winning Quote',
  '中标报价ID': 'Winning Quote ID',
  '中标标记': 'Winning Bid Mark',
  '主键ID': 'Primary Key ID',
  '主题/标题': 'Subject / Title',
  '事件时间': 'Event Time',
  '事件载荷': 'Event Payload',
  '交易后余额': 'Balance After Transaction',
  '交易日期': 'Transaction Date',
  '产品图片URL': 'Product Image URL',
  '人工成本': 'Labor Cost',
  '价格类型': 'Price Type',
  '价税合计': 'Total Incl. Tax',
  '会员ID': 'Member ID',
  '会计年度': 'Fiscal Year',
  '会计月份': 'Fiscal Month',
  '会计期间 YYYY-MM': 'Fiscal Period YYYY-MM',
  '位置': 'Position',
  '低': 'Low',
  '作废原因': 'Void Reason',
  '作者': 'Author',
  '供应商范围': 'Supplier Scope',
  '保价费': 'Insured Value Fee',
  '保修到期日': 'Warranty Expiry Date',
  '信用冻结': 'Credit Hold',
  '借方金额': 'Debit Amount',
  '允许访问的路径前缀数组': 'Allowed Path Prefixes',
  '允许超期未收余额上限': 'Overdue Balance Limit',
  '允许超限比例%': 'Allowed Overage %',
  '兑付/解付时间': 'Payment/Release Time',
  '入库流水ID': 'Inbound Transaction ID',
  '公司比例': 'Employer Share',
  '关联商品规格ID': 'Related SKU ID',
  '关联商机ID': 'Related Opportunity ID',
  '关闭时间': 'Closed At',
  '其他成本': 'Other Cost',
  '内容哈希': 'Content Hash',
  '内容模板': 'Content Template',
  '冻结到指定时间': 'Frozen Until',
  '净利润': 'Net Profit',
  '净需求量': 'Net Requirement',
  '凭证ID': 'Voucher ID',
  '凭证分录ID': 'Voucher Entry ID',
  '出库流水ID': 'Outbound Transaction ID',
  '出库确认': 'Confirm Outbound',
  '出生日期': 'Date of Birth',
  '出表时间': 'Report Generated At',
  '分摊依据': 'Allocation Basis',
  '分配明细': 'Allocation Details',
  '创建人ID': 'Created By ID',
  '到期日期': 'Due Date',
  '到货通知单ID': 'ASN ID',
  '制造费用': 'Manufacturing Overhead',
  '券类型': 'Coupon Type',
  '前置任务ID': 'Predecessor Task ID',
  '加入时间': 'Joined At',
  '包裹数量': 'Package Qty',
  '包裹编号': 'Package No.',
  '匹配方式': 'Match Method',
  '区/县': 'District/County',
  '单位名称': 'Unit Name',
  '单位成本': 'Unit Cost',
  '单据': 'Document',
  '单据 ID': 'Document ID',
  '单据的 hashid（取单据列表 ID 列的值）': 'Document hashid (take it from the ID column of the document list)',
  '原始数据': 'Raw Data',
  '原归属人ID': 'Previous Owner ID',
  '参与时间': 'Participated At',
  '发件地址快照': 'Sender Address Snapshot',
  '发布时间': 'Published At',
  '发放后有效天数': 'Valid Days After Issue',
  '发放总量': 'Total Issued',
  '发料明细': 'Material Issue Details',
  '发票ID': 'Invoice ID',
  '发票代码': 'Invoice Code',
  '发票日期': 'Invoice Date',
  '发货仓库': 'Shipping Warehouse',
  '发货时间': 'Shipped At',
  '发货明细': 'Shipment Details',
  '发送时间': 'Sent At',
  '发送渠道': 'Delivery Channel',
  '取件前为空': 'Empty before pickup',
  '变更人': 'Changed By',
  '可否驳回': 'Can Reject',
  '可用工时': 'Available Hours',
  '合同ID': 'Contract ID',
  '合并报表ID': 'Consolidated Report ID',
  '后端 NOT NULL，留空直接 500': 'Backend NOT NULL; leaving it blank causes a 500',
  '后端按整数 SKU ID 校验（暂无 SKU 列表接口）': 'Backend validates an integer SKU ID (no SKU list endpoint yet)',
  '含税金额': 'Amount Incl. Tax',
  '响应体/错误信息摘要': 'Response Body / Error Summary',
  '响应内容': 'Response Body',
  '售后单ID': 'After-sales Order ID',
  '商业承兑': 'Commercial Acceptance',
  '回复内容': 'Reply Content',
  '国家ISO代码': 'Country ISO Code',
  '在库': 'In Stock',
  '地址行1': 'Address Line 1',
  '地址行2': 'Address Line 2',
  '外部单据ID': 'External Document ID',
  '失败原因': 'Failure Reason',
  '头像URL': 'Avatar URL',
  '套餐': 'Plan',
  '如 purchase_order': 'e.g. purchase_order',
  '始发区域': 'Origin Region',
  '始发国ISO代码': 'Origin Country ISO Code',
  '字段名': 'Field Name',
  '字段标识': 'Field Key',
  '字段类型': 'Field Type',
  '完工数量': 'Completed Qty',
  '完成时间': 'Completed At',
  '完整报表数据JSON': 'Full Report Data JSON',
  '官网': 'Website',
  '实体类型': 'Entity Type',
  '实拣数量': 'Picked Qty',
  '实拣明细': 'Picked Details',
  '实收数量': 'Received Qty',
  '实收明细': 'Received Details',
  '实际到货时间': 'Actual Arrival Time',
  '实际完成时间': 'Actual End Time',
  '实际工时': 'Actual Hours',
  '实际开始时间': 'Actual Start Time',
  '实际成本': 'Actual Cost',
  '实际执行的SQL语句': 'Executed SQL Statement',
  '实际数量': 'Actual Qty',
  '实际材料成本': 'Actual Material Cost',
  '实际签收时间': 'Actual Delivery Time',
  '实际金额': 'Actual Amount',
  '审批人ID': 'Approver ID',
  '审批人类型': 'Approver Type',
  '审批实例ID': 'Approval Instance ID',
  '审批时间': 'Approved At',
  '审批节点ID': 'Approval Node ID',
  '审核人ID': 'Reviewer ID',
  '审核意见': 'Review Comment',
  '审核时间': 'Reviewed At',
  '客户确认': 'Customer Confirmation',
  '客户等级ID': 'Customer Level ID',
  '宽': 'Width',
  '密钥哈希': 'Key Hash',
  '对方户名': 'Counterparty Account Name',
  '对账单行ID': 'Statement Line ID',
  '导入批次号': 'Import Batch No.',
  '展开': 'Expand',
  '履约记录ID': 'Fulfillment Record ID',
  '工作流ID': 'Workflow ID',
  '差异数量': 'Variance Qty',
  '已上架': 'Put Away',
  '已中标': 'Won',
  '已付款': 'Paid',
  '已分配数量': 'Allocated Qty',
  '已到期兑付': 'Matured and Paid',
  '已发布': 'Published',
  '已发放数量': 'Issued Qty',
  '已发数量': 'Issued Qty',
  '已发料': 'Materials Issued',
  '已发料金额累计': 'Issued Amount Total',
  '已发送': 'Sent',
  '已处理': 'Processed',
  '已完成数量': 'Completed Qty',
  '已审核入账': 'Reviewed and Posted',
  '已尝试次数': 'Attempts',
  '已延期': 'Deferred',
  '已开始上架': 'Putaway Started',
  '已开始打包': 'Packing Started',
  '已开始拣货': 'Picking Started',
  '已开始收货': 'Receiving Started',
  '已开票金额累计': 'Invoiced Amount Total',
  '已成交': 'Deal Won',
  '已打包数量': 'Packed Qty',
  '已抵扣': 'Deducted',
  '已提交审核': 'Submitted for Review',
  '已收': 'Received',
  '已核销金额': 'Written-off Amount',
  '已生成': 'Generated',
  '已生成收货任务': 'Receipt Task Generated',
  '已盘点': 'Counted',
  '已确认': 'Confirmed',
  '已背书': 'Endorsed',
  '已解决': 'Resolved',
  '已调入': 'Transferred In',
  '已调出': 'Transferred Out',
  '已质检': 'Inspected',
  '已贴现': 'Discounted',
  '已转合同': 'Converted to Contract',
  '已退票': 'Returned',
  '巷道': 'Aisle',
  '布局': 'Layout',
  '平台适配器标识)': 'Platform Adapter Key)',
  '库位 hashid': 'Location hashid',
  '库位 hashid，留空=待定': 'Location hashid; leave blank = undetermined',
  '库存流水ID': 'Inventory Transaction ID',
  '应拣数量': 'Qty to Pick',
  '应收应付明细ID': 'AR/AP Detail ID',
  '应用 Key': 'App Key',
  '应用密钥': 'App Secret',
  '开始上架': 'Start Putaway',
  '开始打包': 'Start Packing',
  '开始拣货': 'Start Picking',
  '开始收货': 'Start Receiving',
  '开票(应付)': 'Invoice (Payable)',
  '开票申请': 'Invoice Request',
  '开通时间': 'Activated At',
  '当前审批节点ID': 'Current Approval Node ID',
  '当前库存数量': 'On-hand Qty',
  '待上架': 'Pending Putaway',
  '待开始': 'Not Started',
  '待收货': 'Pending Receipt',
  '待生产': 'Pending Production',
  '待盘点': 'Pending Count',
  '待调拨': 'Pending Transfer',
  '得分': 'Score',
  '必填': 'Required',
  '性别': 'Gender',
  '总件数': 'Total Pieces',
  '总体积': 'Total Volume',
  '总分': 'Total Score',
  '总重量': 'Total Weight',
  '成交概率': 'Win Probability',
  '成本中心ID': 'Cost Center ID',
  '成本单价': 'Cost Price',
  '成本合计': 'Total Cost',
  '成本类型': 'Cost Type',
  '所属库位': 'Location',
  '所有者权益总计': 'Total Equity',
  '打包任务ID': 'Packing Task ID',
  '托收中': 'In Collection',
  '托收时间': 'Collection Time',
  '执行时使用的参数': 'Runtime Parameters',
  '批次': 'Batch',
  '承兑类型': 'Acceptance Type',
  '承运商ID': 'Carrier ID',
  '承运商编码': 'Carrier Code',
  '投资活动净流量': 'Net Cash Flow from Investing',
  '投资活动现金流入': 'Cash Inflow from Investing',
  '投资活动现金流出': 'Cash Outflow from Investing',
  '折旧金额': 'Depreciation Amount',
  '报价ID': 'Quote ID',
  '报价单ID': 'Quotation ID',
  '报价单价': 'Quoted Unit Price',
  '报价总额': 'Quote Total',
  '报价日期': 'Quote Date',
  '报价明细': 'Quote Details',
  '报销单号': 'Expense No.',
  '抵扣期间': 'Deduction Period',
  '抵扣状态': 'Deduction Status',
  '拣货任务ID': 'Picking Task ID',
  '拣货时间': 'Picked At',
  '拣货明细': 'Picking Details',
  '拣货顺序': 'Pick Sequence',
  '指派人员ID': 'Assignee ID',
  '指派给': 'Assigned To',
  '按商品匹配本询价单的明细行': 'Match this inquiry\'s lines by product',
  '损耗率': 'Shrinkage Rate',
  '换算比率': 'Conversion Rate',
  '排序号': 'Sort Order',
  '接收方': 'Recipient',
  '提交人ID': 'Submitted By ID',
  '摘要/流水号': 'Memo / Reference No.',
  '操作IP': 'Operator IP',
  '操作人ID': 'Operator ID',
  '操作动作': 'Action',
  '支出': 'Expense',
  '收件地址快照': 'Recipient Address Snapshot',
  '收入': 'Income',
  '收票(应收)': 'Invoice (Receivable)',
  '收货中': 'Receiving',
  '收货人ID': 'Receiver ID',
};
