/*
 * Copyright (c) 2026 erik <erik@erik.xyz> — https://erik.xyz
 */

// 词典切片 2/4，由 ./index 合并导出；查找词条请 grep 整个目录。

export const zhEnPart2: Record<string, string> = {
  执行中: 'Active',
  执行合并: 'Run Consolidation',
  '执行失败：{error}': 'Execution failed: {error}',
  批准: 'Approve',
  批准时间: 'Approved At',
  批准请假: 'Approve Leave',
  批次号: 'Batch No.',
  '批量删除失败: {error}': 'Batch delete failed: {error}',
  批量删除完成: 'Selected users deleted',
  批量删除成功: 'Batch delete successful',
  批量启用: 'Enable Selected',
  批量启用完成: 'Selected users enabled',
  批量拣货: 'Pick by Batch',
  批量操作成功: 'Batch operation successful',
  批量禁用: 'Disable Selected',
  批量禁用完成: 'Selected users disabled',
  承运商: 'Carrier',
  承运商服务: 'Carrier Service',
  承运服务: 'Carrier Service',
  投资活动净额: 'Net Investing Cash Flow',
  投资活动流入: 'Investing Inflows',
  投资活动流出: 'Investing Outflows',
  折旧年份: 'Depreciation Year',
  折旧月份: 'Depreciation Month',
  折旧计提成功: 'Depreciation recorded',
  报价单: 'Quotation',
  报价单号: 'Quotation No.',
  报价时间: 'Quoted At',
  报价转合同: 'Quotation to Contract',
  报价金额: 'Quotation Amount',
  报告人: 'Reporter',
  报表: 'Report',
  报表名称: 'Report Name',
  报表管理: 'Reports',
  报表类型: 'Report Type',
  '报表结果：{name}': 'Report Result: {name}',
  '报表说明: {note}': 'Report note: {note}',
  抽样方案: 'Sampling Plan',
  拒绝: 'Reject',
  拣货中: 'Picking',
  拣货任务: 'Pick Task',
  拣货单: 'Pick Task',
  拣货管理: 'Picking',
  指标名称: 'Metric Name',
  指标类型: 'Metric Type',
  指标键名: 'Metric Key',
  指派: 'Assign',
  指派人: 'Assignee',
  指派工单: 'Assign Ticket',
  按单拣货: 'Pick by Order',
  换一张: 'Refresh',
  换货: 'Exchange',
  排序: 'Sort Order',
  接收人: 'Recipient',
  描述: 'Description',
  提交: 'Submit',
  '提交中...': 'Submitting...',
  提交人: 'Submitted By',
  '提交失败：{error}': 'Submit failed: {error}',
  提交审批: 'Submit for Approval',
  '提交审批：{name}': 'Submit for Approval: {name}',
  提交成功: 'Submitted successfully',
  提交时间: 'Submitted At',
  提示: 'Info',
  搜索: 'Search',
  '搜索...': 'Search...',
  '搜索商品名称/编码/批次号': 'Search product name, code or batch',
  '搜索用户名/姓名': 'Search username/name',
  摘要: 'Summary',
  撤回: 'Withdraw',
  '撤回失败: {error}': 'Withdraw failed: {error}',
  撤回审批: 'Withdraw Approval',
  操作: 'Actions',
  操作失败: 'Operation failed',
  '操作失败，请重试': 'Operation failed, please retry',
  '操作失败：{error}': 'Operation failed: {error}',
  操作成功: 'Operation successful',
  操作日志: 'Operation Log',
  操作筛选: 'Filter by action',
  操作者: 'Operator',
  支付宝: 'Alipay',
  支付状态: 'Payment Status',
  收入结转: 'Revenue Carryforward',
  收款单: 'Receipt',
  收款单ID: 'Receipt ID',
  收款单号: 'Receipt No.',
  收款时间: 'Received At',
  收款管理: 'Receipts',
  收货仓库ID: 'Receiving Warehouse ID',
  收货单ID: 'Receiving ID',
  收货单号: 'Receiving No.',
  收货时间: 'Received At',
  收货管理: 'Receiving',
  收起菜单: 'Collapse menu',
  故障描述: 'Fault Description',
  敏感操作需要输入密码确认: 'Password confirmation required for sensitive operations',
  '数据趋势（近30天）': 'Data Trend (Last 30 Days)',
  数据集: 'Datasets',
  数据集ID: 'Dataset ID',
  '数据集ID: {value}': 'Dataset ID: {value}',
  数据集名称: 'Dataset Name',
  数量: 'Quantity',
  文档列表: 'Document List',
  文档标题: 'Document Title',
  文档编码: 'Document Code',
  新增: 'Add',
  新增OMS订单: 'Add OMS Order',
  新增图表: 'Add Chart',
  新增报价单: 'Add Quotation',
  新增汇率: 'Add Exchange Rate',
  新增用户: 'Add User',
  新增结算: 'Add Settlement',
  新增薪资记录: 'Add Payroll Record',
  新增薪资项: 'Add Salary Item',
  新增角色: 'Add Role',
  新增记账凭证: 'Add Voucher',
  新增请假: 'Add Leave',
  新增账户: 'Add Account',
  新增跟进: 'Add Follow-up',
  新增跟进记录: 'Add Follow-up',
  新增配置: 'Add Setting',
  新增采购申请: 'Add Purchase Request',
  '新增采购结算（付款核销）': 'Add Purchase Settlement (payment write-off)',
  新增采购订单: 'Add Purchase Order',
  新增银行账户: 'Add Bank Account',
  '新增销售结算（收款核销）': 'Add Sales Settlement (receipt write-off)',
  新增销售订单: 'Add Sales Order',
  新增阶段: 'Add Stage',
  '新密码 (6-32位)': 'New Password (6-32 chars)',
  '新密码（留空不修改）': 'New password (leave blank to keep unchanged)',
  新建指标: 'New Metric',
  方向: 'Direction',
  方式: 'Method',
  方法: 'Method',
  无效的ID: 'Invalid ID',
  无权限访问: 'Access denied',
  日期: 'Date',
  旧密码: 'Old Password',
  时间: 'Time',
  '明细-借方金额': 'Item Debit',
  '明细-摘要': 'Item Summary',
  '明细-科目ID': 'Item Account ID',
  '明细-贷方金额': 'Item Credit',
  明细分类账: 'Subsidiary Ledgers',
  是: 'Yes',
  '是否计税(0/1)': 'Taxable (0/1)',
  暂无可选用户: 'No assignable users',
  '暂无图表，点击「新增图表」创建': 'No charts yet; click "Add Chart" to create one',
  暂无数据: 'No data',
  暂无明细数据: 'No detail data',
  暂无角色: 'No roles yet',
  '更新失败: {error}': 'Update failed: {error}',
  更新成功: 'Updated successfully',
  最低: 'Lowest',
  最低库存: 'Min Stock',
  最后登录: 'Last Login',
  最近操作: 'Recent Operations',
  最高: 'Highest',
  最高库存: 'Max Stock',
  月: 'Month',
  月份: 'Month',
  服务器内部错误: 'Internal server error',
  服务工单: 'Service Ticket',
  期初借方: 'Opening Debit',
  期初现金: 'Beginning Cash',
  期初贷方: 'Opening Credit',
  期末借方: 'Closing Debit',
  期末现金: 'Ending Cash',
  期末结转: 'Period-End Closing',
  期末贷方: 'Closing Credit',
  期间: 'Period',
  '期间 YYYY-MM': 'Period YYYY-MM',
  '期间 YYYY-MM(可选)': 'Period YYYY-MM (optional)',
  期间值: 'Period Value',
  期间类型: 'Period Type',
  未分配: 'Unassigned',
  未发放: 'Unpaid',
  未填写则留空: 'Leave blank to keep unchanged',
  未授权访问: 'Unauthorized',
  未核销: 'Unsettled',
  未知: 'Unknown',
  未结算: 'Unsettled',
  本位币: 'Base Currency',
  本年利润: 'Profit for the Year',
  本期借方: 'Current Debit',
  本期贷方: 'Current Credit',
  权限: 'Permission',
  '权限分配:': 'Permissions:',
  条码: 'Barcode',
  '来料检验(IQC)': 'Incoming Inspection (IQC)',
  来源: 'Source',
  来源类型: 'Source Type',
  来源记录ID: 'Source ID',
  查看单据: 'View Document',
  查询: 'Query',
  查询SQL: 'Query SQL',
  '查询中...': 'Querying...',
  '查询成功，暂无数据行': 'Query succeeded, no result rows',
  标准名称: 'Standard Name',
  标准编码: 'Standard Code',
  标签: 'Tags',
  标记全部已读: 'Mark All as Read',
  标识: 'Slug',
  '标识: {slug} | 用户数: {count} | {desc}': 'Slug: {slug} | Users: {count} | {desc}',
  标题: 'Title',
  核销金额: 'Write-off Amount',
  根本原因: 'Root Cause',
  '格式 YYYY-MM-DD': 'Format YYYY-MM-DD',
  '格式 YYYY-MM-DD HH:mm:ss': 'Format YYYY-MM-DD HH:mm:ss',
  '格式 YYYY-MM-DD HH:mm:ss，可留空': 'Format YYYY-MM-DD HH:mm:ss, optional',
  '检验/合格/不合格': 'Inspected/Passed/Rejected',
  检验单号: 'Inspection No.',
  检验员: 'Inspector',
  检验数量: 'Inspected Qty',
  检验标准: 'Inspection Standards',
  检验标准ID: 'Inspection Standard ID',
  检验类型: 'Inspection Type',
  检验结果: 'Inspection Result',
  检验规格: 'Inspection Spec',
  模块: 'Module',
  模板: 'Template',
  模板ID: 'Template ID',
  正常: 'Normal',
  每公斤单价: 'Per-kg Rate',
  每周: 'Weekly',
  每天: 'Daily',
  每月: 'Monthly',
  汇兑损益: 'Exchange Gain/Loss',
  汇率: 'Exchange Rate',
  汇率管理: 'Exchange Rates',
  没有需要保存的修改: 'No changes to save',
  波次拣货: 'Pick by Wave',
  波次管理: 'Wave',
  派送中: 'Out for Delivery',
  流动比率: 'Current Ratio',
  流动负债: 'Current Liabilities',
  流动资产: 'Current Assets',
  流转: 'Transition',
  浮动: 'Variable',
  渠道: 'Channel',
  渠道店铺名称: 'Channel Store Name',
  渠道管理: 'Channels',
  渠道订单号: 'Channel Order No.',
  '热销商品 TOP 5': 'Top 5 Products',
  '燃油附加费(%)': 'Fuel Surcharge (%)',
  版本: 'Version',
  物流轨迹: 'Tracking',
  状态: 'Status',
  状态流转: 'Status Transition',
  状态流转成功: 'Status transitioned',
  现金: 'Cash',
  现金日记账: 'Cash Journals',
  现金流量表: 'Cash Flow Statement',
  生产制造: 'Manufacturing',
  生产工单: 'Production Order',
  生产工单ID: 'Work Order ID',
  生成报表: 'Generate Report',
  生成时间: 'Generated At',
  '生成时间: {value}': 'Generated at: {value}',
  生效日期: 'Effective Date',
  用户: 'User',
  用户ID: 'User ID',
  用户创建成功: 'User created',
  用户名: 'Username',
  用户名或密码错误: 'Invalid username or password',
  用户更新成功: 'User updated',
  用户状态分布: 'User Status Distribution',
  用户管理: 'Users',
  申请人ID: 'Requester ID',
  申请单号: 'Request No.',
  申请部门: 'Department',
  电话: 'Phone',
  留空为0: 'Leave blank for 0',
  '留空自动生成 CT+时间戳': 'Leave blank to auto-generate CT+timestamp',
  '留空自动生成 PA+时间戳': 'Leave blank to auto-generate PA+timestamp',
  '留空自动生成 PAY+时间戳': 'Leave blank to auto-generate PAY+timestamp',
  '留空自动生成 PO+时间戳': 'Leave blank to auto-generate PO+timestamp',
  '留空自动生成 PRN+时间戳': 'Auto PRN+timestamp when blank',
  '留空自动生成 QT+时间戳': 'Leave blank to auto-generate QT+timestamp',
  '留空自动生成 RCV+时间戳': 'Leave blank to auto-generate RCV+timestamp',
  '留空自动生成 SO+时间戳': 'Leave blank to auto-generate SO+timestamp',
  '留空自动生成 SRN+时间戳': 'Auto SRN+timestamp when blank',
  '留空自动生成 VCH+时间戳': 'Leave blank to auto-generate VCH+timestamp',
  '留空默认 合同-报价单号': 'Leave blank to default to Contract-quotation No.',
  病假: 'Sick Leave',
  '登 录': 'Log In',
  登出成功: 'Logged out successfully',
  登录失败: 'Login failed',
  登录成功: 'Login successful',
  '登录状态已失效，请重新登录': 'Session expired, please log in again',
  盘点: 'Stocktaking',
  盘点任务: 'Stocktakes',
  目标币ID: 'Target Currency ID',
  目标状态: 'Target Status',
  目的区域: 'Destination Zone',
  目的国家: 'Destination Country',
  看板名称: 'Dashboard Name',
  真实姓名: 'Real Name',
  确定: 'OK',
  '确定执行「{action}」？': 'Confirm “{action}”?',
  '确定要删除「{name}」吗？': 'Are you sure you want to delete "{name}"?',
  '确定要删除图表「{name}」吗？': 'Are you sure you want to delete chart "{name}"?',
  '确定要删除用户「{name}」吗？': 'Are you sure you want to delete user "{name}"?',
  '确定要删除角色「{name}」吗？': 'Are you sure you want to delete role "{name}"?',
  '确定要删除该汇率记录吗？': 'Are you sure you want to delete this exchange rate?',
  '确定要删除该薪资记录吗？': 'Are you sure you want to delete this payroll record?',
  '确定要删除该请假记录吗？': 'Are you sure you want to delete this leave record?',
  '确定要删除该采购结算记录吗？':
    'Are you sure you want to delete this purchase settlement record?',
  '确定要删除该销售结算记录吗？': 'Are you sure you want to delete this sales settlement record?',
  '确定要删除选中的 {count} 个用户吗？': 'Delete the {count} selected users?',
  '确定要删除配置「{key}」吗？': 'Are you sure you want to delete setting "{key}"?',
  '确定要删除银行账户「{name}」吗？': 'Are you sure you want to delete bank account "{name}"?',
  '确定要将工单「{code}」流转为「{status}」吗？': 'Move work order "{code}" to "{status}"?',
  '确定要撤回该审批吗？': 'Withdraw this approval request?',
  '确定要退出登录吗？': 'Are you sure you want to log out?',
  确定退出: 'Confirm',
  确认: 'Confirm',
  确认删除: 'Confirm delete',
  确认发放: 'Confirm Payment',
  '确认将「{period}」的薪资标记为已发放吗？': 'Mark salary for "{period}" as paid?',
  '确认批准该请假申请吗？': 'Approve this leave request?',
  确认批量删除: 'Confirm Batch Delete',
  确认收货: 'Confirm Receipt',
  确认新密码: 'Confirm New Password',
  确认解决: 'Confirm Resolution',
  确认计提: 'Confirm',
  确认退出: 'Confirm Log Out',
  '确认驳回该请假申请吗？': 'Reject this leave request?',
  '社保(个人)': 'Social Insurance (employee)',
  禁用: 'Disable',
  科目ID: 'Account ID',
  科目余额: 'Account Balances',
  税务管理: 'Taxes',
  税率: 'Tax Rate',
  '第 {page} 页 / 共 {pages} 页 ({total} 条)': 'Page {page} of {pages} ({total} records)',
  等级: 'Level',
  筹资活动净额: 'Net Financing Cash Flow',
  筹资活动流入: 'Financing Inflows',
  筹资活动流出: 'Financing Outflows',
  管理后台: 'Admin Console',
  管理员: 'Administrator',
  类型: 'Type',
  '类型(0=固定 1=浮动)': 'Type (0=fixed 1=variable)',
  '类型: {type}': 'Type: {type}',
  系统: 'System',
  系统管理: 'System',
  系统配置: 'System Config',
  纠正措施: 'Corrective Action',
  经营: 'Business',
  经营活动净额: 'Net Operating Cash Flow',
  经营活动流入: 'Operating Inflows',
  经营活动流出: 'Operating Outflows',
  结束日期: 'End Date',
  结束时间: 'End Time',
  结果: 'Result',
  '结果: {value}': 'Result: {value}',
  '结果行数: {value}': 'Result rows: {value}',
  结算: 'Settle',
  结算时间: 'Settled At',
  结算状态: 'Settlement Status',
  结转状态: 'Closing Status',
  绩效工资: 'Performance Pay',
};
