/*
 * Copyright (c) 2026 erik <erik@erik.xyz> — https://erik.xyz
 */

// 词典切片 4/4，由 ./index 合并导出；查找词条请 grep 整个目录。

export const zhEnPart4: Record<string, string> = {
  委外订单: 'Subcontract Order',
  字符串: 'String',
  季度: 'Quarterly',
  学分: 'Credits',
  完工: 'Complete',
  完工数: 'Completed Qty',
  实发: 'Net Pay',
  审批已发起: 'Approval started',
  审核: 'Approve',
  客户名称: 'Customer Name',
  客户管理: 'Customer Management',
  密码已修改: 'Password changed',
  密钥已重置: 'Secret reset',
  小计: 'Subtotal',
  工作站名称: 'Workstation Name',
  工作站编码: 'Workstation Code',
  工单分类: 'Ticket Category',
  工单号: 'Ticket No.',
  工单已完工: 'Work order completed',
  工单已开工: 'Work order started',
  工单已解决: 'Ticket resolved',
  工单标题: 'Ticket Title',
  工序: 'Operation',
  工序名称: 'Operation Name',
  工序序号: 'Sequence',
  工序报工: 'Work Report',
  工时数: 'Hours',
  工资条: 'Payslip',
  已作废: 'Voided',
  已入职: 'Onboarded',
  '已发 Offer': 'Offer Sent',
  已发出: 'Sent',
  已回复: 'Replied',
  已完成库存分配: 'Stock allocated',
  已归档: 'Archived',
  已接受: 'Accepted',
  已提交: 'Submitted',
  已撤销: 'Withdrawn',
  已标记为已读: 'Marked as read',
  已派单: 'Assigned',
  已淘汰: 'Rejected',
  已生成合同: 'Contract generated',
  已生成履约单: 'Fulfillment created',
  已生成采购订单: 'Purchase order created',
  已生效: 'Effective',
  已用: 'Used',
  已结: 'Settled',
  已认领: 'Claimed',
  已读: 'Read',
  已释放回公海: 'Released back to pool',
  币种名称: 'Currency Name',
  币种管理: 'Currency Management',
  币种编码: 'Currency Code',
  布尔: 'Boolean',
  库位名称: 'Location Name',
  库位编码: 'Location Code',
  库区名称: 'Zone Name',
  库区编码: 'Zone Code',
  库存分配: 'Allocate Stock',
  库存管理: 'Inventory Management',
  应发: 'Gross Pay',
  应用名称: 'App Name',
  应聘职位: 'Applied Job',
  开工: 'Start',
  开户行: 'Bank',
  开放应用: 'OpenAPI Apps',
  开票: 'Issue Invoice',
  开票日期: 'Invoice Date',
  归档: 'Archive',
  归集日期: 'Posting Date',
  当前密码: 'Current Password',
  '录用 Offer': 'Offer Letter',
  往来方: 'Counterparty',
  待定: 'Pending',
  待开通: 'Pending Provision',
  总账: 'General Ledger',
  成本: 'Cost',
  成本归集: 'Cost Entry',
  成本类别: 'Cost Category',
  所属仓库: 'Warehouse',
  所属应用: 'App',
  所属模块: 'Module',
  所属看板: 'Dashboard',
  所属部门: 'Department',
  所属项目: 'Project',
  手机: 'Phone',
  打包完成: 'Pack Done',
  打包已完成: 'Packing completed',
  打卡成功: 'Punched successfully',
  托收: 'Collect',
  托收账户: 'Collection Account',
  执行报表: 'Run Report',
  批次效期预警: 'Batch Expiry Alerts',
  承兑人: 'Acceptor',
  承兑汇票: 'Banker Acceptance',
  承运商名称: 'Carrier Name',
  投递测试完成: 'Test delivery done',
  折扣: 'Discount',
  折旧已计提: 'Depreciation posted',
  折旧方法: 'Depreciation Method',
  报工员工: 'Reporting Employee',
  报工已审核: 'Work report approved',
  报工数量: 'Reported Qty',
  报工日期: 'Report Date',
  报表已执行: 'Report executed',
  报表模板: 'Report Template',
  报销金额: 'Reimbursement Amount',
  抵扣: 'Deduct',
  拒付: 'Reject',
  招聘人数: 'Headcount',
  招聘候选人: 'Candidates',
  招聘管理: 'Recruitment',
  招聘职位: 'Job Postings',
  招聘部门: 'Hiring Department',
  招聘面试: 'Interviews',
  拣货已确认: 'Pick confirmed',
  拣货确认: 'Confirm Pick',
  按钮: 'Button',
  提交数: 'Submitted Qty',
  搜索通知内容: 'Search notification content',
  搜索配置键: 'Search config key',
  撤销: 'Withdraw',
  操作人: 'Operator',
  支付: 'Pay',
  收料仓库: 'Receiving Warehouse',
  收料单号: 'Receipt Slip No.',
  收料单已审核: 'Receipt slip approved',
  收料数量: 'Received Qty',
  收料日期: 'Receive Date',
  收款人: 'Payee',
  收款方式: 'Receipt Method',
  收款日期: 'Receipt Date',
  收款账户: 'Receipt Account',
  收款金额: 'Receipt Amount',
  收票: 'Received',
  收货单: 'Receiving Note',
  收货完成: 'Receiving Done',
  收货已完成: 'Receiving completed',
  收货日期: 'Receipt Date',
  数组: 'Array',
  整数: 'Integer',
  文档内容: 'Content',
  文档分类: 'Category',
  文档管理: 'Document Management',
  新增成功: 'Created',
  新密码: 'New Password',
  '新密码长度需为 6-32 位': 'New password must be 6-32 characters',
  新简历: 'New Resume',
  是否启用: 'Enabled',
  更新时间: 'Updated At',
  最大库存阈值: 'Max Stock Threshold',
  最小库存阈值: 'Min Stock Threshold',
  月度: 'Monthly',
  服务名称: 'Service Name',
  期望薪资: 'Expected Salary',
  期间已结账: 'Period closed',
  未开始: 'Not Started',
  未结: 'Unsettled',
  未设置: 'Not Set',
  未读: 'Unread',
  权限名: 'Permission Name',
  权限管理: 'Permission Management',
  材料: 'Material',
  条: 'records',
  来料检验: 'IQC',
  '来料检验 IQC': 'Incoming Inspection IQC',
  来源币种: 'From Currency',
  来源渠道: 'Source',
  标记已读: 'Mark Read',
  模板名称: 'Template Name',
  模板已启用: 'Template enabled',
  模板编码: 'Template Code',
  残值: 'Salvage Value',
  比价: 'Compare',
  汇率值: 'Rate',
  波次已释放: 'Wave released',
  波次释放: 'Release Wave',
  活动名称: 'Campaign Name',
  派单: 'Assign',
  测试投递: 'Test Delivery',
  渠道名称: 'Channel Name',
  漏斗阶段名称: 'Stage Name',
  点检任务: 'Inspection Tasks',
  点检日期: 'Inspection Date',
  父任务: 'Parent Task',
  '父级 ID': 'Parent ID',
  状态已切换: 'Status toggled',
  状态已更新: 'Status updated',
  生产领料: 'Material Issue',
  用户数: 'Users',
  申请人: 'Applicant',
  界面语言: 'Language',
  '登录已过期，请重新登录': 'Session expired, please log in again',
  盘点任务名称: 'Stocktake Name',
  盘点单号: 'Stocktake No.',
  目录: 'Directory',
  目标币种: 'To Currency',
  目标类型: 'Target Type',
  直线法: 'Straight Line',
  看板布局: 'Dashboard Layout',
  确认操作: 'Confirm Action',
  社保规则: 'Social Security Rules',
  票据号: 'Bill No.',
  票面金额: 'Face Amount',
  租户列表: 'Tenants',
  租户已停用: 'Tenant suspended',
  租户已启用: 'Tenant resumed',
  租户管理: 'Tenant Management',
  税号: 'Tax No.',
  税率管理: 'Tax Rates',
  税额: 'Tax Amount',
  第: 'Page',
  签订日期: 'Sign Date',
  算薪: 'Calculate Payroll',
  算薪完成: 'Payroll calculated',
  纳税记录: 'Tax Records',
  线上: 'Online',
  组件名称: 'Widget Name',
  组件类型: 'Widget Type',
  结账: 'Close Period',
  绩效模板: 'Perf Templates',
  绩效考核: 'Performance Review',
  维修工单号: 'Repair Order No.',
  缴费基数上限: 'Base Ceiling',
  缴费基数下限: 'Base Floor',
  考核批次已启动: 'Review started',
  考核批次已归档: 'Review archived',
  考核计划: 'Review Plans',
  考核评分: 'Review Scores',
  '耗时(ms)': 'Elapsed (ms)',
  职位名称: 'Job Title',
  职位已关闭: 'Job closed',
  职位已发布: 'Job published',
  职位编码: 'Position Code',
  联系人名称: 'Contact Name',
  背书: 'Endorse',
  自定义字段: 'Custom Fields',
  自定义报表: 'Custom Reports',
  获取面单: 'Get Label',
  菜单: 'Menu',
  规则名称: 'Rule Name',
  角色名: 'Role Name',
  角色权限: 'Roles',
  计划年度: 'Plan Year',
  计划数: 'Planned Qty',
  计划数量: 'Planned Quantity',
  计划日期: 'Plan Date',
  计划月份: 'Plan Month',
  计划编码: 'Plan Code',
  订单号: 'Order No.',
  订单履约: 'Order Fulfillment',
  订单已取消: 'Order cancelled',
  认领: 'Claim',
  讲师: 'Lecturer',
  设备: 'Equipment',
  设备管理: 'Equipment Management',
  询价单: 'RFQ',
  询价单已关闭: 'RFQ closed',
  请输入当前密码: 'Enter current password',
  请输入登录密码确认操作: 'Enter login password to confirm',
  '课时(小时)': 'Duration (hours)',
  课程标题: 'Course Title',
  课程类型: 'Course Type',
  调出仓库: 'From Warehouse',
  调拨单号: 'Transfer No.',
  调拨日期: 'Transfer Date',
  财务管理: 'Finance Management',
  账套期间: 'Ledger Periods',
  账户编码: 'Account Code',
  质量管理: 'Quality Management',
  购置日期: 'Purchase Date',
  购置金额: 'Purchase Amount',
  贴现: 'Discount',
  费用科目: 'Expense Account',
  费用类型: 'Expense Type',
  资产名称: 'Asset Name',
  资产类别: 'Asset Category',
  资产编号: 'Asset No.',
  资产编码: 'Asset Code',
  资料已保存: 'Profile saved',
  赢单: 'Won',
  跟进中: 'Following Up',
  跟进人: 'Follower',
  轮次: 'Round',
  输单: 'Lost',
  过程检验: 'IPQC',
  '过程检验 IPQC': 'Process Inspection IPQC',
  运单已发货: 'Shipment shipped',
  运算完成: 'MRP run complete',
  运费已支付: 'Freight paid',
  运费已确认: 'Freight confirmed',
  运输服务: 'Transport Services',
  进行中: 'In Progress',
  进项发票池: 'Input Invoice Pool',
  '退换货 RMA': 'Return RMA',
  退货仓库: 'Return Warehouse',
  退货入库: 'Receive Return',
  退货金额: 'Return Amount',
  部门名称: 'Department Name',
  部门编码: 'Department Code',
  配置键: 'Key',
  采购管理: 'Purchase Management',
  采购销售: 'Procurement & Sales',
  释放: 'Release',
  重置密钥: 'Reset Secret',
  销售管理: 'Sales Management',
  集团财务: 'Group Finance',
  面单已生成: 'Label generated',
  面试中: 'Interviewing',
  面试日期: 'Interview Date',
  页: 'of',
  项目名称: 'Project Name',
  项目成本: 'Project Cost',
  项目管理: 'Project Management',
  项目编号: 'Project Code',
  '预到货 ASN': 'ASN',
  预算名称: 'Budget Name',
  预算对比: 'Compare Budget',
  预算年度: 'Budget Year',
  预算额: 'Budget Amount',
  预计金额: 'Expected Amount',
  领料单已审核: 'Issue approved',
  领料日期: 'Issue Date',
  验真: 'Verify',
  '验证失败，请重试': 'Verification failed, please retry',
  搜索菜单: 'Search menus',
  关闭标签: 'Close tab',
  关闭其他标签: 'Close other tabs',
  关闭全部标签: 'Close all tabs',
  关闭其他: 'Close Others',
  关闭全部: 'Close All',
  页面不存在: 'Page Not Found',
  当前路由未注册: 'Route not registered',
  人机验证: 'Captcha',
  点击文字验证: 'Click the characters',
  '验证码加载中…': 'Loading captcha...',
  暂无趋势数据: 'No trend data yet',
  账户状态分布: 'Account Status',
  最近操作日志: 'Recent Logs',
  暂无日志: 'No logs',
  '近 30 天趋势': 'Last 30 Days Trend',
  '已完成人机验证，点击「登 录」继续': 'Captcha verified. Click Log In to continue',
  登录需先完成人机验证: 'Complete the captcha first',
  全部已读: 'Mark All Read',
  请选择: 'Select...',
  '条/页': 'records/page',
  较昨日: 'vs yesterday',
  按顺序点击: 'Click in order',
  '请填写「{label}」': 'Please fill in {label}',
  '新增{name}': 'New {name}',
  '编辑{name}': 'Edit {name}',
  '确定执行「{act}」吗？': 'Execute {act}?',
  '确定删除「{name}」？该操作不可恢复。': 'Delete {name}? This cannot be undone.',
  '请求失败（{code}）': 'Request failed ({code})',
  '下载失败（{code}）': 'Download failed ({code})',
  'Open ERP · Web 控制台': 'Open ERP · Web Console',
  业务模块: 'Modules',
  中英切换: 'Chinese / English',
  '第 {count} 个字位置不准，请再点一次': 'Click #{count} again - the point missed the target',
  '仍未通过，请按顺序重新点击': 'Still not matched - click all characters in order again',
};
