/*
 * Copyright (c) 2026 erik <erik@erik.xyz> — https://erik.xyz
 */

import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';
import { NzIconModule } from 'ng-zorro-antd/icon';
import {
  AccountBookOutline,
  AlertOutline,
  ApartmentOutline,
  ApiOutline,
  AppstoreOutline,
  AuditOutline,
  BarChartOutline,
  BellOutline,
  BlockOutline,
  BranchesOutline,
  BugOutline,
  BuildOutline,
  CalendarOutline,
  CheckOutline,
  ClockCircleOutline,
  CloseOutline,
  ClusterOutline,
  CodepenOutline,
  ContainerOutline,
  CreditCardOutline,
  DashboardOutline,
  DatabaseOutline,
  DeleteOutline,
  DeploymentUnitOutline,
  DesktopOutline,
  DollarOutline,
  DownOutline,
  DownloadOutline,
  DropboxOutline,
  EditOutline,
  ExceptionOutline,
  ExperimentOutline,
  ExportOutline,
  EyeOutline,
  FileTextOutline,
  FilterOutline,
  FolderOutline,
  FundOutline,
  GlobalOutline,
  GoldOutline,
  GroupOutline,
  HomeOutline,
  ImportOutline,
  InboxOutline,
  InfoCircleOutline,
  LineChartOutline,
  LinkOutline,
  LockOutline,
  LogoutOutline,
  MenuOutline,
  MinusCircleOutline,
  MonitorOutline,
  PartitionOutline,
  PieChartOutline,
  PlusCircleOutline,
  PlusOutline,
  ProfileOutline,
  ProjectOutline,
  QuestionCircleOutline,
  RadarChartOutline,
  ReloadOutline,
  RightOutline,
  RocketOutline,
  SafetyCertificateOutline,
  SafetyOutline,
  SearchOutline,
  SendOutline,
  SettingOutline,
  ShopOutline,
  ShoppingCartOutline,
  SnippetsOutline,
  SolutionOutline,
  StarOutline,
  SwapOutline,
  SyncOutline,
  TableOutline,
  TeamOutline,
  ThunderboltOutline,
  ToolOutline,
  TruckOutline,
  UnorderedListOutline,
  UploadOutline,
  UserAddOutline,
  UserOutline,
  WalletOutline,
} from '@ant-design/icons-angular/icons';
import type { IconDefinition } from '@ant-design/icons-angular';

/**
 * 图标名 → antd 图标定义（与 React ui/Icon.tsx 同名同义）。
 *
 * 键值是「裸名」：zorro 查表时会给无主题后缀的名字补默认主题 outline，
 * 补法是把 outline 写成 -o 后缀（withSuffix(name,'outline') === `${name}-o`），
 * 所以 <nz-icon nzType="user"> 命中的是注册表里的 user-o。
 * 因此映射值必须是 *Outline 定义，且 app.config 里注册的就是这里的全部值。
 *
 * 替换说明（icons-angular 22.1 没有的名字）：layers→ApartmentOutline、
 * box→DropboxOutline、factory→BuildOutline；语义相近，调用方无感。
 */
export const ICON_MAP: Record<string, IconDefinition> = {
  accountBook: AccountBookOutline,
  activity: ThunderboltOutline,
  alert: AlertOutline,
  api: ApiOutline,
  apartment: ApartmentOutline,
  audit: AuditOutline,
  bell: BellOutline,
  block: BlockOutline,
  box: DropboxOutline,
  branches: BranchesOutline,
  bug: BugOutline,
  calendar: CalendarOutline,
  cart: ShoppingCartOutline,
  chart: BarChartOutline,
  check: CheckOutline,
  chevDown: DownOutline,
  chevRight: RightOutline,
  clipboard: SnippetsOutline,
  clock: ClockCircleOutline,
  close: CloseOutline,
  cluster: ClusterOutline,
  codepen: CodepenOutline,
  container: ContainerOutline,
  creditCard: CreditCardOutline,
  database: DatabaseOutline,
  delete: DeleteOutline,
  deployment: DeploymentUnitOutline,
  desktop: DesktopOutline,
  download: DownloadOutline,
  edit: EditOutline,
  exception: ExceptionOutline,
  experiment: ExperimentOutline,
  export: ExportOutline,
  eye: EyeOutline,
  factory: BuildOutline,
  file: FileTextOutline,
  filter: FilterOutline,
  folder: FolderOutline,
  fund: FundOutline,
  gauge: DashboardOutline,
  global: GlobalOutline,
  gold: GoldOutline,
  grid: AppstoreOutline,
  group: GroupOutline,
  home: HomeOutline,
  import: ImportOutline,
  inbox: InboxOutline,
  info: InfoCircleOutline,
  layers: ApartmentOutline,
  line: LineChartOutline,
  link: LinkOutline,
  list: UnorderedListOutline,
  lock: LockOutline,
  logout: LogoutOutline,
  menu: MenuOutline,
  minus: MinusCircleOutline,
  money: DollarOutline,
  monitor: MonitorOutline,
  partition: PartitionOutline,
  pie: PieChartOutline,
  plus: PlusOutline,
  plusCircle: PlusCircleOutline,
  profile: ProfileOutline,
  project: ProjectOutline,
  question: QuestionCircleOutline,
  radar: RadarChartOutline,
  refresh: ReloadOutline,
  reload: ReloadOutline,
  rocket: RocketOutline,
  safety: SafetyOutline,
  search: SearchOutline,
  send: SendOutline,
  settings: SettingOutline,
  shield: SafetyCertificateOutline,
  shop: ShopOutline,
  solution: SolutionOutline,
  star: StarOutline,
  swap: SwapOutline,
  sync: SyncOutline,
  table: TableOutline,
  tool: ToolOutline,
  trash: DeleteOutline,
  truck: TruckOutline,
  upload: UploadOutline,
  user: UserOutline,
  userAdd: UserAddOutline,
  users: TeamOutline,
  wallet: WalletOutline,
};

/** 未知名兜底：绝不渲染空图标（菜单配置新增图标名时不至于开天窗） */
export const FALLBACK_ICON: IconDefinition = AppstoreOutline;

/** 注册进 NZ_ICONS 的全量定义（去重：一个定义可挂多个名字） */
export const APP_ICONS: IconDefinition[] = [...new Set(Object.values(ICON_MAP))];

/**
 * 图标渲染组件：模板只写 <app-icon name="user"/>。
 * 尺寸靠 CSS 的 font-size 继承（antd 图标是 1em 的 svg），故不设 size 入参。
 */
@Component({
  selector: 'app-icon',
  standalone: true,
  imports: [NzIconModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<nz-icon [nzType]="type()" />`,
  styles: [':host{display:inline-flex;align-items:center;justify-content:center;line-height:1}'],
})
export class IconComponent {
  readonly name = input('');
  readonly type = computed(() => (ICON_MAP[this.name()] ?? FALLBACK_ICON).name);
}
