/*
 * Copyright (c) 2026 erik <erik@erik.xyz> — https://erik.xyz
 */

/**
 * 中文原文 → German 词典（de）。由 scripts/gen-fe-locales.mjs 生成，**请勿手工编辑**。
 * 缺词条时回退中文原文；键集须与 core/zh-en 完全一致。
 */
export const zhDe: Record<string, string> = {
  ':attribute 不存在': 'Das :attribute existiert nicht',
  ':attribute 不能为空': 'Das Feld :attribute ist erforderlich',
  ':attribute 不能大于 :max': 'Das :attribute darf :max nicht überschreiten',
  ':attribute 不能小于 :min': 'Das :attribute muss mindestens :min betragen',
  ':attribute 值无效': 'Der Wert von :attribute ist ungültig',
  ':attribute 已存在': 'Das :attribute existiert bereits',
  ':attribute 必须是字符串': 'Das :attribute muss eine Zeichenkette sein',
  ':attribute 必须是数字': 'Das :attribute muss eine Zahl sein',
  ':attribute 必须是整数': 'Das :attribute muss eine ganze Zahl sein',
  ':attribute 格式不正确': 'Das Format von :attribute ist ungültig',
  'BOM管理': 'Stücklistenverwaltung',
  'JSON 对象，含 current_assets、current_liabilities、total_liabilities、total_assets 字段，值为数字': 'JSON-Objekt mit numerischen Werten für current_assets, current_liabilities, total_liabilities und total_assets',
  'JSON 对象，含 net_profit、revenue 字段，值为数字': 'JSON-Objekt mit numerischen Werten für net_profit und revenue',
  'MRP计划': 'MRP-Planung',
  'OMS 订单': 'OMS-Bestellungen',
  'OMS订单': 'OMS-Bestellung',
  'Token已过期': 'Token abgelaufen',
  'Token无效': 'Ungültiges Token',
  'X坐标': 'X-Position',
  'YYYY-MM-DD，如 2026-09-05': 'JJJJ-MM-TT, z. B. 2026-09-05',
  'Y坐标': 'Y-Position',
  'erp开放管理后台': 'Open ERP Admin',
  'erp管理后台': 'Open ERP Admin',
  '{field} 不是合法 JSON': '{field} ist kein gültiges JSON',
  '{field} 必须为 JSON 对象': '{field} muss ein JSON-Objekt sein',
  '{field} 必须为 JSON 数组': '{field} muss ein JSON-Array sein',
  '{page} / {pages} ({total}条)': '{page} / {pages} ({total})',
  '一个平台，管好全部业务': 'Eine Plattform für Ihr gesamtes Unternehmen',
  '上传成功': 'Upload erfolgreich',
  '上架管理': 'Einlagerung',
  '上次保养日期': 'Letztes Wartungsdatum',
  '下单时间': 'Bestelldatum',
  '下次保养日期': 'Nächstes Wartungsdatum',
  '下次日期': 'Nächstes Datum',
  '不合格品': 'Nicht konforme Produkte',
  '不合格数量': 'Abgelehnte Menge',
  '不合格编号': 'Fehlernr.',
  '两次密码不一致': 'Passwörter stimmen nicht überein',
  '严重程度': 'Schweregrad',
  '个人中心': 'Profil',
  '个人信息更新成功': 'Profil erfolgreich aktualisiert',
  '个人所得税': 'Einkommensteuer (natürliche Personen)',
  '个税': 'Einkommensteuer',
  '主题': 'Betreff',
  '买家备注': 'Käufernotiz',
  '事假': 'Sonderurlaub',
  '产假': 'Mutterschutz',
  '人力资源': 'Personal',
  '从供应商列表页获取数字ID': 'Numerische ID aus der Lieferantenliste',
  '从员工列表页获取数字ID': 'Numerische ID aus der Mitarbeiterliste',
  '从客户列表页获取数字ID': 'Numerische ID aus der Kundenliste',
  '从科目列表获取数字ID，填了则按明细创建': 'Numerische ID aus der Kontenliste; wenn gesetzt, wird der Beleg mit Positionen erstellt',
  '从销售订单列表页获取数字ID': 'Numerische ID aus der Auftragsliste',
  '仓储管理': 'Lagerverwaltung',
  '仓库': 'Lager',
  '仓库信息': 'Lagerinfo',
  '付款单': 'Zahlung',
  '付款单ID': 'Zahlungs-ID',
  '付款单号': 'Zahlungsnr.',
  '付款时间': 'Bezahlt am',
  '付款管理': 'Zahlungen',
  '仪表盘': 'Dashboard',
  '价格': 'Preis',
  '任务': 'Aufgabe',
  '任务管理': 'Aufgaben',
  '企业所得税': 'Körperschaftsteuer',
  '优先级': 'Priorität',
  '优惠金额': 'Rabattbetrag',
  '会计科目': 'Kontenplan',
  '低库存预警': 'Niedrigbestandswarnungen',
  '余额': 'Saldo',
  '供应商': 'Lieferant',
  '供应商ID': 'Lieferanten-ID',
  '供应商信息': 'Lieferanteninfo',
  '保修到期': 'Garantieablauf',
  '保养计划': 'Wartungspläne',
  '保养频率': 'Wartungsintervall',
  '保存': 'Speichern',
  '保存失败: {error}': 'Speichern fehlgeschlagen: {error}',
  '保存成功': 'Erfolgreich gespeichert',
  '修改失败: {error}': 'Änderung fehlgeschlagen: {error}',
  '修改密码': 'Passwort ändern',
  '借': 'Soll',
  '借方合计': 'Soll gesamt',
  '值': 'Wert',
  '全部': 'Alle',
  '公海池': 'Lead-Pool',
  '公积金': 'Wohnungsfonds',
  '共 {count} 个': '{count} gesamt',
  '共 {total} 条': '{total} Datensätze',
  '关联订单': 'Zugehörige Bestellung',
  '关联销售订单ID': 'Verknüpfte Verkaufsauftrags-ID',
  '关闭': 'Schließen',
  '其他': 'Sonstiges',
  '内容': 'Inhalt',
  '冻结时间': 'Halten bis',
  '净利率': 'Nettomarge',
  '凭证ID: {id}': 'Beleg-ID: {id}',
  '凭证号': 'Beleg-Nr.',
  '凭证名称': 'Belegname',
  '凭证日期': 'Belegdatum',
  '出入库流水': 'Lagerbewegung',
  '出货检验(OQC)': 'Ausgangsprüfung (OQC)',
  '分区拣货': 'Kommissionierung nach Zone',
  '分类': 'Kategorie',
  '分组': 'Gruppe',
  '分配中': 'Zuweisung',
  '分配库存': 'Bestand zuweisen',
  '分配数量不能为空': 'Menge ist erforderlich',
  '分配数量须为正数': 'Menge muss eine positive Zahl sein',
  '创建失败: {error}': 'Erstellen fehlgeschlagen: {error}',
  '创建履约': 'Fulfillment erstellen',
  '创建成功': 'Erfolgreich erstellt',
  '创建时间': 'Erstellt am',
  '删除': 'Löschen',
  '删除({count})': 'Löschen ({count})',
  '删除失败: {error}': 'Löschen fehlgeschlagen: {error}',
  '删除成功': 'Erfolgreich gelöscht',
  '利润': 'Gewinn',
  '利润中心': 'Profitcenter',
  '利润报表': 'Gewinnbericht',
  '利润表 JSON *': 'Gewinn- und Verlustrechnung JSON *',
  '到期日': 'Fälligkeitsdatum',
  '刷新': 'Aktualisieren',
  '加班费': 'Überstundenvergütung',
  '加载中...': 'Wird geladen...',
  '加载失败': 'Laden fehlgeschlagen',
  '加载失败: {error}': 'Laden fehlgeschlagen: {error}',
  '加载权限列表失败: {error}': 'Berechtigungen konnten nicht geladen werden: {error}',
  '加载用户列表失败: {error}': 'Benutzer konnten nicht geladen werden: {error}',
  '加载角色列表失败: {error}': 'Rollen konnten nicht geladen werden: {error}',
  '包装类型': 'Pakettyp',
  '单价': 'Preis',
  '单位': 'Einheit',
  '单据ID': 'Dokument-ID',
  '单据ID必须为数字': 'Dokument-ID muss numerisch sein',
  '单据类型': 'Dokumenttyp',
  '卖家备注': 'Verkäufernotiz',
  '印花税': 'Stempelsteuer',
  '原因': 'Grund',
  '原币ID': 'Quellwährungs-ID',
  '参数(JSON)': 'Parameter (JSON)',
  '参数验证失败': 'Validierung fehlgeschlagen',
  '发放': 'Bezahlen',
  '发放失败：{error}': 'Zahlung fehlgeschlagen: {error}',
  '发货仓库ID': 'Versandlager-ID',
  '发货单ID': 'Lieferungs-ID',
  '发货单号': 'Lieferungs-Nr.',
  '取消': 'Abbrechen',
  '取消订单': 'Bestellung stornieren',
  '变更说明': 'Änderungsnotizen',
  '合同名称': 'Vertragsname',
  '合同状态流转': 'Vertragsstatus-Übergang',
  '合同管理': 'Verträge',
  '合同编号': 'Vertrags-Nr.',
  '合并中...': 'Wird zusammengeführt...',
  '合并报表': 'Konsolidierte Berichte',
  '合格数量': 'Freigegebene Menge',
  '名称': 'Name',
  '后端要求提供发货仓库': 'Ein Versandlager wird vom Server benötigt',
  '否': 'Nein',
  '启用': 'Aktivieren',
  '员工': 'Mitarbeiter',
  '员工ID': 'Mitarbeiter-ID',
  '员工档案': 'Mitarbeiter',
  '品牌': 'Marke',
  '品牌管理': 'Marken',
  '商品': 'Produkt',
  '商品ID': 'Produkt-ID',
  '商品ID须为正整数': 'Produkt-ID muss eine positive Ganzzahl sein',
  '商品ID（数字）': 'Produkt-ID (numerisch)',
  '商品信息': 'Produktinfo',
  '商品分类': 'Kategorien',
  '商品列表': 'Produktliste',
  '商品名称': 'Produktname',
  '商品明细': 'Artikel',
  '商品编码': 'Produktcode',
  '商机': 'Verkaufschance',
  '商机管理': 'Verkaufschancen',
  '商品规格': 'Produktspezifikationen',
  '固定': 'Fest',
  '固定资产': 'Anlagegut',
  '图表名称': 'Diagrammname',
  '图表管理': 'Diagramme verwalten',
  '图表管理 — {name}': 'Diagramme verwalten — {name}',
  '图表类型': 'Diagrammtyp',
  '地址': 'Adresse',
  '地点': 'Standort',
  '型号': 'Modell',
  '基本信息': 'Basisinfo',
  '基本工资': 'Grundgehalt',
  '增值税': 'Mehrwertsteuer',
  '处置方式': 'Disposition',
  '备件': 'Ersatzteile',
  '备件名称': 'Ersatzteilname',
  '备件编码': 'Ersatzteilcode',
  '备注': 'Notizen',
  '多币种/汇率': 'Mehrwährung / Wechselkurse',
  '天数': 'Tage',
  '失效日期': 'Gültig bis',
  '如 1.5': 'z. B. 1.5',
  '如 10.00': 'z. B. 10.00',
  '如 100.00': 'z. B. 100.00',
  '如 1000.00': 'z. B. 1000.00',
  '如 61000000000000001=CNY': 'z. B. 61000000000000001=CNY',
  '如 7.250000': 'z. B. 7.250000',
  '如 8000.00': 'z. B. 8000.00',
  '如 purchase_order / expense': 'z. B. purchase_order / expense',
  '如 {amount}': 'z. B. {amount}',
  '姓名': 'Mitarbeitername',
  '婚假': 'Heiratsurlaub',
  '子公司报表 JSON 数组 *': 'Tochtergesellschaftsberichte JSON-Array *',
  '存放位置': 'Standort',
  '季': 'Quartal',
  '完成': 'Abschließen',
  '定时调度': 'Zeitpläne',
  '实发工资': 'Nettolohn',
  '实时库存': 'Lagerbestand',
  '审批': 'Genehmigen',
  '审批中': 'Wird genehmigt',
  '审批工作流': 'Workflow',
  '审批意见为必填项': 'Ein Genehmigungskommentar ist erforderlich',
  '审批意见（必填）': 'Genehmigungskommentar (erforderlich)',
  '审批意见（选填）': 'Genehmigungskommentar (optional)',
  '审批流程': 'Workflow',
  '审批记录': 'Genehmigungseinträge',
  '客户': 'Kunde',
  '客户ID': 'Kunden-ID',
  '客户信息': 'Kundeninformationen',
  '客户分析': 'Kundenanalysen',
  '宽度': 'Breite',
  '密码': 'Passwort',
  '密码修改成功': 'Passwort erfolgreich geändert',
  '密码验证失败': 'Passwortüberprüfung fehlgeschlagen',
  '导入失败': 'Import fehlgeschlagen',
  '导入成功': 'Import erfolgreich',
  '导出': 'Export',
  '导出Excel': 'Excel exportieren',
  '导出PDF': 'PDF exportieren',
  '导出成功': 'Export erfolgreich',
  '展开菜单': 'Menü ausklappen',
  '履约': 'Erfüllen',
  '履约单': 'Erfüllungen',
  '履约状态': 'Erfüllungsstatus',
  '履约管理': 'Erfüllung',
  '工作日期': 'Arbeitsdatum',
  '工作流定义': 'Workflows',
  '工作站': 'Arbeitsstation',
  '工作站ID': 'Arbeitsstation-ID',
  '工单ID': 'Arbeitsauftrags-ID',
  '工单编码': 'Arbeitsauftragscode',
  '工序号': 'Sequenz',
  '工时': 'Stundenzettel',
  '工时(小时)': 'Stunden',
  '工时记录': 'Stundenzettel',
  '工艺路线': 'Arbeitsplan',
  '已付金额': 'Gezahlter Betrag',
  '已入库': 'Erhalten',
  '已关闭': 'Geschlossen',
  '已出库': 'Ausgegeben',
  '已分配': 'Zugewiesen',
  '已发放': 'Bezahlt',
  '已发货': 'Versandt',
  '已取件': 'Abgeholt',
  '已取消': 'Storniert',
  '已失效': 'Abgelaufen',
  '已完成': 'Abgeschlossen',
  '已审批': 'Genehmigt',
  '已审核': 'Geprüft',
  '已打包': 'Verpackt',
  '已打款': 'Bezahlt',
  '已批准': 'Genehmigt',
  '已报价': 'Angeboten',
  '已拒绝': 'Abgelehnt',
  '已拣货': 'Kommissioniert',
  '已撤回': 'Zurückgezogen',
  '已支付': 'Bezahlt',
  '已收货': 'Erhalten',
  '已收金额': 'Erhaltener Betrag',
  '已核销': 'Ausgeglichen',
  '已点击 {count}/{total}': 'Geklickt {count}/{total}',
  '已签收': 'Unterschrieben',
  '已终止': 'Beendet',
  '已结算': 'Abgerechnet',
  '已转订单': 'In Bestellung umgewandelt',
  '已退回': 'Retourniert',
  '已退款': 'Erstattet',
  '已送达': 'Zugestellt',
  '已通过': 'Genehmigt',
  '已驳回': 'Abgelehnt',
  '币种': 'Währung',
  '币种列表中的数字ID，如 61000000000000002=USD': 'Numerische ID aus der Währungsliste, z. B. 61000000000000002=USD',
  '布局配置': 'Layout-Konfiguration',
  '年': 'Jahr',
  '年份': 'Jahr',
  '年假': 'Jahresurlaub',
  '年度': 'Jahr',
  '序列号': 'Seriennummer',
  '库位': 'Standort',
  '库位管理': 'Standortverwaltung',
  '库区': 'Zone',
  '库区管理': 'Zonen',
  '库存': 'Bestand',
  '库存不足': 'Unzureichender Bestand',
  '库存总值': 'Bestandswert',
  '库存数量': 'Lagermenge',
  '库存流水': 'Lagerbewegungen',
  '库存调拨': 'Umlagerung',
  '库存预警': 'Bestandswarnungen',
  '应付': 'Verbindlichkeiten',
  '应付账龄': 'Verbindlichkeitenalterung',
  '应付金额': 'Verbindlichkeitsbetrag',
  '应发工资': 'Bruttolohn',
  '应收': 'Forderungen',
  '应收应付': 'Debitoren/Kreditoren',
  '应收账龄': 'Debitorenalterung',
  '应收金额': 'Forderungsbetrag',
  '应纳税所得额': 'Steuerpflichtiges Einkommen',
  '开始日期': 'Startdatum',
  '开始时间': 'Startzeit',
  '开始维修': 'Reparatur starten',
  '开户银行': 'Bankname',
  '异常': 'Ausnahme',
  '当前状态不允许此操作': 'Aktion im aktuellen Status nicht erlaubt',
  '当前状态无可流转的目标状态': 'Kein Zielstatus für den aktuellen Status verfügbar',
  '当前节点': 'Aktueller Knoten',
  '往来单位': 'Gegenpartei',
  '往来单位与所选类型不匹配，请重新选择': 'Gegenpartei entspricht nicht dem ausgewählten Typ, bitte erneut auswählen',
  '待入库': 'Wareneingang ausstehend',
  '待出库': 'Ausgabe ausstehend',
  '待发货': 'Versandbereit',
  '待处理': 'Ausstehend',
  '待审批': 'Ausstehend',
  '待审核': 'Prüfung ausstehend',
  '待打包': 'Verpackung ausstehend',
  '待拣货': 'Kommissionierung ausstehend',
  '待支付': 'Zahlung ausstehend',
  '微信': 'WeChat',
  '必填（后端校验）': 'Erforderlich (vom Server validiert)',
  '必填（后端校验），如 OM+时间戳': 'Erforderlich (vom Server validiert), z. B. OM+Zeitstempel',
  '总览': 'Übersicht',
  '总账/明细账': 'Allgemeines / Detailliertes Hauptbuch',
  '总金额': 'Gesamtbetrag',
  '恢复成功': 'Erfolgreich wiederhergestellt',
  '成功': 'Erfolg',
  '成本/利润中心': 'Kosten- / Profitcenter',
  '成本中心': 'Kostenstelle',
  '成本价': 'Stückkosten',
  '我的审批': 'Meine Genehmigungen',
  '截止重量(kg)': 'Gewicht bis (kg)',
  '所有者权益': 'Eigenkapital',
  '手机号': 'Telefon',
  '打包中': 'Verpackung',
  '打包任务': 'Verpackungsaufgabe',
  '打包单': 'Verpackungsaufgabe',
  '打包管理': 'Verpackung',
  '扣款': 'Abzüge',
  '执行': 'Ausführen',
  '执行中': 'Aktiv',
  '执行合并': 'Konsolidierung ausführen',
  '执行失败：{error}': 'Ausführung fehlgeschlagen: {error}',
  '批准': 'Genehmigen',
  '批准时间': 'Genehmigt am',
  '批准请假': 'Urlaub genehmigen',
  '批次号': 'Batch-Nr.',
  '批量删除失败: {error}': 'Batch-Löschen fehlgeschlagen: {error}',
  '批量删除完成': 'Ausgewählte Benutzer gelöscht',
  '批量删除成功': 'Batch-Löschen erfolgreich',
  '批量启用': 'Ausgewählte aktivieren',
  '批量启用完成': 'Ausgewählte Benutzer aktiviert',
  '批量拣货': 'Nach Batch auswählen',
  '批量操作成功': 'Batch-Vorgang erfolgreich',
  '批量禁用': 'Ausgewählte deaktivieren',
  '批量禁用完成': 'Ausgewählte Benutzer deaktiviert',
  '承运商': 'Versanddienstleister',
  '承运商服务': 'Versanddienst',
  '承运服务': 'Versanddienst',
  '投资活动净额': 'Netto-Investitions-Cashflow',
  '投资活动流入': 'Investitionszuflüsse',
  '投资活动流出': 'Investitionsabflüsse',
  '折旧年份': 'Abschreibungsjahr',
  '折旧月份': 'Abschreibungsmonat',
  '折旧计提成功': 'Abschreibung erfasst',
  '报价单': 'Angebot',
  '报价单号': 'Angebots-Nr.',
  '报价时间': 'Angeboten am',
  '报价转合同': 'Angebot zu Vertrag',
  '报价金额': 'Angebotsbetrag',
  '报告人': 'Reporter',
  '报表': 'Bericht',
  '报表名称': 'Berichtsname',
  '报表管理': 'Berichte',
  '报表类型': 'Berichtstyp',
  '报表结果：{name}': 'Berichtsergebnis: {name}',
  '报表说明: {note}': 'Berichtsnotiz: {note}',
  '抽样方案': 'Stichprobenplan',
  '拒绝': 'Ablehnen',
  '拣货中': 'Kommissionierung',
  '拣货任务': 'Kommissionierauftrag',
  '拣货单': 'Kommissionierauftrag',
  '拣货管理': 'Kommissionierung',
  '指标名称': 'Metrikname',
  '指标类型': 'Metriktyp',
  '指标键名': 'Metrikschlüssel',
  '指派': 'Zuweisen',
  '指派人': 'Zugewiesener',
  '指派工单': 'Ticket zuweisen',
  '按单拣货': 'Nach Auftrag kommissionieren',
  '换一张': 'Aktualisieren',
  '换货': 'Umtausch',
  '排序': 'Sortierreihenfolge',
  '接收人': 'Empfänger',
  '描述': 'Beschreibung',
  '提交': 'Einreichen',
  '提交中...': 'Wird eingereicht...',
  '提交人': 'Eingereicht von',
  '提交失败：{error}': 'Einreichen fehlgeschlagen: {error}',
  '提交审批': 'Zur Genehmigung einreichen',
  '提交审批：{name}': 'Zur Genehmigung einreichen: {name}',
  '提交成功': 'Erfolgreich eingereicht',
  '提交时间': 'Eingereicht am',
  '提示': 'Info',
  '搜索': 'Suchen',
  '搜索...': 'Suchen...',
  '搜索商品名称/编码/批次号': 'Produktname, Code oder Charge suchen',
  '搜索用户名/姓名': 'Benutzername/Name suchen',
  '摘要': 'Zusammenfassung',
  '撤回': 'Zurückziehen',
  '撤回失败: {error}': 'Zurückziehen fehlgeschlagen: {error}',
  '撤回审批': 'Genehmigung zurückziehen',
  '操作': 'Aktionen',
  '操作失败': 'Vorgang fehlgeschlagen',
  '操作失败，请重试': 'Vorgang fehlgeschlagen, bitte erneut versuchen',
  '操作失败：{error}': 'Vorgang fehlgeschlagen: {error}',
  '操作成功': 'Vorgang erfolgreich',
  '操作日志': 'Vorgangsprotokoll',
  '操作筛选': 'Nach Aktion filtern',
  '操作者': 'Bearbeiter',
  '支付宝': 'Alipay',
  '支付状态': 'Zahlungsstatus',
  '收入结转': 'Umsatzvortrag',
  '收款单': 'Beleg',
  '收款单ID': 'Beleg-ID',
  '收款单号': 'Beleg-Nr.',
  '收款时间': 'Empfangen am',
  '收款管理': 'Belege',
  '收货仓库ID': 'Wareneingangslager-ID',
  '收货单ID': 'Wareneingangs-ID',
  '收货单号': 'Wareneingangs-Nr.',
  '收货时间': 'Empfangen am',
  '收货管理': 'Wareneingang',
  '收起菜单': 'Menü einklappen',
  '故障描述': 'Fehlerbeschreibung',
  '敏感操作需要输入密码确认': 'Passwortbestätigung für sensible Vorgänge erforderlich',
  '数据趋势（近30天）': 'Datentrend (Letzte 30 Tage)',
  '数据集': 'Datensätze',
  '数据集ID': 'Datensatz-ID',
  '数据集ID: {value}': 'Datensatz-ID: {value}',
  '数据集名称': 'Datensatzname',
  '数量': 'Menge',
  '文档列表': 'Dokumentenliste',
  '文档标题': 'Dokumenttitel',
  '文档编码': 'Dokumentencode',
  '新增': 'Hinzufügen',
  '新增OMS订单': 'OMS-Bestellung hinzufügen',
  '新增图表': 'Diagramm hinzufügen',
  '新增报价单': 'Angebot hinzufügen',
  '新增汇率': 'Wechselkurs hinzufügen',
  '新增用户': 'Benutzer hinzufügen',
  '新增结算': 'Abrechnung hinzufügen',
  '新增薪资记录': 'Lohnbuchung hinzufügen',
  '新增薪资项': 'Gehaltsposition hinzufügen',
  '新增角色': 'Rolle hinzufügen',
  '新增记账凭证': 'Beleg hinzufügen',
  '新增请假': 'Urlaub hinzufügen',
  '新增账户': 'Konto hinzufügen',
  '新增跟进': 'Nachverfolgung hinzufügen',
  '新增跟进记录': 'Nachverfolgung hinzufügen',
  '新增配置': 'Einstellung hinzufügen',
  '新增采购申请': 'Bestellanforderung hinzufügen',
  '新增采购结算（付款核销）': 'Einkaufsverrechnung hinzufügen (Zahlungsausbuchung)',
  '新增采购订单': 'Bestellung hinzufügen',
  '新增银行账户': 'Bankkonto hinzufügen',
  '新增销售结算（收款核销）': 'Verkaufsverrechnung hinzufügen (Belegausbuchung)',
  '新增销售订单': 'Verkaufsauftrag hinzufügen',
  '新增阶段': 'Phase hinzufügen',
  '新密码 (6-32位)': 'Neues Passwort (6-32 Zeichen)',
  '新密码（留空不修改）': 'Neues Passwort (leer lassen, um unverändert zu lassen)',
  '新建指标': 'Neue Metrik',
  '方向': 'Richtung',
  '方式': 'Methode',
  '方法': 'Methode',
  '无效的ID': 'Ungültige ID',
  '无权限访问': 'Zugriff verweigert',
  '日期': 'Datum',
  '旧密码': 'Altes Passwort',
  '时间': 'Zeit',
  '明细-借方金额': 'Posten Soll',
  '明细-摘要': 'Postenzusammenfassung',
  '明细-科目ID': 'Posten Konto-ID',
  '明细-贷方金额': 'Posten Haben',
  '明细分类账': 'Nebenbücher',
  '是': 'Ja',
  '是否计税(0/1)': 'Steuerpflichtig (0/1)',
  '暂无可选用户': 'Keine zuweisbaren Benutzer',
  '暂无图表，点击「新增图表」创建': 'Noch keine Diagramme; klicken Sie auf "Diagramm hinzufügen", um eines zu erstellen',
  '暂无数据': 'Keine Daten',
  '暂无明细数据': 'Keine Detaildaten',
  '暂无角色': 'Noch keine Rollen',
  '更新失败: {error}': 'Aktualisierung fehlgeschlagen: {error}',
  '更新成功': 'Erfolgreich aktualisiert',
  '最低': 'Niedrigste',
  '最低库存': 'Mindestbestand',
  '最后登录': 'Letzte Anmeldung',
  '最近操作': 'Letzte Vorgänge',
  '最高': 'Höchste',
  '最高库存': 'Höchstbestand',
  '月': 'Monat',
  '月份': 'Monat',
  '服务器内部错误': 'Interner Serverfehler',
  '服务工单': 'Service-Ticket',
  '期初借方': 'Anfangs-Soll',
  '期初现金': 'Anfangsbestand Kasse',
  '期初贷方': 'Anfangs-Haben',
  '期末借方': 'Abschluss-Soll',
  '期末现金': 'Endbestand Kasse',
  '期末结转': 'Periodenabschluss',
  '期末贷方': 'Abschluss-Haben',
  '期间': 'Periode',
  '期间 YYYY-MM': 'Periode JJJJ-MM',
  '期间 YYYY-MM(可选)': 'Periode JJJJ-MM (optional)',
  '期间值': 'Periodenwert',
  '期间类型': 'Periodentyp',
  '未分配': 'Nicht zugewiesen',
  '未发放': 'Unbezahlt',
  '未填写则留空': 'Leer lassen, um unverändert zu bleiben',
  '未授权访问': 'Nicht autorisiert',
  '未核销': 'Nicht abgerechnet',
  '未知': 'Unbekannt',
  '未结算': 'Nicht abgerechnet',
  '本位币': 'Basiswährung',
  '本年利润': 'Jahresüberschuss',
  '本期借方': 'Aktuelles Soll',
  '本期贷方': 'Aktuelles Haben',
  '权限': 'Berechtigung',
  '权限分配:': 'Berechtigungen:',
  '条码': 'Barcode',
  '来料检验(IQC)': 'Wareneingangsprüfung (IQC)',
  '来源': 'Quelle',
  '来源类型': 'Quelltyp',
  '来源记录ID': 'Quell-ID',
  '查看单据': 'Dokument anzeigen',
  '查询': 'Abfrage',
  '查询SQL': 'SQL-Abfrage',
  '查询中...': 'Abfrage läuft...',
  '查询成功，暂无数据行': 'Abfrage erfolgreich, keine Ergebniszeilen',
  '标准名称': 'Standardname',
  '标准编码': 'Standardcode',
  '标签': 'Tags',
  '标记全部已读': 'Alle als gelesen markieren',
  '标识': 'Slug',
  '标识: {slug} | 用户数: {count} | {desc}': 'Slug: {slug} | Benutzer: {count} | {desc}',
  '标题': 'Titel',
  '核销金额': 'Abschreibungsbetrag',
  '根本原因': 'Grundursache',
  '格式 YYYY-MM-DD': 'Format JJJJ-MM-TT',
  '格式 YYYY-MM-DD HH:mm:ss': 'Format JJJJ-MM-TT HH:mm:ss',
  '格式 YYYY-MM-DD HH:mm:ss，可留空': 'Format JJJJ-MM-TT HH:mm:ss, optional',
  '检验/合格/不合格': 'Geprüft/Bestanden/Abgelehnt',
  '检验单号': 'Inspektions-Nr.',
  '检验员': 'Prüfer',
  '检验数量': 'Geprüfte Menge',
  '检验标准': 'Prüfstandards',
  '检验标准ID': 'Prüfstandard-ID',
  '检验类型': 'Prüfungsart',
  '检验结果': 'Prüfergebnis',
  '检验规格': 'Prüfspezifikation',
  '模块': 'Modul',
  '模板': 'Vorlage',
  '模板ID': 'Vorlagen-ID',
  '正常': 'Normal',
  '每公斤单价': 'Preis pro kg',
  '每周': 'Wöchentlich',
  '每天': 'Täglich',
  '每月': 'Monatlich',
  '汇兑损益': 'Währungsgewinn/-verlust',
  '汇率': 'Wechselkurs',
  '汇率管理': 'Wechselkurse',
  '没有需要保存的修改': 'Keine Änderungen zu speichern',
  '波次拣货': 'Kommissionierung nach Welle',
  '波次管理': 'Welle',
  '派送中': 'In Zustellung',
  '流动比率': 'Liquiditätsgrad 3',
  '流动负债': 'Kurzfristige Verbindlichkeiten',
  '流动资产': 'Umlaufvermögen',
  '流转': 'Übergang',
  '浮动': 'Variable',
  '渠道': 'Kanal',
  '渠道店铺名称': 'Kanal-Shop-Name',
  '渠道管理': 'Kanäle',
  '渠道订单号': 'Kanalbestell-Nr.',
  '热销商品 TOP 5': 'Top 5 Produkte',
  '燃油附加费(%)': 'Kraftstoffzuschlag (%)',
  '版本': 'Version',
  '物流轨迹': 'Sendungsverfolgung',
  '状态': 'Status',
  '状态流转': 'Statuswechsel',
  '状态流转成功': 'Status geändert',
  '现金': 'Bargeld',
  '现金日记账': 'Kassenbücher',
  '现金流量表': 'Kapitalflussrechnung',
  '生产制造': 'Fertigung',
  '生产工单': 'Produktionsauftrag',
  '生产工单ID': 'Arbeitsauftrags-ID',
  '生成报表': 'Bericht erstellen',
  '生成时间': 'Erstellt am',
  '生成时间: {value}': 'Erstellt am: {value}',
  '生效日期': 'Gültigkeitsdatum',
  '用户': 'Benutzer',
  '用户ID': 'Benutzer-ID',
  '用户创建成功': 'Benutzer erstellt',
  '用户名': 'Benutzername',
  '用户名或密码错误': 'Ungültiger Benutzername oder Passwort',
  '用户更新成功': 'Benutzer aktualisiert',
  '用户状态分布': 'Benutzerstatus-Verteilung',
  '用户管理': 'Benutzer',
  '申请人ID': 'Antragsteller-ID',
  '申请单号': 'Antragsnr.',
  '申请部门': 'Abteilung',
  '电话': 'Telefon',
  '留空为0': 'Leer lassen für 0',
  '留空自动生成 CT+时间戳': 'Leer lassen, um CT+Zeitstempel automatisch zu generieren',
  '留空自动生成 PA+时间戳': 'Leer lassen, um PA+Zeitstempel automatisch zu generieren',
  '留空自动生成 PAY+时间戳': 'Leer lassen, um PAY+Zeitstempel automatisch zu generieren',
  '留空自动生成 PO+时间戳': 'Leer lassen, um PO+Zeitstempel automatisch zu generieren',
  '留空自动生成 PRN+时间戳': 'Wenn leer, automatisch PRN+Zeitstempel',
  '留空自动生成 QT+时间戳': 'Leer lassen, um QT+Zeitstempel automatisch zu generieren',
  '留空自动生成 RCV+时间戳': 'Leer lassen, um RCV+Zeitstempel automatisch zu generieren',
  '留空自动生成 SO+时间戳': 'Leer lassen, um SO+Zeitstempel automatisch zu generieren',
  '留空自动生成 SRN+时间戳': 'Wenn leer, automatisch SRN+Zeitstempel',
  '留空自动生成 VCH+时间戳': 'Leer lassen, um VCH+Zeitstempel automatisch zu generieren',
  '留空默认 合同-报价单号': 'Leer lassen für Standard-Vertragsangebotsnummer.',
  '病假': 'Krankheitsurlaub',
  '登 录': 'Anmelden',
  '登出成功': 'Erfolgreich abgemeldet',
  '登录失败': 'Anmeldung fehlgeschlagen',
  '登录成功': 'Anmeldung erfolgreich',
  '登录状态已失效，请重新登录': 'Sitzung abgelaufen, bitte erneut anmelden',
  '盘点': 'Inventur',
  '盘点任务': 'Inventuren',
  '目标币ID': 'Zielwährungs-ID',
  '目标状态': 'Zielstatus',
  '目的区域': 'Zielzone',
  '目的国家': 'Zielland',
  '看板名称': 'Dashboard-Name',
  '真实姓名': 'Echter Name',
  '确定': 'OK',
  '确定执行「{action}」？': '„{action}“ bestätigen?',
  '确定要删除「{name}」吗？': 'Sind Sie sicher, dass Sie „{name}“ löschen möchten?',
  '确定要删除图表「{name}」吗？': 'Sind Sie sicher, dass Sie Diagramm „{name}“ löschen möchten?',
  '确定要删除用户「{name}」吗？': 'Sind Sie sicher, dass Sie Benutzer „{name}“ löschen möchten?',
  '确定要删除角色「{name}」吗？': 'Sind Sie sicher, dass Sie Rolle „{name}“ löschen möchten?',
  '确定要删除该汇率记录吗？': 'Sind Sie sicher, dass Sie diesen Wechselkurs löschen möchten?',
  '确定要删除该薪资记录吗？': 'Sind Sie sicher, dass Sie diesen Lohnabrechnungsdatensatz löschen möchten?',
  '确定要删除该请假记录吗？': 'Sind Sie sicher, dass Sie diesen Urlaubsdatensatz löschen möchten?',
  '确定要删除该采购结算记录吗？': 'Sind Sie sicher, dass Sie diesen Einkaufsabrechnungsdatensatz löschen möchten?',
  '确定要删除该销售结算记录吗？': 'Sind Sie sicher, dass Sie diesen Verkaufsabrechnungsdatensatz löschen möchten?',
  '确定要删除选中的 {count} 个用户吗？': 'Die {count} ausgewählten Benutzer löschen?',
  '确定要删除配置「{key}」吗？': 'Sind Sie sicher, dass Sie die Einstellung „{key}“ löschen möchten?',
  '确定要删除银行账户「{name}」吗？': 'Sind Sie sicher, dass Sie das Bankkonto „{name}“ löschen möchten?',
  '确定要将工单「{code}」流转为「{status}」吗？': 'Arbeitsauftrag „{code}“ nach „{status}“ verschieben?',
  '确定要撤回该审批吗？': 'Diese Genehmigungsanfrage zurückziehen?',
  '确定要退出登录吗？': 'Sind Sie sicher, dass Sie sich abmelden möchten?',
  '确定退出': 'Bestätigen',
  '确认': 'Bestätigen',
  '确认删除': 'Löschen bestätigen',
  '确认发放': 'Zahlung bestätigen',
  '确认将「{period}」的薪资标记为已发放吗？': 'Gehalt für „{period}“ als bezahlt markieren?',
  '确认批准该请假申请吗？': 'Diesen Urlaubsantrag genehmigen?',
  '确认批量删除': 'Sammellöschen bestätigen',
  '确认收货': 'Empfang bestätigen',
  '确认新密码': 'Neues Passwort bestätigen',
  '确认解决': 'Lösung bestätigen',
  '确认计提': 'Bestätigen',
  '确认退出': 'Abmeldung bestätigen',
  '确认驳回该请假申请吗？': 'Diesen Urlaubsantrag ablehnen?',
  '社保(个人)': 'Sozialversicherung (Arbeitnehmer)',
  '禁用': 'Deaktivieren',
  '科目ID': 'Konto-ID',
  '科目余额': 'Kontostände',
  '税务管理': 'Steuern',
  '税率': 'Steuersatz',
  '第 {page} 页 / 共 {pages} 页 ({total} 条)': 'Seite {page} von {pages} ({total} Datensätze)',
  '等级': 'Ebene',
  '筹资活动净额': 'Netto-Finanzierungs-Cashflow',
  '筹资活动流入': 'Finanzierungszuflüsse',
  '筹资活动流出': 'Finanzierungsabflüsse',
  '管理后台': 'Admin-Konsole',
  '管理员': 'Administrator',
  '类型': 'Typ',
  '类型(0=固定 1=浮动)': 'Typ (0=fest 1=variabel)',
  '类型: {type}': 'Typ: {type}',
  '系统': 'System',
  '系统管理': 'System',
  '系统配置': 'Systemkonfiguration',
  '纠正措施': 'Korrekturmaßnahme',
  '经营': 'Geschäft',
  '经营活动净额': 'Netto-Betriebs-Cashflow',
  '经营活动流入': 'Betriebliche Zuflüsse',
  '经营活动流出': 'Betriebliche Abflüsse',
  '结束日期': 'Enddatum',
  '结束时间': 'Endzeit',
  '结果': 'Ergebnis',
  '结果: {value}': 'Ergebnis: {value}',
  '结果行数: {value}': 'Ergebniszeilen: {value}',
  '结算': 'Begleichen',
  '结算时间': 'Beglichen am',
  '结算状态': 'Abrechnungsstatus',
  '结转状态': 'Abschlussstatus',
  '绩效工资': 'Leistungsbezahlung',
  '维修': 'Reparatur',
  '维修人': 'Reparateur',
  '维修工单': 'Reparaturaufträge',
  '维修类型': 'Reparaturtyp',
  '维修费用': 'Reparaturkosten',
  '编号': 'Nr.',
  '编码': 'Code',
  '编辑': 'Bearbeiten',
  '编辑OMS订单': 'OMS-Auftrag bearbeiten',
  '编辑图表': 'Diagramm bearbeiten',
  '编辑报价单': 'Angebot bearbeiten',
  '编辑收货单（仅备注）': 'Wareneingang bearbeiten (nur Bemerkung)',
  '编辑汇率': 'Wechselkurs bearbeiten',
  '编辑用户': 'Benutzer bearbeiten',
  '编辑薪资': 'Lohnabrechnung bearbeiten',
  '编辑薪资项': 'Gehaltsposition bearbeiten',
  '编辑角色': 'Rolle bearbeiten',
  '编辑记账凭证': 'Beleg bearbeiten',
  '编辑请假': 'Urlaub bearbeiten',
  '编辑跟进记录': 'Nachverfolgung bearbeiten',
  '编辑配置': 'Einstellung bearbeiten',
  '编辑采购申请': 'Bestellanforderung bearbeiten',
  '编辑采购结算': 'Einkaufsabrechnung bearbeiten',
  '编辑采购订单': 'Bestellung bearbeiten',
  '编辑银行账户': 'Bankkonto bearbeiten',
  '编辑销售结算': 'Verkaufsabrechnung bearbeiten',
  '编辑销售订单': 'Verkaufsauftrag bearbeiten',
  '编辑阶段': 'Phase bearbeiten',
  '缺陷数量': 'Fehlermenge',
  '缺陷类型': 'Fehlertyp',
  '网络连接失败，请检查网络': 'Netzwerkverbindung fehlgeschlagen, bitte überprüfen Sie Ihr Netzwerk',
  '网络错误，请检查连接': 'Netzwerkfehler, bitte überprüfen Sie Ihre Verbindung',
  '考勤': 'Anwesenheit',
  '考勤管理': 'Anwesenheit',
  '职位': 'Position',
  '职位管理': 'Positionen',
  '联系人': 'Kontakt',
  '草稿': 'Entwurf',
  '营业成本': 'Betriebskosten',
  '营业收入': 'Betriebseinnahmen',
  '营销活动': 'Kampagne',
  '薪资': 'Gehalt',
  '薪资发放': 'Gehälter auszahlen',
  '薪资已发放': 'Gehalt als bezahlt markiert',
  '薪资年度': 'Gehaltsjahr',
  '薪资月份': 'Gehaltsmonat',
  '薪资管理': 'Lohnabrechnung',
  '薪资试算': 'Gehaltsberechnung',
  '薪资项配置': 'Lohnpositionen',
  '行数': 'Zeilen',
  '规格': 'Spezifikation',
  '规格名称': 'Spezifikationsname',
  '规格型号': 'Modell/Spezifikation',
  '角色': 'Rolle',
  '角色创建成功': 'Rolle erstellt',
  '角色删除成功': 'Rolle gelöscht',
  '角色更新成功': 'Rolle aktualisiert',
  '角色管理': 'Rollen',
  '解决': 'Lösen',
  '解决工单': 'Ticket lösen',
  '解决说明': 'Lösungsnotizen',
  '计划名称': 'Planname',
  '计划生产数量': 'Geplante Menge',
  '计提折旧': 'Abschreibung erfassen',
  '计税': 'Steuerpflichtig',
  '计算中...': 'Berechnung läuft...',
  '计算比率': 'Kennzahlen berechnen',
  '计算薪资': 'Gehalt berechnen',
  '订单': 'Auftrag',
  '订单名称': 'Auftragsname',
  '订单总金额': 'Auftragsgesamtbetrag',
  '订单状态分布': 'Auftragsstatus-Verteilung',
  '订单管理': 'Auftragsverwaltung',
  '订单编号': 'Auftragsnr.',
  '订单编码': 'Auftragscode',
  '记录不存在': 'Datensatz nicht gefunden',
  '记录已存在': 'Datensatz existiert bereits',
  '记账凭证': 'Beleg',
  '设备ID': 'Geräte-ID',
  '设备分类': 'Gerätekategorie',
  '设备台账': 'Ausrüstungsbuch',
  '设备名称': 'Ausrüstungsname',
  '设备编码': 'Ausrüstungscode',
  '试算平衡表': 'Probebilanz',
  '试算结果': 'Berechnungsergebnis',
  '详情': 'Details',
  '说明': 'Beschreibung',
  '请假': 'Urlaub',
  '请假原因': 'Grund',
  '请假天数': 'Urlaubstage',
  '请假日期': 'Urlaubszeitraum',
  '请假管理': 'Urlaub',
  '请假类型': 'Urlaubsart',
  '请先选择用户': 'Bitte wählen Sie zuerst Benutzer aus',
  '请加载验证码': 'Bitte laden Sie das Captcha',
  '请按顺序点击图中文字: {text}': 'Klicken Sie die Zeichen im Bild in der Reihenfolge: {text}',
  '请按顺序点击图中文字『{text}』': 'Klicken Sie das Zeichen \\\'{text}\\\' in der Reihenfolge',
  '请求失败': 'Anfrage fehlgeschlagen',
  '请求超时，请稍后重试': 'Zeitüberschreitung bei der Anfrage, bitte später erneut versuchen',
  '请求过于频繁，请稍后重试': 'Zu viele Anfragen, bitte später erneut versuchen',
  '请至少填写一行分配明细': 'Fügen Sie mindestens eine Zuordnungszeile hinzu',
  '请输入{label}': 'Bitte geben Sie {label} ein',
  '请输入密码': 'Bitte geben Sie Ihr Passwort ein',
  '请输入用户名和密码': 'Bitte geben Sie Benutzername und Passwort ein',
  '请输入科目ID（account_subject_id 必填）': 'Geben Sie die Konto-ID ein (account_subject_id ist erforderlich)',
  '请选择目标状态': 'Bitte wählen Sie einen Zielstatus aus',
  '调休': 'Freizeitausgleich',
  '负债总计': 'Gesamtverbindlichkeiten',
  '负责人': 'Zugewiesener',
  '财务': 'Finanzen',
  '财务比率': 'Finanzkennzahlen',
  '账号已被锁定': 'Konto ist gesperrt',
  '账户余额': 'Kontostand',
  '账户名称': 'Kontoname',
  '购买日期': 'Kaufdatum',
  '贷': 'Haben',
  '贷方合计': 'Gesamthaben',
  '费用': 'Aufwand',
  '费用合计': 'Gesamtaufwand',
  '费用报销': 'Aufwand',
  '费用结转': 'Kostenübertrag',
  '资产总计': 'Gesamtvermögen',
  '资产收益率': 'Gesamtkapitalrendite',
  '资产负债率': 'Verschuldungsgrad',
  '资产负债表': 'Bilanz',
  '资产负债表 JSON *': 'Bilanz JSON *',
  '起始区域': 'Herkunftszone',
  '起始国家': 'Herkunftsland',
  '起始重量(kg)': 'Gewicht von (kg)',
  '起步价': 'Grundtarif',
  '跟进主题': 'Betreff der Nachverfolgung',
  '跟进内容': 'Inhalt der Nachverfolgung',
  '跟进记录': 'Nachverfolgung',
  '路径': 'Pfad',
  '路径筛选': 'Nach Pfad filtern',
  '转合同': 'In Vertrag umwandeln',
  '输入关键词搜索': 'Suchbegriffe eingeben',
  '输入密码确认': 'Zur Bestätigung Passwort eingeben',
  '过程检验(IPQC)': 'Zwischenprüfung (IPQC)',
  '运单': 'Sendung',
  '运单号': 'Sendungsnummer',
  '运单管理': 'Sendungen',
  '运费': 'Versandgebühr',
  '运费发票': 'Frachtrechnung',
  '运费费率': 'Frachttarif',
  '运输中': 'Im Transit',
  '运输管理': 'Transportmanagement',
  '退出登录': 'Abmelden',
  '退回时间': 'Zurückgegeben am',
  '退回运费': 'Rücksendegebühr',
  '退换单号': 'RMA-Nr.',
  '退换货': 'RMA',
  '退换货(RMA)': 'Retouren (RMA)',
  '退款': 'Rückerstattung',
  '退款金额': 'Erstattungsbetrag',
  '退货': 'Retoure',
  '退货单号': 'Retouren-Nr.',
  '退货时间': 'Zurückgegeben am',
  '选填': 'Optional',
  '通知': 'Benachrichtigung',
  '通知中心': 'Benachrichtigungen',
  '通过': 'Genehmigen',
  '通过审批': 'Genehmigen',
  '邮箱': 'E-Mail',
  '部分发货': 'Teilweise versandt',
  '部分收货': 'Teilweise erhalten',
  '部分核销': 'Teilweise abgerechnet',
  '部分结算': 'Teilweise abgerechnet',
  '部分退款': 'Teilweise erstattet',
  '部门': 'Abteilung',
  '部门ID': 'Abteilungs-ID',
  '部门管理': 'Abteilungen',
  '配置JSON': 'Konfigurations-JSON',
  '配送方式': 'Versandmethode',
  '采购': 'Einkauf',
  '采购收货': 'Wareneingang',
  '采购申请': 'Bestellanforderung',
  '采购申请ID': 'Bestellanforderungs-ID',
  '采购结算': 'Einkaufsabrechnung',
  '采购订单': 'Bestellung',
  '采购退货': 'Einkaufsrückgabe',
  '释放回公海': 'Für Pool freigeben',
  '重试': 'Wiederholen',
  '金额': 'Betrag',
  '金额超出限额': 'Betrag überschreitet Limit',
  '银行': 'Bank',
  '银行账号': 'Bankkontonummer',
  '银行账户': 'Bankkonten',
  '销售': 'Verkauf',
  '销售发货': 'Verkaufslieferung',
  '销售报价': 'Verkaufsangebote',
  '销售渠道': 'Vertriebskanal',
  '销售漏斗': 'Verkaufstrichter',
  '销售结算': 'Verkaufsabrechnungen',
  '销售订单': 'Verkaufsauftrag',
  '销售趋势（近30天）': 'Verkaufstrend (letzte 30 Tage)',
  '销售退货': 'Verkaufsrückgabe',
  '错误': 'Fehler',
  '键': 'Schlüssel',
  '阶段': 'Phase',
  '阶段名称': 'Phasenname',
  '需已审核的付款单 hashid': 'Hashid eines genehmigten Zahlungsdatensatzes',
  '需已审核的收款单 hashid': 'Hashid eines genehmigten Belegdatensatzes',
  '非流动负债': 'Langfristige Verbindlichkeiten',
  '非流动资产': 'Langfristige Vermögenswerte',
  '非空 JSON 数组，每项须含 ledger_id 或 company_id（后端数字ID，非 hashid）与 report_year（≥2000）、report_month（1-12）': 'Nicht-leeres JSON-Array; jedes Element muss ledger_id oder company_id (numerische Backend-ID, nicht Hashid) sowie report_year (≥2000) und report_month (1-12) enthalten',
  '项目': 'Projekt',
  '项目列表': 'Projektliste',
  '预到货(ASN)': 'Erwartete Eingänge (ASN)',
  '预到货通知': 'ASN',
  '预算': 'Budget',
  '预算管理': 'Budgets',
  '领取': 'Reklamation',
  '领取客户': 'Reklamationskunde',
  '频率': 'Häufigkeit',
  '驳回': 'Ablehnen',
  '驳回审批': 'Ablehnen',
  '驳回请假': 'Urlaub ablehnen',
  '验证码加载失败': 'Captcha konnte nicht geladen werden',
  '验证码错误，请重试': 'Falsches Captcha, bitte erneut versuchen',
  '旋转图片验证': 'Bild-Captcha drehen',
  '滑块拼图验证': 'Slider-Puzzle-Captcha',
  '尝试次数过多，请更换验证码': 'Zu viele Versuche, bitte Captcha aktualisieren',
  '转动图片使其摆正后提交': 'Drehen Sie das Bild aufrecht, dann absenden',
  '拖动拼图块使其对齐图中缺口': 'Ziehen Sie das Puzzleteil in die Lücke im Bild',
  '高库存预警': 'Überbestandswarnungen',
  '高度': 'Höhe',
  '默认 0': 'Standard 0',
  '默认金额': 'Standardbetrag',
  '0 为顶级': '0 für oberste Ebene',
  '3-50 字符': '3-50 Zeichen',
  '6-32 字符': '6-32 Zeichen',
  '6-32 位': '6-32 Zeichen',
  'BI 看板': 'BI-Dashboard',
  'BOM 名称': 'Stücklistenname',
  'BOM 管理': 'Stücklistenverwaltung',
  'BOM 编码': 'Stücklistencode',
  'CRM 报价单': 'CRM-Angebot',
  'LOGO 地址': 'Logo-URL',
  'MRP 计划': 'MRP-Plan',
  'MRP 运算': 'MRP ausführen',
  'Offer 已发出': 'Angebot gesendet',
  'Offer 薪资': 'Angebotsgehalt',
  'erp开放平台': 'Open-ERP-Plattform',
  '上一页': 'Zurück',
  '上架': 'Veröffentlichen',
  '上架完成': 'Einlagerung erledigt',
  '上架已完成': 'Einlagerung abgeschlossen',
  '上次登录': 'Letzte Anmeldung',
  '上班打卡': 'Einstempeln',
  '上级部门': 'Übergeordnete Abteilung',
  '下一页': 'Weiter',
  '下架': 'Veröffentlichung aufheben',
  '下班打卡': 'Ausstempeln',
  '不合格': 'Ablehnen',
  '不合格品单号': 'NCR-Nummer',
  '不通过': 'Nicht bestanden',
  '两位小数，如 30000.00': 'Bis zu 2 Dezimalstellen, z. B. 30000.00',
  '两位小数，如 5000.00': 'Bis zu 2 Dezimalstellen, z. B. 5000.00',
  '两次输入的新密码不一致': 'Die beiden neuen Passwörter stimmen nicht überein',
  '中标转订单': 'Zuschlag zur Bestellung',
  '产品': 'Produkt',
  '人工': 'Arbeit',
  '仓库名称': 'Lagername',
  '仓库管理': 'Lagerverwaltung',
  '仓库编码': 'Lagerkennung',
  '付款方式': 'Zahlungsart',
  '付款日期': 'Zahlungsdatum',
  '付款账户': 'Zahlungskonto',
  '任务名称': 'Aufgabenname',
  '任职要求': 'Anforderungen',
  '作废': 'Stornieren',
  '使用年限': 'Nutzungsdauer',
  '供应商名称': 'Lieferantenname',
  '供应商报价': 'Lieferantenangebote',
  '供应商评估': 'Lieferantenbewertung',
  '保存失败': 'Speichern fehlgeschlagen',
  '保存资料': 'Profil speichern',
  '信用账期(天)': 'Zahlungsziel (Tage)',
  '信用额度': 'Kreditlimit',
  '修改失败': 'Update fehlgeschlagen',
  '候选人': 'Kandidat',
  '停用': 'Aussetzen',
  '兑付': 'Bargeld',
  '入职日期': 'Eintrittsdatum',
  '全部通知已标记为已读': 'Alle Benachrichtigungen als gelesen markiert',
  '共': 'von',
  '关联任务': 'Verknüpfte Aufgabe',
  '内训': 'Intern',
  '再次输入新密码': 'Neues Passwort erneut eingeben',
  '净值': 'Nettowert',
  '出库仓库': 'Ausgabelager',
  '出票人': 'Schublade',
  '出票日期': 'Ausgabedatum',
  '出货检验': 'Endkontrolle OQC',
  '出货检验 OQC': 'Endkontrolle OQC',
  '分类名称': 'Kategoriename',
  '初筛通过': 'Screening bestanden',
  '利润表': 'Gewinn- und Verlustrechnung',
  '到期': 'Abgelaufen',
  '到期预警': 'Ablaufwarnungen',
  '制费': 'Gemeinkosten',
  '加工单价': 'Bearbeitungspreis',
  '加载中…': 'Wird geladen...',
  '勾选': 'Prüfen',
  '协同管理': 'Zusammenarbeit',
  '原值': 'Originalwert',
  '发出': 'Senden',
  '发布': 'Veröffentlichen',
  '发布中': 'Veröffentlicht',
  '发料仓库': 'Ausgabelager',
  '发料单号': 'Ausgabeschein-Nr.',
  '发料单已审核': 'Ausgabeschein genehmigt',
  '发料日期': 'Ausgabedatum',
  '发生日期': 'Ereignisdatum',
  '发票号': 'Rechnungs-Nr.',
  '发票管理': 'Rechnungsverwaltung',
  '发货': 'Versenden',
  '发货单': 'Lieferschein',
  '发货日期': 'Versanddatum',
  '发起审批': 'Genehmigung starten',
  '取消点检': 'Inspektion abbrechen',
  '合同号': 'Vertragsnr.',
  '合同金额': 'Vertragsbetrag',
  '合格': 'Bestanden',
  '合格数': 'Bestandene Menge',
  '合计': 'Gesamt',
  '启停': 'Umschalten',
  '启动': 'Start',
  '启用日期': 'Inbetriebnahmedatum',
  '员工姓名': 'Mitarbeitername',
  '员工编码': 'Mitarbeitercode',
  '周期类型': 'Periodentyp',
  '品牌名称': 'Markenname',
  '品牌描述': 'Markenbeschreibung',
  '品项数': 'Positionen',
  '商品描述': 'Beschreibung',
  '商品管理': 'Produktverwaltung',
  '商品资料': 'Produktstamm',
  '商机名称': 'Verkaufschancenname',
  '回复': 'Antworten',
  '回调地址': 'Rückruf-URL',
  '图标': 'Symbol',
  '图表组件': 'Diagramm-Widget',
  '城市': 'Stadt',
  '培训社保': 'Schulung & Sozialversicherung',
  '培训课程': 'Schulungskurse',
  '基本资料': 'Basisprofil',
  '处理中': 'Verarbeitung',
  '备件管理': 'Ersatzteile',
  '外训': 'Extern',
  '多币种': 'Währungen',
  '多组织公司': 'Unternehmen',
  '如 admin、viewer': 'z.B. Admin, Betrachter',
  '如 monthly': 'z.B. monatlich',
  '如 上海': 'z.B. Shanghai',
  '如 人民币': 'z.B. CNY',
  '委外产品': 'Outsourcing-Produkt',
  '委外加工': 'Unterauftragsvergabe',
  '委外发料': 'Unterauftragserteilung',
  '委外收货': 'Unterauftragseingang',
  '委外数量': 'Unterauftragsmenge',
  '委外订单': 'Unterauftrag',
  '字符串': 'Zeichenkette',
  '季度': 'Vierteljährlich',
  '学分': 'Guthaben',
  '完工': 'Abgeschlossen',
  '完工数': 'Abgeschlossene Menge',
  '实发': 'Nettolohn',
  '审批已发起': 'Genehmigung gestartet',
  '审核': 'Genehmigen',
  '客户名称': 'Kundenname',
  '客户管理': 'Kundenverwaltung',
  '密码已修改': 'Passwort geändert',
  '密钥已重置': 'Secret zurückgesetzt',
  '小计': 'Zwischensumme',
  '工作站名称': 'Arbeitsplatzname',
  '工作站编码': 'Arbeitsplatzcode',
  '工单分类': 'Ticketkategorie',
  '工单号': 'Ticket-Nr.',
  '工单已完工': 'Arbeitsauftrag abgeschlossen',
  '工单已开工': 'Arbeitsauftrag gestartet',
  '工单已解决': 'Ticket gelöst',
  '工单标题': 'Tickettitel',
  '工序': 'Vorgang',
  '工序名称': 'Vorgangsname',
  '工序序号': 'Reihenfolge',
  '工序报工': 'Arbeitsbericht',
  '工时数': 'Stunden',
  '工资条': 'Lohnabrechnung',
  '已作废': 'Storniert',
  '已入职': 'Eingearbeitet',
  '已发 Offer': 'Angebot gesendet',
  '已发出': 'Gesendet',
  '已回复': 'Geantwortet',
  '已完成库存分配': 'Bestand zugewiesen',
  '已归档': 'Archiviert',
  '已接受': 'Akzeptiert',
  '已提交': 'Eingereicht',
  '已撤销': 'Zurückgezogen',
  '已标记为已读': 'Als gelesen markiert',
  '已派单': 'Zugewiesen',
  '已淘汰': 'Abgelehnt',
  '已生成合同': 'Vertrag erstellt',
  '已生成履约单': 'Fulfillment erstellt',
  '已生成采购订单': 'Bestellung erstellt',
  '已生效': 'Wirksam',
  '已用': 'Verwendet',
  '已结': 'Abgerechnet',
  '已认领': 'Beansprucht',
  '已读': 'Gelesen',
  '已释放回公海': 'Zurück in den Pool freigegeben',
  '币种名称': 'Währungsname',
  '币种管理': 'Währungsverwaltung',
  '币种编码': 'Währungscode',
  '布尔': 'Boolesch',
  '库位名称': 'Standortname',
  '库位编码': 'Standortcode',
  '库区名称': 'Zonenname',
  '库区编码': 'Zonencode',
  '库存分配': 'Bestand zuweisen',
  '库存管理': 'Bestandsverwaltung',
  '应发': 'Bruttolohn',
  '应用名称': 'App-Name',
  '应聘职位': 'Beworbene Stelle',
  '开工': 'Start',
  '开户行': 'Bank',
  '开放应用': 'OpenAPI-Apps',
  '开票': 'Rechnung ausstellen',
  '开票日期': 'Rechnungsdatum',
  '归档': 'Archivieren',
  '归集日期': 'Buchungsdatum',
  '当前密码': 'Aktuelles Passwort',
  '录用 Offer': 'Arbeitsangebot',
  '往来方': 'Gegenpartei',
  '待定': 'Ausstehend',
  '待开通': 'Ausstehende Rückstellung',
  '总账': 'Hauptbuch',
  '成本': 'Kosten',
  '成本归集': 'Kosteneintrag',
  '成本类别': 'Kostenkategorie',
  '所属仓库': 'Lager',
  '所属应用': 'App',
  '所属模块': 'Modul',
  '所属看板': 'Dashboard',
  '所属部门': 'Abteilung',
  '所属项目': 'Projekt',
  '手机': 'Telefon',
  '打包完成': 'Verpackt',
  '打包已完成': 'Verpackung abgeschlossen',
  '打卡成功': 'Erfolgreich gestempelt',
  '托收': 'Sammeln',
  '托收账户': 'Inkassokonto',
  '执行报表': 'Bericht ausführen',
  '批次效期预警': 'Chargen-Ablaufwarnungen',
  '承兑人': 'Akzeptant',
  '承兑汇票': 'Bankakzept',
  '承运商名称': 'Frachtführer',
  '投递测试完成': 'Testlieferung abgeschlossen',
  '折扣': 'Rabatt',
  '折旧已计提': 'Abschreibung gebucht',
  '折旧方法': 'Abschreibungsmethode',
  '报工员工': 'Berichtender Mitarbeiter',
  '报工已审核': 'Arbeitsbericht genehmigt',
  '报工数量': 'Gemeldete Menge',
  '报工日期': 'Berichtsdatum',
  '报表已执行': 'Bericht ausgeführt',
  '报表模板': 'Berichtsvorlage',
  '报销金额': 'Erstattungsbetrag',
  '抵扣': 'Abziehen',
  '拒付': 'Ablehnen',
  '招聘人数': 'Mitarbeiterzahl',
  '招聘候选人': 'Kandidaten',
  '招聘管理': 'Rekrutierung',
  '招聘职位': 'Stellenanzeigen',
  '招聘部门': 'Einstellungsabteilung',
  '招聘面试': 'Vorstellungsgespräche',
  '拣货已确认': 'Kommissionierung bestätigt',
  '拣货确认': 'Kommissionierung bestätigen',
  '按钮': 'Schaltfläche',
  '提交数': 'Eingereichte Menge',
  '搜索通知内容': 'Benachrichtigungsinhalt suchen',
  '搜索配置键': 'Konfigurationsschlüssel suchen',
  '撤销': 'Abheben',
  '操作人': 'Bediener',
  '支付': 'Zahlen',
  '收料仓库': 'Empfangslager',
  '收料单号': 'Beleg-Nr.',
  '收料单已审核': 'Beleg genehmigt',
  '收料数量': 'Empfangene Menge',
  '收料日期': 'Empfangsdatum',
  '收款人': 'Zahlungsempfänger',
  '收款方式': 'Empfangsmethode',
  '收款日期': 'Empfangsdatum',
  '收款账户': 'Empfangskonto',
  '收款金额': 'Empfangsbetrag',
  '收票': 'Empfangen',
  '收货单': 'Empfangsvermerk',
  '收货完成': 'Empfang abgeschlossen',
  '收货已完成': 'Empfang abgeschlossen',
  '收货日期': 'Empfangsdatum',
  '数组': 'Array',
  '整数': 'Ganzzahl',
  '文档内容': 'Inhalt',
  '文档分类': 'Kategorie',
  '文档管理': 'Dokumentenverwaltung',
  '新增成功': 'Erstellt',
  '新密码': 'Neues Passwort',
  '新密码长度需为 6-32 位': 'Das neue Passwort muss 6-32 Zeichen lang sein',
  '新简历': 'Neuer Lebenslauf',
  '是否启用': 'Aktiviert',
  '更新时间': 'Aktualisiert am',
  '最大库存阈值': 'Maximaler Bestandsschwellenwert',
  '最小库存阈值': 'Minimaler Bestandsschwellenwert',
  '月度': 'Monatlich',
  '服务名称': 'Dienstname',
  '期望薪资': 'Erwartetes Gehalt',
  '期间已结账': 'Periode geschlossen',
  '未开始': 'Nicht gestartet',
  '未结': 'Unbeglichen',
  '未设置': 'Nicht festgelegt',
  '未读': 'Ungelesen',
  '权限名': 'Berechtigungsname',
  '权限管理': 'Berechtigungsverwaltung',
  '材料': 'Material',
  '条': 'Datensätze',
  '来料检验': 'IQC',
  '来料检验 IQC': 'Wareneingangsprüfung IQC',
  '来源币种': 'Ausgangswährung',
  '来源渠道': 'Quelle',
  '标记已读': 'Als gelesen markieren',
  '模板名称': 'Vorlagenname',
  '模板已启用': 'Vorlage aktiviert',
  '模板编码': 'Vorlagencode',
  '残值': 'Restwert',
  '比价': 'Vergleichen',
  '汇率值': 'Kurs',
  '波次已释放': 'Welle freigegeben',
  '波次释放': 'Welle freigeben',
  '活动名称': 'Kampagnenname',
  '派单': 'Zuweisen',
  '测试投递': 'Testlieferung',
  '渠道名称': 'Kanalname',
  '漏斗阶段名称': 'Phasenname',
  '点检任务': 'Prüfaufgaben',
  '点检日期': 'Prüfdatum',
  '父任务': 'Übergeordnete Aufgabe',
  '父级 ID': 'Übergeordnete ID',
  '状态已切换': 'Status umgeschaltet',
  '状态已更新': 'Status aktualisiert',
  '生产领料': 'Materialausgabe',
  '用户数': 'Benutzer',
  '申请人': 'Antragsteller',
  '界面语言': 'Sprache',
  '登录已过期，请重新登录': 'Sitzung abgelaufen, bitte erneut anmelden',
  '盘点任务名称': 'Inventurname',
  '盘点单号': 'Inventurnummer',
  '目录': 'Verzeichnis',
  '目标币种': 'Zielwährung',
  '目标类型': 'Zieltyp',
  '直线法': 'Lineare Abschreibung',
  '看板布局': 'Dashboard-Layout',
  '确认操作': 'Aktion bestätigen',
  '社保规则': 'Sozialversicherungsregeln',
  '票据号': 'Rechnungsnummer',
  '票面金额': 'Nennbetrag',
  '租户列表': 'Mandanten',
  '租户已停用': 'Mandant gesperrt',
  '租户已启用': 'Mandant wieder aktiviert',
  '租户管理': 'Mandantenverwaltung',
  '税号': 'Steuernummer',
  '税率管理': 'Steuersätze',
  '税额': 'Steuerbetrag',
  '第': 'Seite',
  '签订日期': 'Unterschriftsdatum',
  '算薪': 'Lohnabrechnung berechnen',
  '算薪完成': 'Lohnabrechnung berechnet',
  '纳税记录': 'Steuerdatensätze',
  '线上': 'Online',
  '组件名称': 'Widget-Name',
  '组件类型': 'Widget-Typ',
  '结账': 'Periode schließen',
  '绩效模板': 'Leistungsvorlagen',
  '绩效考核': 'Leistungsbeurteilung',
  '维修工单号': 'Reparaturauftragsnummer',
  '缴费基数上限': 'Basisobergrenze',
  '缴费基数下限': 'Basisuntergrenze',
  '考核批次已启动': 'Beurteilung gestartet',
  '考核批次已归档': 'Beurteilung archiviert',
  '考核计划': 'Beurteilungspläne',
  '考核评分': 'Beurteilungsergebnisse',
  '耗时(ms)': 'Verstrichen (ms)',
  '职位名称': 'Stellenbezeichnung',
  '职位已关闭': 'Stelle geschlossen',
  '职位已发布': 'Stelle veröffentlicht',
  '职位编码': 'Positionscode',
  '联系人名称': 'Kontaktname',
  '背书': 'Bestätigen',
  '自定义字段': 'Benutzerdefinierte Felder',
  '自定义报表': 'Benutzerdefinierte Berichte',
  '获取面单': 'Label abrufen',
  '菜单': 'Menü',
  '规则名称': 'Regelname',
  '角色名': 'Rollenname',
  '角色权限': 'Rollen',
  '计划年度': 'Planjahr',
  '计划数': 'Gepl. Menge',
  '计划数量': 'Geplante Menge',
  '计划日期': 'Plandatum',
  '计划月份': 'Planmonat',
  '计划编码': 'Plancode',
  '订单号': 'Auftragsnr.',
  '订单履约': 'Auftragsabwicklung',
  '订单已取消': 'Auftrag storniert',
  '认领': 'Reklamation',
  '讲师': 'Dozent',
  '设备': 'Ausrüstung',
  '设备管理': 'Ausrüstungsverwaltung',
  '询价单': 'Anfrage',
  '询价单已关闭': 'Anfrage geschlossen',
  '请输入当前密码': 'Aktuelles Passwort eingeben',
  '请输入登录密码确认操作': 'Anmeldepasswort zur Bestätigung eingeben',
  '课时(小时)': 'Dauer (Stunden)',
  '课程标题': 'Kurstitel',
  '课程类型': 'Kursart',
  '调出仓库': 'Von Lager',
  '调拨单号': 'Transfernr.',
  '调拨日期': 'Transferdatum',
  '财务管理': 'Finanzverwaltung',
  '账套期间': 'Hauptbuchperioden',
  '账户编码': 'Kontocode',
  '质量管理': 'Qualitätsmanagement',
  '购置日期': 'Kaufdatum',
  '购置金额': 'Kaufbetrag',
  '贴现': 'Rabatt',
  '费用科目': 'Aufwandskonto',
  '费用类型': 'Aufwandsart',
  '资产名称': 'Anlagenname',
  '资产类别': 'Anlagenkategorie',
  '资产编号': 'Anlagennr.',
  '资产编码': 'Anlagencode',
  '资料已保存': 'Profil gespeichert',
  '赢单': 'Gewonnen',
  '跟进中': 'Nachverfolgung',
  '跟进人': 'Follower',
  '轮次': 'Runde',
  '输单': 'Verloren',
  '过程检验': 'IPQC',
  '过程检验 IPQC': 'Prozessprüfung IPQC',
  '运单已发货': 'Sendung versandt',
  '运算完成': 'MRP-Lauf abgeschlossen',
  '运费已支付': 'Fracht bezahlt',
  '运费已确认': 'Fracht bestätigt',
  '运输服务': 'Transportdienstleistungen',
  '进行中': 'In Bearbeitung',
  '进项发票池': 'Eingangsrechnungspool',
  '退换货 RMA': 'RMA-Rücksendung',
  '退货仓库': 'Retourenlager',
  '退货入库': 'Rücksendung erhalten',
  '退货金额': 'Retourenbetrag',
  '部门名称': 'Abteilungsname',
  '部门编码': 'Abteilungscode',
  '配置键': 'Schlüssel',
  '采购管理': 'Einkaufsmanagement',
  '采购销售': 'Beschaffung & Vertrieb',
  '释放': 'Freigeben',
  '重置密钥': 'Geheimnis zurücksetzen',
  '销售管理': 'Vertriebsmanagement',
  '集团财务': 'Konzernfinanzen',
  '面单已生成': 'Etikett erstellt',
  '面试中': 'Im Interview',
  '面试日期': 'Interviewdatum',
  '页': 'von',
  '项目名称': 'Projektname',
  '项目成本': 'Projektkosten',
  '项目管理': 'Projektmanagement',
  '项目编号': 'Projektcode',
  '预到货 ASN': 'ASN',
  '预算名称': 'BudgetName',
  '预算对比': 'Budget vergleichen',
  '预算年度': 'Haushaltsjahr',
  '预算额': 'Budgetbetrag',
  '预计金额': 'Erwarteter Betrag',
  '领料单已审核': 'Problem genehmigt',
  '领料日期': 'Ausgabedatum',
  '验真': 'Überprüfen',
  '验证失败，请重试': 'Überprüfung fehlgeschlagen, bitte erneut versuchen',
  '搜索菜单': 'Menüs durchsuchen',
  '关闭标签': 'Tab schließen',
  '关闭其他标签': 'Andere Tabs schließen',
  '关闭全部标签': 'Alle Tabs schließen',
  '关闭其他': 'Andere schließen',
  '关闭全部': 'Alle schließen',
  '页面不存在': 'Seite nicht gefunden',
  '当前路由未注册': 'Route nicht registriert',
  '人机验证': 'Captcha',
  '点击文字验证': 'Zeichen anklicken',
  '验证码加载中…': 'Captcha wird geladen...',
  '暂无趋势数据': 'Noch keine Trenddaten',
  '账户状态分布': 'Kontostatus',
  '最近操作日志': 'Letzte Protokolle',
  '暂无日志': 'Keine Protokolle',
  '近 30 天趋势': 'Trend der letzten 30 Tage',
  '已完成人机验证，点击「登 录」继续': 'Captcha bestätigt. Klicken Sie auf Anmelden, um fortzufahren',
  '登录需先完成人机验证': 'Bitte zuerst das Captcha ausfüllen',
  '全部已读': 'Alle als gelesen markieren',
  '请选择': 'Auswählen...',
  '条/页': 'Einträge/Seite',
  '较昨日': 'vs. gestern',
  '按顺序点击': 'In Reihenfolge klicken',
  '请填写「{label}」': 'Bitte {label} ausfüllen',
  '新增{name}': 'Neu {name}',
  '编辑{name}': '{name} bearbeiten',
  '确定执行「{act}」吗？': '{act} ausführen?',
  '确定删除「{name}」？该操作不可恢复。': '{name} löschen? Dies kann nicht rückgängig gemacht werden.',
  '请求失败（{code}）': 'Anfrage fehlgeschlagen ({code})',
  '下载失败（{code}）': 'Download fehlgeschlagen ({code})',
  'Open ERP · Web 控制台': 'ERP öffnen · Web-Konsole',
  '业务模块': 'Module',
  '中英切换': 'Chinesisch / Englisch',
  '第 {count} 个字位置不准，请再点一次': 'Klicke erneut auf #{count} – der Punkt hat das Ziel verfehlt',
  '仍未通过，请按顺序重新点击': 'Noch nicht übereinstimmend – klicke alle Zeichen erneut in der Reihenfolge an',
  '规格属性': 'Spezifikationsattribute',
  '费率(元/小时)': 'Satz (Yuan/Stunde)',
  '订阅事件': 'Abonnierte Ereignisse',
  '0=全部': '0=Alle',
  '如 get.admin/user': 'z.B. get.admin/user',
  '搜索用户/路径': 'Benutzer/Pfad suchen',
  '多个事件名用逗号或换行分隔；* 表示全部；仅允许字母、数字与 . _ -': 'Mehrere Ereignisnamen mit Kommas oder Zeilenumbrüchen trennen; * bedeutet alle; nur Buchstaben, Ziffern und . _ - sind erlaubt',
  '勾选父级即全选其下所有子项': 'Wenn ein übergeordnetes Element ausgewählt wird, werden alle untergeordneten Elemente ausgewählt',
  '父级': 'Übergeordnet',
  '点节点选父级；点已选节点取消（空 = 顶级）': 'Klicken Sie auf einen Knoten, um ihn als übergeordnet festzulegen; klicken Sie auf einen ausgewählten Knoten, um die Auswahl aufzuheben (leer = oberste Ebene)',
  'JSON 对象：属性名 → 值数组，如 {"颜色":["红","蓝"],"尺寸":["S","M","L"]}；留空 / {} 表示无属性': 'JSON-Objekt: Attributname → Werteliste, z. B. {"Color":["Red","Blue"],"Size":["S","M","L"]}; leer lassen / {} für keine Attribute',
  'BOM': 'BOM',
  'SKU ID': 'SKU-ID',
  '删除时间': 'Gelöscht am',
};
