/*
 * Copyright (c) 2026 erik <erik@erik.xyz> — https://erik.xyz
 */

/**
 * 中文原文 → Spanish 词典（es）。由 scripts/gen-fe-locales.mjs 生成，**请勿手工编辑**。
 * 缺词条时回退中文原文；键集须与 core/zh-en 完全一致。
 */
export const zhEs: Record<string, string> = {
  ':attribute 不存在': 'El :attribute no existe',
  ':attribute 不能为空': 'El campo :attribute es obligatorio',
  ':attribute 不能大于 :max': 'El :attribute no debe superar :max',
  ':attribute 不能小于 :min': 'El :attribute debe ser al menos :min',
  ':attribute 值无效': 'El valor de :attribute no es válido',
  ':attribute 已存在': 'El :attribute ya existe',
  ':attribute 必须是字符串': 'El :attribute debe ser una cadena',
  ':attribute 必须是数字': 'El :attribute debe ser un número',
  ':attribute 必须是整数': 'El :attribute debe ser un número entero',
  ':attribute 格式不正确': 'El formato de :attribute no es válido',
  'BOM管理': 'Gestión de BOM',
  'JSON 对象，含 current_assets、current_liabilities、total_liabilities、total_assets 字段，值为数字': 'Objeto JSON con valores numéricos para current_assets, current_liabilities, total_liabilities y total_assets',
  'JSON 对象，含 net_profit、revenue 字段，值为数字': 'Objeto JSON con valores numéricos para net_profit y revenue',
  'MRP计划': 'Planificación MRP',
  'OMS 订单': 'Pedidos OMS',
  'OMS订单': 'Pedido OMS',
  'Token已过期': 'Token expirado',
  'Token无效': 'Token no válido',
  'X坐标': 'Posición X',
  'YYYY-MM-DD，如 2026-09-05': 'AAAA-MM-DD, ej. 2026-09-05',
  'Y坐标': 'Posición Y',
  'erp开放管理后台': 'Abrir administrador de ERP',
  'erp管理后台': 'Abrir administrador de ERP',
  '{field} 不是合法 JSON': '{field} no es JSON válido',
  '{field} 必须为 JSON 对象': '{field} debe ser un objeto JSON',
  '{field} 必须为 JSON 数组': '{field} debe ser un array JSON',
  '{page} / {pages} ({total}条)': '{page} / {pages} ({total})',
  '一个平台，管好全部业务': 'Una plataforma para todo tu negocio',
  '上传成功': 'Carga exitosa',
  '上架管理': 'Almacenaje',
  '上次保养日期': 'Última fecha de mantenimiento',
  '下单时间': 'Fecha del pedido',
  '下次保养日期': 'Próxima fecha de mantenimiento',
  '下次日期': 'Próxima fecha',
  '不合格品': 'Productos no conformes',
  '不合格数量': 'Cantidad rechazada',
  '不合格编号': 'N.º de defecto',
  '两次密码不一致': 'Las contraseñas no coinciden',
  '严重程度': 'Gravedad',
  '个人中心': 'Perfil',
  '个人信息更新成功': 'Perfil actualizado correctamente',
  '个人所得税': 'Impuesto sobre la Renta de Personas Físicas',
  '个税': 'Impuesto sobre la Renta',
  '主题': 'Asunto',
  '买家备注': 'Nota del comprador',
  '事假': 'Permiso personal',
  '产假': 'Permiso de maternidad',
  '人力资源': 'Recursos Humanos',
  '从供应商列表页获取数字ID': 'ID numérico de la página de lista de proveedores',
  '从员工列表页获取数字ID': 'ID numérico de la página de lista de empleados',
  '从客户列表页获取数字ID': 'ID numérico de la página de lista de clientes',
  '从科目列表获取数字ID，填了则按明细创建': 'ID numérico de la lista de cuentas; cuando se establece, el comprobante se crea con líneas de detalle',
  '从销售订单列表页获取数字ID': 'ID numérico de la página de lista de pedidos de venta',
  '仓储管理': 'Gestión de almacenes',
  '仓库': 'Almacén',
  '仓库信息': 'Información del almacén',
  '付款单': 'Pago',
  '付款单ID': 'ID de pago',
  '付款单号': 'N.º de pago',
  '付款时间': 'Fecha de pago',
  '付款管理': 'Pagos',
  '仪表盘': 'Panel',
  '价格': 'Precio',
  '任务': 'Tarea',
  '任务管理': 'Tareas',
  '企业所得税': 'Impuesto sobre Sociedades',
  '优先级': 'Prioridad',
  '优惠金额': 'Importe del descuento',
  '会计科目': 'Plan de cuentas',
  '低库存预警': 'Alertas de stock bajo',
  '余额': 'Saldo',
  '供应商': 'Proveedor',
  '供应商ID': 'ID de proveedor',
  '供应商信息': 'Información del proveedor',
  '保修到期': 'Vencimiento de garantía',
  '保养计划': 'Planes de mantenimiento',
  '保养频率': 'Frecuencia de mantenimiento',
  '保存': 'Guardar',
  '保存失败: {error}': 'Error al guardar: {error}',
  '保存成功': 'Guardado correctamente',
  '修改失败: {error}': 'Error al cambiar: {error}',
  '修改密码': 'Cambiar contraseña',
  '借': 'Débito',
  '借方合计': 'Total débitos',
  '值': 'Valor',
  '全部': 'Todos',
  '公海池': 'Grupo de leads',
  '公积金': 'Fondo de vivienda',
  '共 {count} 个': '{count} total',
  '共 {total} 条': '{total} registros',
  '关联订单': 'Pedido relacionado',
  '关联销售订单ID': 'ID de pedido de venta vinculado',
  '关闭': 'Cerrar',
  '其他': 'Otro',
  '内容': 'Contenido',
  '冻结时间': 'Retener hasta',
  '净利率': 'Margen neto',
  '凭证ID: {id}': 'ID de comprobante: {id}',
  '凭证号': 'N.º de comprobante',
  '凭证名称': 'Nombre del comprobante',
  '凭证日期': 'Fecha del comprobante',
  '出入库流水': 'Movimiento de stock',
  '出货检验(OQC)': 'Inspección de salida (OQC)',
  '分区拣货': 'Recoger por zona',
  '分类': 'Categoría',
  '分组': 'Grupo',
  '分配中': 'Asignando',
  '分配库存': 'Asignar stock',
  '分配数量不能为空': 'Cantidad requerida',
  '分配数量须为正数': 'La cantidad debe ser un número positivo',
  '创建失败: {error}': 'Error al crear: {error}',
  '创建履约': 'Crear fulfillment',
  '创建成功': 'Creado correctamente',
  '创建时间': 'Creado el',
  '删除': 'Eliminar',
  '删除({count})': 'Eliminar ({count})',
  '删除失败: {error}': 'Error al eliminar: {error}',
  '删除成功': 'Eliminado correctamente',
  '利润': 'Beneficio',
  '利润中心': 'Centro de beneficio',
  '利润报表': 'Informe de ganancias',
  '利润表 JSON *': 'Estado de resultados JSON *',
  '到期日': 'Fecha de vencimiento',
  '刷新': 'Actualizar',
  '加班费': 'Pago de horas extra',
  '加载中...': 'Cargando...',
  '加载失败': 'Error al cargar',
  '加载失败: {error}': 'Error al cargar: {error}',
  '加载权限列表失败: {error}': 'Error al cargar permisos: {error}',
  '加载用户列表失败: {error}': 'Error al cargar usuarios: {error}',
  '加载角色列表失败: {error}': 'Error al cargar roles: {error}',
  '包装类型': 'Tipo de paquete',
  '单价': 'Precio',
  '单位': 'Unidad',
  '单据ID': 'ID de documento',
  '单据ID必须为数字': 'El ID de documento debe ser numérico',
  '单据类型': 'Tipo de documento',
  '卖家备注': 'Nota del vendedor',
  '印花税': 'Impuesto de timbre',
  '原因': 'Motivo',
  '原币ID': 'ID de moneda de origen',
  '参数(JSON)': 'Parámetros (JSON)',
  '参数验证失败': 'Validación fallida',
  '发放': 'Pagar',
  '发放失败：{error}': 'Pago fallido: {error}',
  '发货仓库ID': 'ID de almacén de envío',
  '发货单ID': 'ID de entrega',
  '发货单号': 'N.º de entrega',
  '取消': 'Cancelar',
  '取消订单': 'Cancelar pedido',
  '变更说明': 'Notas de cambio',
  '合同名称': 'Nombre del contrato',
  '合同状态流转': 'Transición de estado del contrato',
  '合同管理': 'Contratos',
  '合同编号': 'N.º de contrato',
  '合并中...': 'Consolidando...',
  '合并报表': 'Informes consolidados',
  '合格数量': 'Cantidad aprobada',
  '名称': 'Nombre',
  '后端要求提供发货仓库': 'El servidor requiere un almacén de envío',
  '否': 'No',
  '启用': 'Habilitar',
  '员工': 'Empleado',
  '员工ID': 'ID de empleado',
  '员工档案': 'Empleados',
  '品牌': 'Marca',
  '品牌管理': 'Marcas',
  '商品': 'Producto',
  '商品ID': 'ID de producto',
  '商品ID须为正整数': 'El ID de producto debe ser un entero positivo',
  '商品ID（数字）': 'ID de producto (numérico)',
  '商品信息': 'Información del producto',
  '商品分类': 'Categorías',
  '商品列表': 'Lista de productos',
  '商品名称': 'Nombre del producto',
  '商品明细': 'Artículos',
  '商品编码': 'Código de producto',
  '商机': 'Oportunidad',
  '商机管理': 'Oportunidades',
  '商品规格': 'Especificaciones del producto',
  '固定': 'Fijo',
  '固定资产': 'Activo fijo',
  '图表名称': 'Nombre del gráfico',
  '图表管理': 'Administrar gráficos',
  '图表管理 — {name}': 'Administrar gráficos — {name}',
  '图表类型': 'Tipo de gráfico',
  '地址': 'Dirección',
  '地点': 'Ubicación',
  '型号': 'Modelo',
  '基本信息': 'Información básica',
  '基本工资': 'Salario base',
  '增值税': 'Impuesto al valor agregado',
  '处置方式': 'Disposición',
  '备件': 'Repuestos',
  '备件名称': 'Nombre del repuesto',
  '备件编码': 'Código del repuesto',
  '备注': 'Notas',
  '多币种/汇率': 'Multidivisa / Tipos de cambio',
  '天数': 'Días',
  '失效日期': 'Válido hasta',
  '如 1.5': 'p. ej. 1.5',
  '如 10.00': 'p. ej. 10.00',
  '如 100.00': 'p. ej. 100.00',
  '如 1000.00': 'p. ej. 1000.00',
  '如 61000000000000001=CNY': 'p. ej. 61000000000000001=CNY',
  '如 7.250000': 'p. ej. 7.250000',
  '如 8000.00': 'p. ej. 8000.00',
  '如 purchase_order / expense': 'p. ej. orden_de_compra / gasto',
  '如 {amount}': 'p. ej. {amount}',
  '姓名': 'Nombre del empleado',
  '婚假': 'Licencia por matrimonio',
  '子公司报表 JSON 数组 *': 'Array JSON de informes de subsidiarias *',
  '存放位置': 'Ubicación',
  '季': 'Trimestre',
  '完成': 'Finalizar',
  '定时调度': 'Horarios',
  '实发工资': 'Salario neto',
  '实时库存': 'Existencias disponibles',
  '审批': 'Aprobar',
  '审批中': 'Aprobando',
  '审批工作流': 'Flujo de trabajo',
  '审批意见为必填项': 'Se requiere un comentario de aprobación',
  '审批意见（必填）': 'Comentario de aprobación (obligatorio)',
  '审批意见（选填）': 'Comentario de aprobación (opcional)',
  '审批流程': 'Flujo de trabajo',
  '审批记录': 'Registros de aprobación',
  '客户': 'Cliente',
  '客户ID': 'ID de cliente',
  '客户信息': 'Información del cliente',
  '客户分析': 'Analíticas de clientes',
  '宽度': 'Ancho',
  '密码': 'Contraseña',
  '密码修改成功': 'Contraseña cambiada correctamente',
  '密码验证失败': 'Verificación de contraseña fallida',
  '导入失败': 'Importación fallida',
  '导入成功': 'Importación exitosa',
  '导出': 'Exportar',
  '导出Excel': 'Exportar Excel',
  '导出PDF': 'Exportar PDF',
  '导出成功': 'Exportación exitosa',
  '展开菜单': 'Expandir menú',
  '履约': 'Cumplir',
  '履约单': 'Cumplimientos',
  '履约状态': 'Estado de cumplimiento',
  '履约管理': 'Cumplimiento',
  '工作日期': 'Fecha de trabajo',
  '工作流定义': 'Flujos de trabajo',
  '工作站': 'Estación de trabajo',
  '工作站ID': 'ID de estación de trabajo',
  '工单ID': 'ID de orden de trabajo',
  '工单编码': 'Código de orden de trabajo',
  '工序号': 'Sec.',
  '工时': 'Hoja de horas',
  '工时(小时)': 'Horas',
  '工时记录': 'Hojas de horas',
  '工艺路线': 'Ruta',
  '已付金额': 'Monto pagado',
  '已入库': 'Recibido',
  '已关闭': 'Cerrado',
  '已出库': 'Emitido',
  '已分配': 'Asignado',
  '已发放': 'Pagado',
  '已发货': 'Enviado',
  '已取件': 'Recogido',
  '已取消': 'Cancelado',
  '已失效': 'Expirado',
  '已完成': 'Completado',
  '已审批': 'Aprobado',
  '已审核': 'Revisado',
  '已打包': 'Empaquetado',
  '已打款': 'Pagado',
  '已批准': 'Aprobado',
  '已报价': 'Cotizado',
  '已拒绝': 'Rechazado',
  '已拣货': 'Surtido',
  '已撤回': 'Retirado',
  '已支付': 'Pagado',
  '已收货': 'Recibido',
  '已收金额': 'Monto recibido',
  '已核销': 'Liquidado',
  '已点击 {count}/{total}': 'Clics {count}/{total}',
  '已签收': 'Firmado',
  '已终止': 'Terminado',
  '已结算': 'Liquidado',
  '已转订单': 'Convertido a pedido',
  '已退回': 'Devuelto',
  '已退款': 'Reembolsado',
  '已送达': 'Entregado',
  '已通过': 'Aprobado',
  '已驳回': 'Rechazado',
  '币种': 'Moneda',
  '币种列表中的数字ID，如 61000000000000002=USD': 'ID numérico de la lista de monedas, p. ej. 61000000000000002=USD',
  '布局配置': 'Configuración de diseño',
  '年': 'Año',
  '年份': 'Año',
  '年假': 'Vacaciones anuales',
  '年度': 'Año',
  '序列号': 'Número de serie',
  '库位': 'Ubicación',
  '库位管理': 'Gestión de ubicaciones',
  '库区': 'Zona',
  '库区管理': 'Zonas',
  '库存': 'Inventario',
  '库存不足': 'Stock insuficiente',
  '库存总值': 'Valor del inventario',
  '库存数量': 'Cantidad en stock',
  '库存流水': 'Movimientos de stock',
  '库存调拨': 'Transferencia de stock',
  '库存预警': 'Alertas de stock',
  '应付': 'Por pagar',
  '应付账龄': 'Antigüedad de cuentas por pagar',
  '应付金额': 'Monto por pagar',
  '应发工资': 'Salario bruto',
  '应收': 'Por cobrar',
  '应收应付': 'CxC/CxP',
  '应收账龄': 'Antigüedad de cuentas por cobrar',
  '应收金额': 'Monto por cobrar',
  '应纳税所得额': 'Ingreso gravable',
  '开始日期': 'Fecha de inicio',
  '开始时间': 'Hora de inicio',
  '开始维修': 'Iniciar reparación',
  '开户银行': 'Nombre del banco',
  '异常': 'Excepción',
  '当前状态不允许此操作': 'Operación no permitida en el estado actual',
  '当前状态无可流转的目标状态': 'No hay estado destino disponible para el estado actual',
  '当前节点': 'Nodo actual',
  '往来单位': 'Contraparte',
  '往来单位与所选类型不匹配，请重新选择': 'La contraparte no coincide con el tipo seleccionado, vuelva a seleccionar',
  '待入库': 'Recepción pendiente',
  '待出库': 'Emisión pendiente',
  '待发货': 'Listo para enviar',
  '待处理': 'Pendiente',
  '待审批': 'Pendiente',
  '待审核': 'Revisión pendiente',
  '待打包': 'Empaque pendiente',
  '待拣货': 'Recogida pendiente',
  '待支付': 'Pago pendiente',
  '微信': 'WeChat',
  '必填（后端校验）': 'Obligatorio (validado por el servidor)',
  '必填（后端校验），如 OM+时间戳': 'Obligatorio (validado por el servidor), p. ej. OM+marca de tiempo',
  '总览': 'Resumen',
  '总账/明细账': 'Mayor general / detalle',
  '总金额': 'Importe total',
  '恢复成功': 'Restaurado correctamente',
  '成功': 'Éxito',
  '成本/利润中心': 'Centros de coste / beneficio',
  '成本中心': 'Centro de coste',
  '成本价': 'Coste unitario',
  '我的审批': 'Mis aprobaciones',
  '截止重量(kg)': 'Peso hasta (kg)',
  '所有者权益': 'Patrimonio neto',
  '手机号': 'Teléfono',
  '打包中': 'Empaque',
  '打包任务': 'Tarea de empaque',
  '打包单': 'Tarea de empaque',
  '打包管理': 'Empaque',
  '扣款': 'Deducciones',
  '执行': 'Ejecutar',
  '执行中': 'Activo',
  '执行合并': 'Ejecutar consolidación',
  '执行失败：{error}': 'Error de ejecución: {error}',
  '批准': 'Aprobar',
  '批准时间': 'Aprobado el',
  '批准请假': 'Aprobar permiso',
  '批次号': 'N.º de lote',
  '批量删除失败: {error}': 'Error al eliminar lote: {error}',
  '批量删除完成': 'Usuarios seleccionados eliminados',
  '批量删除成功': 'Eliminación por lotes exitosa',
  '批量启用': 'Habilitar seleccionados',
  '批量启用完成': 'Usuarios seleccionados habilitados',
  '批量拣货': 'Seleccionar por lote',
  '批量操作成功': 'Operación por lotes exitosa',
  '批量禁用': 'Deshabilitar seleccionados',
  '批量禁用完成': 'Usuarios seleccionados deshabilitados',
  '承运商': 'Transportista',
  '承运商服务': 'Servicio de transporte',
  '承运服务': 'Servicio de transporte',
  '投资活动净额': 'Flujo de efectivo neto de inversión',
  '投资活动流入': 'Entradas de inversión',
  '投资活动流出': 'Salidas de inversión',
  '折旧年份': 'Año de depreciación',
  '折旧月份': 'Mes de depreciación',
  '折旧计提成功': 'Depreciación registrada',
  '报价单': 'Cotización',
  '报价单号': 'N.º de cotización',
  '报价时间': 'Cotizado el',
  '报价转合同': 'Cotización a contrato',
  '报价金额': 'Importe de cotización',
  '报告人': 'Informante',
  '报表': 'Informe',
  '报表名称': 'Nombre del informe',
  '报表管理': 'Informes',
  '报表类型': 'Tipo de informe',
  '报表结果：{name}': 'Resultado del informe: {name}',
  '报表说明: {note}': 'Nota del informe: {note}',
  '抽样方案': 'Plan de muestreo',
  '拒绝': 'Rechazar',
  '拣货中': 'Recogida',
  '拣货任务': 'Tarea de recogida',
  '拣货单': 'Tarea de recogida',
  '拣货管理': 'Selección',
  '指标名称': 'Nombre de métrica',
  '指标类型': 'Tipo de métrica',
  '指标键名': 'Clave de métrica',
  '指派': 'Asignar',
  '指派人': 'Asignado',
  '指派工单': 'Asignar ticket',
  '按单拣货': 'Seleccionar por pedido',
  '换一张': 'Actualizar',
  '换货': 'Intercambio',
  '排序': 'Orden de clasificación',
  '接收人': 'Destinatario',
  '描述': 'Descripción',
  '提交': 'Enviar',
  '提交中...': 'Enviando...',
  '提交人': 'Enviado por',
  '提交失败：{error}': 'Error al enviar: {error}',
  '提交审批': 'Enviar para aprobación',
  '提交审批：{name}': 'Enviar para aprobación: {name}',
  '提交成功': 'Enviado correctamente',
  '提交时间': 'Enviado el',
  '提示': 'Información',
  '搜索': 'Buscar',
  '搜索...': 'Buscar...',
  '搜索商品名称/编码/批次号': 'Buscar nombre, código o lote del producto',
  '搜索用户名/姓名': 'Buscar nombre de usuario/nombre',
  '摘要': 'Resumen',
  '撤回': 'Retirar',
  '撤回失败: {error}': 'Error al retirar: {error}',
  '撤回审批': 'Aprobación de retiro',
  '操作': 'Acciones',
  '操作失败': 'La operación falló',
  '操作失败，请重试': 'La operación falló, inténtalo de nuevo',
  '操作失败：{error}': 'La operación falló: {error}',
  '操作成功': 'Operación exitosa',
  '操作日志': 'Registro de operaciones',
  '操作筛选': 'Filtrar por acción',
  '操作者': 'Operador',
  '支付宝': 'Alipay',
  '支付状态': 'Estado del pago',
  '收入结转': 'Arrastre de ingresos',
  '收款单': 'Recibo',
  '收款单ID': 'ID de recibo',
  '收款单号': 'N.º de recibo',
  '收款时间': 'Recibido en',
  '收款管理': 'Recibos',
  '收货仓库ID': 'ID de almacén de recepción',
  '收货单ID': 'ID de recepción',
  '收货单号': 'N.º de recepción',
  '收货时间': 'Recibido en',
  '收货管理': 'Recepción',
  '收起菜单': 'Contraer menú',
  '故障描述': 'Descripción de falla',
  '敏感操作需要输入密码确认': 'Se requiere confirmación de contraseña para operaciones sensibles',
  '数据趋势（近30天）': 'Tendencia de datos (últimos 30 días)',
  '数据集': 'Conjuntos de datos',
  '数据集ID': 'ID de conjunto de datos',
  '数据集ID: {value}': 'ID de conjunto de datos: {value}',
  '数据集名称': 'Nombre del conjunto de datos',
  '数量': 'Cantidad',
  '文档列表': 'Lista de documentos',
  '文档标题': 'Título del documento',
  '文档编码': 'Código de documento',
  '新增': 'Agregar',
  '新增OMS订单': 'Agregar orden OMS',
  '新增图表': 'Agregar gráfico',
  '新增报价单': 'Agregar cotización',
  '新增汇率': 'Agregar tipo de cambio',
  '新增用户': 'Agregar usuario',
  '新增结算': 'Agregar liquidación',
  '新增薪资记录': 'Agregar registro de nómina',
  '新增薪资项': 'Agregar ítem de salario',
  '新增角色': 'Agregar rol',
  '新增记账凭证': 'Agregar comprobante',
  '新增请假': 'Agregar permiso',
  '新增账户': 'Agregar cuenta',
  '新增跟进': 'Agregar seguimiento',
  '新增跟进记录': 'Agregar seguimiento',
  '新增配置': 'Agregar configuración',
  '新增采购申请': 'Agregar solicitud de compra',
  '新增采购结算（付款核销）': 'Agregar liquidación de compra (cancelación de pago)',
  '新增采购订单': 'Agregar orden de compra',
  '新增银行账户': 'Agregar cuenta bancaria',
  '新增销售结算（收款核销）': 'Agregar liquidación de venta (cancelación de recibo)',
  '新增销售订单': 'Agregar pedido de venta',
  '新增阶段': 'Agregar etapa',
  '新密码 (6-32位)': 'Nueva contraseña (6-32 caracteres)',
  '新密码（留空不修改）': 'Nueva contraseña (dejar en blanco para no cambiarla)',
  '新建指标': 'Nueva métrica',
  '方向': 'Dirección',
  '方式': 'Método',
  '方法': 'Método',
  '无效的ID': 'ID inválido',
  '无权限访问': 'Acceso denegado',
  '日期': 'Fecha',
  '旧密码': 'Contraseña anterior',
  '时间': 'Hora',
  '明细-借方金额': 'Débito del artículo',
  '明细-摘要': 'Resumen del artículo',
  '明细-科目ID': 'ID de cuenta del artículo',
  '明细-贷方金额': 'Crédito del artículo',
  '明细分类账': 'Libros auxiliares',
  '是': 'Sí',
  '是否计税(0/1)': 'Gravable (0/1)',
  '暂无可选用户': 'No hay usuarios asignables',
  '暂无图表，点击「新增图表」创建': 'Aún no hay gráficos; haz clic en "Agregar gráfico" para crear uno',
  '暂无数据': 'Sin datos',
  '暂无明细数据': 'Sin datos de detalle',
  '暂无角色': 'Aún no hay roles',
  '更新失败: {error}': 'Error al actualizar: {error}',
  '更新成功': 'Actualizado correctamente',
  '最低': 'Más bajo',
  '最低库存': 'Stock mínimo',
  '最后登录': 'Último inicio de sesión',
  '最近操作': 'Operaciones recientes',
  '最高': 'Más alto',
  '最高库存': 'Stock máximo',
  '月': 'Mes',
  '月份': 'Mes',
  '服务器内部错误': 'Error interno del servidor',
  '服务工单': 'Ticket de servicio',
  '期初借方': 'Débito inicial',
  '期初现金': 'Efectivo inicial',
  '期初贷方': 'Crédito inicial',
  '期末借方': 'Débito de cierre',
  '期末现金': 'Efectivo final',
  '期末结转': 'Cierre de fin de período',
  '期末贷方': 'Crédito de cierre',
  '期间': 'Período',
  '期间 YYYY-MM': 'Período AAAA-MM',
  '期间 YYYY-MM(可选)': 'Período AAAA-MM (opcional)',
  '期间值': 'Valor del período',
  '期间类型': 'Tipo de período',
  '未分配': 'Sin asignar',
  '未发放': 'No pagado',
  '未填写则留空': 'Dejar en blanco para no cambiar',
  '未授权访问': 'No autorizado',
  '未核销': 'No liquidado',
  '未知': 'Desconocido',
  '未结算': 'No liquidado',
  '本位币': 'Moneda base',
  '本年利润': 'Beneficio del ejercicio',
  '本期借方': 'Débito actual',
  '本期贷方': 'Crédito actual',
  '权限': 'Permiso',
  '权限分配:': 'Permisos:',
  '条码': 'Código de barras',
  '来料检验(IQC)': 'Inspección de entrada (IQC)',
  '来源': 'Origen',
  '来源类型': 'Tipo de origen',
  '来源记录ID': 'ID de origen',
  '查看单据': 'Ver documento',
  '查询': 'Consulta',
  '查询SQL': 'Consulta SQL',
  '查询中...': 'Consultando...',
  '查询成功，暂无数据行': 'Consulta exitosa, sin filas de resultados',
  '标准名称': 'Nombre estándar',
  '标准编码': 'Código estándar',
  '标签': 'Etiquetas',
  '标记全部已读': 'Marcar todo como leído',
  '标识': 'Slug',
  '标识: {slug} | 用户数: {count} | {desc}': 'Slug: {slug} | Usuarios: {count} | {desc}',
  '标题': 'Título',
  '核销金额': 'Importe de baja',
  '根本原因': 'Causa raíz',
  '格式 YYYY-MM-DD': 'Formato YYYY-MM-DD',
  '格式 YYYY-MM-DD HH:mm:ss': 'Formato YYYY-MM-DD HH:mm:ss',
  '格式 YYYY-MM-DD HH:mm:ss，可留空': 'Formato YYYY-MM-DD HH:mm:ss, opcional',
  '检验/合格/不合格': 'Inspeccionado/Aprobado/Rechazado',
  '检验单号': 'N.º de inspección',
  '检验员': 'Inspector',
  '检验数量': 'Cant. inspeccionada',
  '检验标准': 'Normas de inspección',
  '检验标准ID': 'ID de norma de inspección',
  '检验类型': 'Tipo de inspección',
  '检验结果': 'Resultado de inspección',
  '检验规格': 'Especificación de inspección',
  '模块': 'Módulo',
  '模板': 'Plantilla',
  '模板ID': 'ID de plantilla',
  '正常': 'Normal',
  '每公斤单价': 'Tarifa por kg',
  '每周': 'Semanal',
  '每天': 'Diario',
  '每月': 'Mensual',
  '汇兑损益': 'Ganancia/Pérdida cambiaria',
  '汇率': 'Tipo de cambio',
  '汇率管理': 'Tipos de cambio',
  '没有需要保存的修改': 'No hay cambios que guardar',
  '波次拣货': 'Recogida por oleada',
  '波次管理': 'Oleada',
  '派送中': 'En reparto',
  '流动比率': 'Razón corriente',
  '流动负债': 'Pasivo corriente',
  '流动资产': 'Activo corriente',
  '流转': 'Transición',
  '浮动': 'Variable',
  '渠道': 'Canal',
  '渠道店铺名称': 'Nombre de tienda del canal',
  '渠道管理': 'Canales',
  '渠道订单号': 'N.º de pedido de canal',
  '热销商品 TOP 5': 'Top 5 productos',
  '燃油附加费(%)': 'Recargo por combustible (%)',
  '版本': 'Versión',
  '物流轨迹': 'Seguimiento',
  '状态': 'Estado',
  '状态流转': 'Transición de estado',
  '状态流转成功': 'Estado cambiado',
  '现金': 'Efectivo',
  '现金日记账': 'Diarios de efectivo',
  '现金流量表': 'Estado de flujo de efectivo',
  '生产制造': 'Fabricación',
  '生产工单': 'Orden de producción',
  '生产工单ID': 'ID de orden de trabajo',
  '生成报表': 'Generar informe',
  '生成时间': 'Generado el',
  '生成时间: {value}': 'Generado el: {value}',
  '生效日期': 'Fecha de vigencia',
  '用户': 'Usuario',
  '用户ID': 'ID de usuario',
  '用户创建成功': 'Usuario creado',
  '用户名': 'Nombre de usuario',
  '用户名或密码错误': 'Nombre de usuario o contraseña incorrectos',
  '用户更新成功': 'Usuario actualizado',
  '用户状态分布': 'Distribución de estados de usuario',
  '用户管理': 'Usuarios',
  '申请人ID': 'ID del solicitante',
  '申请单号': 'N.º de solicitud',
  '申请部门': 'Departamento',
  '电话': 'Teléfono',
  '留空为0': 'Dejar en blanco para 0',
  '留空自动生成 CT+时间戳': 'Dejar en blanco para autogenerar CT+marca de tiempo',
  '留空自动生成 PA+时间戳': 'Dejar en blanco para autogenerar PA+marca de tiempo',
  '留空自动生成 PAY+时间戳': 'Dejar en blanco para autogenerar PAY+marca de tiempo',
  '留空自动生成 PO+时间戳': 'Dejar en blanco para autogenerar PO+marca de tiempo',
  '留空自动生成 PRN+时间戳': 'Auto PRN+marca de tiempo cuando esté en blanco',
  '留空自动生成 QT+时间戳': 'Dejar en blanco para autogenerar QT+marca de tiempo',
  '留空自动生成 RCV+时间戳': 'Dejar en blanco para autogenerar RCV+marca de tiempo',
  '留空自动生成 SO+时间戳': 'Dejar en blanco para autogenerar SO+marca de tiempo',
  '留空自动生成 SRN+时间戳': 'Auto SRN+marca de tiempo cuando esté en blanco',
  '留空自动生成 VCH+时间戳': 'Dejar en blanco para generar automáticamente VCH+marca de tiempo',
  '留空默认 合同-报价单号': 'Dejar en blanco para usar por defecto el N.º de cotización de contrato',
  '病假': 'Licencia por enfermedad',
  '登 录': 'Iniciar sesión',
  '登出成功': 'Sesión cerrada correctamente',
  '登录失败': 'Error al iniciar sesión',
  '登录成功': 'Inicio de sesión correcto',
  '登录状态已失效，请重新登录': 'Sesión expirada, por favor inicie sesión de nuevo',
  '盘点': 'Inventario',
  '盘点任务': 'Inventarios',
  '目标币ID': 'ID de moneda destino',
  '目标状态': 'Estado destino',
  '目的区域': 'Zona de destino',
  '目的国家': 'País de destino',
  '看板名称': 'Nombre del panel',
  '真实姓名': 'Nombre real',
  '确定': 'Aceptar',
  '确定执行「{action}」？': '¿Confirmar “{action}”?',
  '确定要删除「{name}」吗？': '¿Estás seguro de que quieres eliminar "{name}"?',
  '确定要删除图表「{name}」吗？': '¿Estás seguro de que quieres eliminar el gráfico "{name}"?',
  '确定要删除用户「{name}」吗？': '¿Estás seguro de que quieres eliminar el usuario "{name}"?',
  '确定要删除角色「{name}」吗？': '¿Estás seguro de que quieres eliminar el rol "{name}"?',
  '确定要删除该汇率记录吗？': '¿Estás seguro de que quieres eliminar este tipo de cambio?',
  '确定要删除该薪资记录吗？': '¿Estás seguro de que quieres eliminar este registro de nómina?',
  '确定要删除该请假记录吗？': '¿Estás seguro de que quieres eliminar este registro de licencia?',
  '确定要删除该采购结算记录吗？': '¿Estás seguro de que quieres eliminar este registro de liquidación de compra?',
  '确定要删除该销售结算记录吗？': '¿Estás seguro de que quieres eliminar este registro de liquidación de venta?',
  '确定要删除选中的 {count} 个用户吗？': '¿Eliminar los {count} usuarios seleccionados?',
  '确定要删除配置「{key}」吗？': '¿Estás seguro de que quieres eliminar la configuración "{key}"?',
  '确定要删除银行账户「{name}」吗？': '¿Estás seguro de que quieres eliminar la cuenta bancaria "{name}"?',
  '确定要将工单「{code}」流转为「{status}」吗？': '¿Mover la orden de trabajo "{code}" a "{status}"?',
  '确定要撤回该审批吗？': '¿Retirar esta solicitud de aprobación?',
  '确定要退出登录吗？': '¿Estás seguro de que quieres cerrar sesión?',
  '确定退出': 'Confirmar',
  '确认': 'Confirmar',
  '确认删除': 'Confirmar eliminación',
  '确认发放': 'Confirmar pago',
  '确认将「{period}」的薪资标记为已发放吗？': '¿Marcar el salario de "{period}" como pagado?',
  '确认批准该请假申请吗？': '¿Aprobar esta solicitud de licencia?',
  '确认批量删除': 'Confirmar eliminación por lotes',
  '确认收货': 'Confirmar recepción',
  '确认新密码': 'Confirmar nueva contraseña',
  '确认解决': 'Confirmar resolución',
  '确认计提': 'Confirmar',
  '确认退出': 'Confirmar cierre de sesión',
  '确认驳回该请假申请吗？': '¿Rechazar esta solicitud de permiso?',
  '社保(个人)': 'Seguro Social (empleado)',
  '禁用': 'Deshabilitar',
  '科目ID': 'ID de cuenta',
  '科目余额': 'Saldos de cuentas',
  '税务管理': 'Impuestos',
  '税率': 'Tasa de impuesto',
  '第 {page} 页 / 共 {pages} 页 ({total} 条)': 'Página {page} de {pages} ({total} registros)',
  '等级': 'Nivel',
  '筹资活动净额': 'Flujo de efectivo neto de financiamiento',
  '筹资活动流入': 'Entradas de financiamiento',
  '筹资活动流出': 'Salidas de financiamiento',
  '管理后台': 'Consola de administración',
  '管理员': 'Administrador',
  '类型': 'Tipo',
  '类型(0=固定 1=浮动)': 'Tipo (0=fijo 1=variable)',
  '类型: {type}': 'Tipo: {type}',
  '系统': 'Sistema',
  '系统管理': 'Sistema',
  '系统配置': 'Configuración del sistema',
  '纠正措施': 'Acción correctiva',
  '经营': 'Negocio',
  '经营活动净额': 'Flujo de efectivo neto de operación',
  '经营活动流入': 'Entradas de operación',
  '经营活动流出': 'Salidas de operación',
  '结束日期': 'Fecha de finalización',
  '结束时间': 'Hora de finalización',
  '结果': 'Resultado',
  '结果: {value}': 'Resultado: {value}',
  '结果行数: {value}': 'Filas de resultado: {value}',
  '结算': 'Liquidar',
  '结算时间': 'Liquidado en',
  '结算状态': 'Estado de liquidación',
  '结转状态': 'Estado de cierre',
  '绩效工资': 'Pago por desempeño',
  '维修': 'Reparación',
  '维修人': 'Reparador',
  '维修工单': 'Órdenes de reparación',
  '维修类型': 'Tipo de reparación',
  '维修费用': 'Costo de reparación',
  '编号': 'N.º',
  '编码': 'Código',
  '编辑': 'Editar',
  '编辑OMS订单': 'Editar pedido OMS',
  '编辑图表': 'Editar gráfico',
  '编辑报价单': 'Editar cotización',
  '编辑收货单（仅备注）': 'Editar registro de recepción (solo comentario)',
  '编辑汇率': 'Editar tipo de cambio',
  '编辑用户': 'Editar usuario',
  '编辑薪资': 'Editar registro de nómina',
  '编辑薪资项': 'Editar concepto salarial',
  '编辑角色': 'Editar rol',
  '编辑记账凭证': 'Editar comprobante',
  '编辑请假': 'Editar permiso',
  '编辑跟进记录': 'Editar seguimiento',
  '编辑配置': 'Editar configuración',
  '编辑采购申请': 'Editar solicitud de compra',
  '编辑采购结算': 'Editar liquidación de compra',
  '编辑采购订单': 'Editar orden de compra',
  '编辑银行账户': 'Editar cuenta bancaria',
  '编辑销售结算': 'Editar liquidación de venta',
  '编辑销售订单': 'Editar orden de venta',
  '编辑阶段': 'Editar etapa',
  '缺陷数量': 'Cantidad de defectos',
  '缺陷类型': 'Tipo de defecto',
  '网络连接失败，请检查网络': 'No se pudo conectar a la red, verifique su red',
  '网络错误，请检查连接': 'Error de red, verifique su conexión',
  '考勤': 'Asistencia',
  '考勤管理': 'Asistencia',
  '职位': 'Cargo',
  '职位管理': 'Cargos',
  '联系人': 'Contacto',
  '草稿': 'Borrador',
  '营业成本': 'Costo operativo',
  '营业收入': 'Ingresos operativos',
  '营销活动': 'Campaña',
  '薪资': 'Salario',
  '薪资发放': 'Pagar salarios',
  '薪资已发放': 'Salario marcado como pagado',
  '薪资年度': 'Año de salario',
  '薪资月份': 'Mes de salario',
  '薪资管理': 'Nómina',
  '薪资试算': 'Cálculo de salario',
  '薪资项配置': 'Elementos de nómina',
  '行数': 'Filas',
  '规格': 'Espec.',
  '规格名称': 'Nombre de especificación',
  '规格型号': 'Modelo/Espec.',
  '角色': 'Rol',
  '角色创建成功': 'Rol creado',
  '角色删除成功': 'Rol eliminado',
  '角色更新成功': 'Rol actualizado',
  '角色管理': 'Roles',
  '解决': 'Resolver',
  '解决工单': 'Resolver ticket',
  '解决说明': 'Notas de resolución',
  '计划名称': 'Nombre del plan',
  '计划生产数量': 'Cantidad planificada',
  '计提折旧': 'Registrar depreciación',
  '计税': 'Gravable',
  '计算中...': 'Calculando...',
  '计算比率': 'Calcular ratios',
  '计算薪资': 'Calcular salario',
  '订单': 'Pedido',
  '订单名称': 'Nombre del pedido',
  '订单总金额': 'Importe total del pedido',
  '订单状态分布': 'Distribución del estado de pedidos',
  '订单管理': 'Gestión de pedidos',
  '订单编号': 'Nº de pedido',
  '订单编码': 'Código de pedido',
  '记录不存在': 'Registro no encontrado',
  '记录已存在': 'El registro ya existe',
  '记账凭证': 'Comprobante',
  '设备ID': 'ID de equipo',
  '设备分类': 'Categoría de equipo',
  '设备台账': 'Libro de equipos',
  '设备名称': 'Nombre del equipo',
  '设备编码': 'Código del equipo',
  '试算平衡表': 'Balance de comprobación',
  '试算结果': 'Resultado del cálculo',
  '详情': 'Detalles',
  '说明': 'Descripción',
  '请假': 'Salir',
  '请假原因': 'Motivo',
  '请假天数': 'Días de permiso',
  '请假日期': 'Período de permiso',
  '请假管理': 'Licencia',
  '请假类型': 'Tipo de permiso',
  '请先选择用户': 'Seleccione usuarios primero',
  '请加载验证码': 'Cargue el captcha',
  '请按顺序点击图中文字: {text}': 'Haga clic en los caracteres de la imagen en orden: {text}',
  '请按顺序点击图中文字『{text}』': 'Haga clic en el carácter \\\'{text}\\\' en orden',
  '请求失败': 'Solicitud fallida',
  '请求超时，请稍后重试': 'Tiempo de espera agotado, vuelva a intentarlo más tarde',
  '请求过于频繁，请稍后重试': 'Demasiadas solicitudes, inténtelo de nuevo más tarde',
  '请至少填写一行分配明细': 'Agregue al menos una línea de asignación',
  '请输入{label}': 'Ingrese {label}',
  '请输入密码': 'Ingrese su contraseña',
  '请输入用户名和密码': 'Ingrese usuario y contraseña',
  '请输入科目ID（account_subject_id 必填）': 'Ingrese el ID de cuenta (se requiere account_subject_id)',
  '请选择目标状态': 'Seleccione un estado objetivo',
  '调休': 'Permiso compensatorio',
  '负债总计': 'Total de pasivos',
  '负责人': 'Asignado',
  '财务': 'Finanzas',
  '财务比率': 'Razones financieras',
  '账号已被锁定': 'La cuenta está bloqueada',
  '账户余额': 'Saldo de la cuenta',
  '账户名称': 'Nombre de la cuenta',
  '购买日期': 'Fecha de compra',
  '贷': 'Crédito',
  '贷方合计': 'Total de créditos',
  '费用': 'Gasto',
  '费用合计': 'Total de gastos',
  '费用报销': 'Gasto',
  '费用结转': 'Arrastre de gastos',
  '资产总计': 'Activos totales',
  '资产收益率': 'Rentabilidad sobre activos',
  '资产负债率': 'Ratio de deuda sobre activos',
  '资产负债表': 'Balance general',
  '资产负债表 JSON *': 'Balance general JSON *',
  '起始区域': 'Zona de origen',
  '起始国家': 'País de origen',
  '起始重量(kg)': 'Peso desde (kg)',
  '起步价': 'Tarifa base',
  '跟进主题': 'Asunto de seguimiento',
  '跟进内容': 'Contenido de seguimiento',
  '跟进记录': 'Seguimiento',
  '路径': 'Ruta',
  '路径筛选': 'Filtrar por ruta',
  '转合同': 'Convertir en contrato',
  '输入关键词搜索': 'Introduzca palabras clave para buscar',
  '输入密码确认': 'Introduzca la contraseña para confirmar',
  '过程检验(IPQC)': 'Inspección en proceso (IPQC)',
  '运单': 'Envío',
  '运单号': 'N.º de seguimiento',
  '运单管理': 'Envíos',
  '运费': 'Gastos de envío',
  '运费发票': 'Factura de flete',
  '运费费率': 'Tarifa de flete',
  '运输中': 'En tránsito',
  '运输管理': 'Gestión de transporte',
  '退出登录': 'Cerrar sesión',
  '退回时间': 'Devuelto el',
  '退回运费': 'Gastos de envío de devolución',
  '退换单号': 'N.º de RMA',
  '退换货': 'RMA',
  '退换货(RMA)': 'Devoluciones (RMA)',
  '退款': 'Reembolso',
  '退款金额': 'Importe del reembolso',
  '退货': 'Devolución',
  '退货单号': 'N.º de devolución',
  '退货时间': 'Devuelto el',
  '选填': 'Opcional',
  '通知': 'Notificación',
  '通知中心': 'Notificaciones',
  '通过': 'Aprobar',
  '通过审批': 'Aprobar',
  '邮箱': 'Correo electrónico',
  '部分发货': 'Enviado parcialmente',
  '部分收货': 'Recibido parcialmente',
  '部分核销': 'Liquidado parcialmente',
  '部分结算': 'Liquidado parcialmente',
  '部分退款': 'Reembolsado parcialmente',
  '部门': 'Departamento',
  '部门ID': 'ID de departamento',
  '部门管理': 'Departamentos',
  '配置JSON': 'Configuración JSON',
  '配送方式': 'Método de envío',
  '采购': 'Compra',
  '采购收货': 'Recepción de compra',
  '采购申请': 'Solicitud de compra',
  '采购申请ID': 'ID de solicitud de compra',
  '采购结算': 'Liquidación de compra',
  '采购订单': 'Orden de compra',
  '采购退货': 'Devolución de compra',
  '释放回公海': 'Liberar al grupo',
  '重试': 'Reintentar',
  '金额': 'Importe',
  '金额超出限额': 'El importe supera el límite',
  '银行': 'Banco',
  '银行账号': 'Número de cuenta bancaria',
  '银行账户': 'Cuentas bancarias',
  '销售': 'Ventas',
  '销售发货': 'Entrega de ventas',
  '销售报价': 'Cotizaciones de ventas',
  '销售渠道': 'Canal de ventas',
  '销售漏斗': 'Embudo de ventas',
  '销售结算': 'Liquidaciones de ventas',
  '销售订单': 'Pedido de venta',
  '销售趋势（近30天）': 'Tendencia de ventas (últimos 30 días)',
  '销售退货': 'Devolución de venta',
  '错误': 'Error',
  '键': 'Clave',
  '阶段': 'Etapa',
  '阶段名称': 'Nombre de la etapa',
  '需已审核的付款单 hashid': 'Hashid de un registro de pago aprobado',
  '需已审核的收款单 hashid': 'Hashid de un registro de cobro aprobado',
  '非流动负债': 'Pasivos no corrientes',
  '非流动资产': 'Activos no corrientes',
  '非空 JSON 数组，每项须含 ledger_id 或 company_id（后端数字ID，非 hashid）与 report_year（≥2000）、report_month（1-12）': 'Array JSON no vacío; cada elemento debe tener ledger_id o company_id (ID numérico del backend, no hashid), además de report_year (≥2000) y report_month (1-12)',
  '项目': 'Proyecto',
  '项目列表': 'Lista de proyectos',
  '预到货(ASN)': 'Recepciones previstas (ASN)',
  '预到货通知': 'ASN',
  '预算': 'Presupuesto',
  '预算管理': 'Presupuestos',
  '领取': 'Reclamación',
  '领取客户': 'Reclamar cliente',
  '频率': 'Frecuencia',
  '驳回': 'Rechazar',
  '驳回审批': 'Rechazar',
  '驳回请假': 'Rechazar ausencia',
  '验证码加载失败': 'No se pudo cargar el captcha',
  '验证码错误，请重试': 'Captcha incorrecto, inténtalo de nuevo',
  '旋转图片验证': 'Captcha de rotación de imagen',
  '滑块拼图验证': 'Captcha de rompecabezas deslizante',
  '尝试次数过多，请更换验证码': 'Demasiados intentos, actualiza el captcha',
  '转动图片使其摆正后提交': 'Gira la imagen hasta enderezarla y envía',
  '拖动拼图块使其对齐图中缺口': 'Arrastra la pieza del rompecabezas al hueco de la imagen',
  '高库存预警': 'Alertas de exceso de stock',
  '高度': 'Altura',
  '默认 0': 'Predeterminado 0',
  '默认金额': 'Importe predeterminado',
  '0 为顶级': '0 para el nivel superior',
  '3-50 字符': '3-50 caracteres',
  '6-32 字符': '6-32 caracteres',
  '6-32 位': '6-32 caracteres',
  'BI 看板': 'Panel de BI',
  'BOM 名称': 'Nombre de BOM',
  'BOM 管理': 'Gestión de BOM',
  'BOM 编码': 'Código de BOM',
  'CRM 报价单': 'Cotización CRM',
  'LOGO 地址': 'URL del logo',
  'MRP 计划': 'Plan MRP',
  'MRP 运算': 'Ejecutar MRP',
  'Offer 已发出': 'Oferta enviada',
  'Offer 薪资': 'Salario ofrecido',
  'erp开放平台': 'Abrir plataforma ERP',
  '上一页': 'Anterior',
  '上架': 'Publicar',
  '上架完成': 'Estantería finalizada',
  '上架已完成': 'Estantería completada',
  '上次登录': 'Último inicio de sesión',
  '上班打卡': 'Registrar entrada',
  '上级部门': 'Departamento padre',
  '下一页': 'Siguiente',
  '下架': 'Despublicar',
  '下班打卡': 'Registrar salida',
  '不合格': 'Rechazar',
  '不合格品单号': 'Número de NCR',
  '不通过': 'No aprobado',
  '两位小数，如 30000.00': 'Hasta 2 decimales, p. ej. 30000.00',
  '两位小数，如 5000.00': 'Hasta 2 decimales, p. ej. 5000.00',
  '两次输入的新密码不一致': 'Las dos contraseñas nuevas no coinciden',
  '中标转订单': 'Adjudicar a orden de compra',
  '产品': 'Producto',
  '人工': 'Mano de obra',
  '仓库名称': 'Nombre del almacén',
  '仓库管理': 'Gestión de almacenes',
  '仓库编码': 'Código de almacén',
  '付款方式': 'Método de pago',
  '付款日期': 'Fecha de pago',
  '付款账户': 'Cuenta de pago',
  '任务名称': 'Nombre de la tarea',
  '任职要求': 'Requisitos',
  '作废': 'Anular',
  '使用年限': 'Vida útil',
  '供应商名称': 'Nombre del proveedor',
  '供应商报价': 'Cotizaciones de proveedores',
  '供应商评估': 'Evaluación de proveedores',
  '保存失败': 'Error al guardar',
  '保存资料': 'Guardar perfil',
  '信用账期(天)': 'Plazo de crédito (días)',
  '信用额度': 'Límite de crédito',
  '修改失败': 'Error al actualizar',
  '候选人': 'Candidato',
  '停用': 'Suspender',
  '兑付': 'Efectivo',
  '入职日期': 'Fecha de incorporación',
  '全部通知已标记为已读': 'Todas las notificaciones marcadas como leídas',
  '共': 'de',
  '关联任务': 'Tarea vinculada',
  '内训': 'Interno',
  '再次输入新密码': 'Vuelve a introducir la nueva contraseña',
  '净值': 'Valor neto',
  '出库仓库': 'Almacén de salida',
  '出票人': 'Cajón',
  '出票日期': 'Fecha de salida',
  '出货检验': 'Inspección final OQC',
  '出货检验 OQC': 'Inspección final OQC',
  '分类名称': 'Nombre de categoría',
  '初筛通过': 'Cribado superado',
  '利润表': 'Estado de resultados',
  '到期': 'Vencido',
  '到期预警': 'Alertas de vencimiento',
  '制费': 'Gastos generales',
  '加工单价': 'Precio de procesamiento',
  '加载中…': 'Cargando...',
  '勾选': 'Comprobar',
  '协同管理': 'Colaboración',
  '原值': 'Valor original',
  '发出': 'Enviar',
  '发布': 'Publicar',
  '发布中': 'Publicado',
  '发料仓库': 'Almacén de salida',
  '发料单号': 'N.º de vale de salida',
  '发料单已审核': 'Vale de salida aprobado',
  '发料日期': 'Fecha de salida',
  '发生日期': 'Fecha de ocurrencia',
  '发票号': 'N.º de factura',
  '发票管理': 'Gestión de facturas',
  '发货': 'Enviar',
  '发货单': 'Albarán de entrega',
  '发货日期': 'Fecha de envío',
  '发起审批': 'Iniciar aprobación',
  '取消点检': 'Cancelar inspección',
  '合同号': 'N.º de contrato',
  '合同金额': 'Importe del contrato',
  '合格': 'Aprobar',
  '合格数': 'Cantidad aprobada',
  '合计': 'Total',
  '启停': 'Alternar',
  '启动': 'Iniciar',
  '启用日期': 'Fecha de entrada en servicio',
  '员工姓名': 'Nombre del empleado',
  '员工编码': 'Código de empleado',
  '周期类型': 'Tipo de período',
  '品牌名称': 'Nombre de la marca',
  '品牌描述': 'Descripción de la marca',
  '品项数': 'Líneas de detalle',
  '商品描述': 'Descripción',
  '商品管理': 'Gestión de productos',
  '商品资料': 'Maestro de productos',
  '商机名称': 'Nombre de la oportunidad',
  '回复': 'Responder',
  '回调地址': 'URL de callback',
  '图标': 'Icono',
  '图表组件': 'Widget de gráfico',
  '城市': 'Ciudad',
  '培训社保': 'Capacitación y seguridad social',
  '培训课程': 'Cursos de capacitación',
  '基本资料': 'Perfil básico',
  '处理中': 'Procesando',
  '备件管理': 'Repuestos',
  '外训': 'Externo',
  '多币种': 'Monedas',
  '多组织公司': 'Empresas',
  '如 admin、viewer': 'p. ej. admin, visor',
  '如 monthly': 'p. ej. mensual',
  '如 上海': 'p. ej. Shanghái',
  '如 人民币': 'p. ej. CNY',
  '委外产品': 'Producto subcontratado',
  '委外加工': 'Subcontratación',
  '委外发料': 'Salida de subcontratación',
  '委外收货': 'Recepción de subcontrato',
  '委外数量': 'Cant. subcontrato',
  '委外订单': 'Pedido de subcontrato',
  '字符串': 'Cadena',
  '季度': 'Trimestral',
  '学分': 'Créditos',
  '完工': 'Completar',
  '完工数': 'Cant. completada',
  '实发': 'Pago neto',
  '审批已发起': 'Aprobación iniciada',
  '审核': 'Aprobar',
  '客户名称': 'Nombre del cliente',
  '客户管理': 'Gestión de clientes',
  '密码已修改': 'Contraseña cambiada',
  '密钥已重置': 'Secreto restablecido',
  '小计': 'Subtotal',
  '工作站名称': 'Nombre de estación de trabajo',
  '工作站编码': 'Código de estación de trabajo',
  '工单分类': 'Categoría de ticket',
  '工单号': 'N.º de ticket',
  '工单已完工': 'Orden de trabajo completada',
  '工单已开工': 'Orden de trabajo iniciada',
  '工单已解决': 'Ticket resuelto',
  '工单标题': 'Título del ticket',
  '工序': 'Operación',
  '工序名称': 'Nombre de operación',
  '工序序号': 'Secuencia',
  '工序报工': 'Informe de trabajo',
  '工时数': 'Horas',
  '工资条': 'Nómina',
  '已作废': 'Anulado',
  '已入职': 'Incorporado',
  '已发 Offer': 'Oferta enviada',
  '已发出': 'Enviado',
  '已回复': 'Respondido',
  '已完成库存分配': 'Stock asignado',
  '已归档': 'Archivado',
  '已接受': 'Aceptado',
  '已提交': 'Enviado',
  '已撤销': 'Retirado',
  '已标记为已读': 'Marcado como leído',
  '已派单': 'Asignado',
  '已淘汰': 'Rechazado',
  '已生成合同': 'Contrato generado',
  '已生成履约单': 'Cumplimiento creado',
  '已生成采购订单': 'Orden de compra creada',
  '已生效': 'Vigente',
  '已用': 'Usado',
  '已结': 'Liquidado',
  '已认领': 'Reclamado',
  '已读': 'Leído',
  '已释放回公海': 'Liberado de nuevo al grupo',
  '币种名称': 'Nombre de moneda',
  '币种管理': 'Gestión de monedas',
  '币种编码': 'Código de moneda',
  '布尔': 'Booleano',
  '库位名称': 'Nombre de ubicación',
  '库位编码': 'Código de ubicación',
  '库区名称': 'Nombre de zona',
  '库区编码': 'Código de zona',
  '库存分配': 'Asignar stock',
  '库存管理': 'Gestión de inventario',
  '应发': 'Salario bruto',
  '应用名称': 'Nombre de aplicación',
  '应聘职位': 'Trabajo aplicado',
  '开工': 'Iniciar',
  '开户行': 'Banco',
  '开放应用': 'Aplicaciones OpenAPI',
  '开票': 'Emitir factura',
  '开票日期': 'Fecha de factura',
  '归档': 'Archivar',
  '归集日期': 'Fecha de contabilización',
  '当前密码': 'Contraseña actual',
  '录用 Offer': 'Carta de oferta',
  '往来方': 'Contraparte',
  '待定': 'Pendiente',
  '待开通': 'Provisión pendiente',
  '总账': 'Libro mayor',
  '成本': 'Costo',
  '成本归集': 'Entrada de costo',
  '成本类别': 'Categoría de costo',
  '所属仓库': 'Almacén',
  '所属应用': 'Aplicación',
  '所属模块': 'Módulo',
  '所属看板': 'Panel',
  '所属部门': 'Departamento',
  '所属项目': 'Proyecto',
  '手机': 'Teléfono',
  '打包完成': 'Empacado',
  '打包已完成': 'Empaque completado',
  '打卡成功': 'Registrado correctamente',
  '托收': 'Cobrar',
  '托收账户': 'Cuenta de recaudación',
  '执行报表': 'Ejecutar informe',
  '批次效期预警': 'Alertas de vencimiento de lote',
  '承兑人': 'Aceptante',
  '承兑汇票': 'Aceptación bancaria',
  '承运商名称': 'Nombre del transportista',
  '投递测试完成': 'Entrega de prueba completada',
  '折扣': 'Descuento',
  '折旧已计提': 'Depreciación contabilizada',
  '折旧方法': 'Método de depreciación',
  '报工员工': 'Empleado informante',
  '报工已审核': 'Informe de trabajo aprobado',
  '报工数量': 'Cantidad reportada',
  '报工日期': 'Fecha del informe',
  '报表已执行': 'Informe ejecutado',
  '报表模板': 'Plantilla de informe',
  '报销金额': 'Monto de reembolso',
  '抵扣': 'Deducir',
  '拒付': 'Rechazar',
  '招聘人数': 'Número de empleados',
  '招聘候选人': 'Candidatos',
  '招聘管理': 'Reclutamiento',
  '招聘职位': 'Ofertas de empleo',
  '招聘部门': 'Departamento de contratación',
  '招聘面试': 'Entrevistas',
  '拣货已确认': 'Picking confirmado',
  '拣货确认': 'Confirmar picking',
  '按钮': 'Botón',
  '提交数': 'Cant. enviada',
  '搜索通知内容': 'Buscar contenido de notificación',
  '搜索配置键': 'Buscar clave de configuración',
  '撤销': 'Retirar',
  '操作人': 'Operador',
  '支付': 'Pagar',
  '收料仓库': 'Almacén de recepción',
  '收料单号': 'N.º de recibo',
  '收料单已审核': 'Recibo aprobado',
  '收料数量': 'Cant. recibida',
  '收料日期': 'Fecha de recepción',
  '收款人': 'Beneficiario',
  '收款方式': 'Método de recibo',
  '收款日期': 'Fecha de recibo',
  '收款账户': 'Cuenta de recibo',
  '收款金额': 'Importe del recibo',
  '收票': 'Recibido',
  '收货单': 'Nota de recepción',
  '收货完成': 'Recepción realizada',
  '收货已完成': 'Recepción completada',
  '收货日期': 'Fecha de recibo',
  '数组': 'Array',
  '整数': 'Entero',
  '文档内容': 'Contenido',
  '文档分类': 'Categoría',
  '文档管理': 'Gestión de documentos',
  '新增成功': 'Creado',
  '新密码': 'Nueva contraseña',
  '新密码长度需为 6-32 位': 'La nueva contraseña debe tener entre 6 y 32 caracteres',
  '新简历': 'Nuevo currículum',
  '是否启用': 'Habilitado',
  '更新时间': 'Actualizado el',
  '最大库存阈值': 'Umbral máximo de stock',
  '最小库存阈值': 'Umbral mínimo de stock',
  '月度': 'Mensual',
  '服务名称': 'Nombre del servicio',
  '期望薪资': 'Salario esperado',
  '期间已结账': 'Período cerrado',
  '未开始': 'No iniciado',
  '未结': 'No liquidado',
  '未设置': 'No establecido',
  '未读': 'No leído',
  '权限名': 'Nombre del permiso',
  '权限管理': 'Gestión de permisos',
  '材料': 'Material',
  '条': 'registros',
  '来料检验': 'IQC',
  '来料检验 IQC': 'Inspección de entrada IQC',
  '来源币种': 'Moneda origen',
  '来源渠道': 'Origen',
  '标记已读': 'Marcar como leído',
  '模板名称': 'Nombre de plantilla',
  '模板已启用': 'Plantilla habilitada',
  '模板编码': 'Código de plantilla',
  '残值': 'Valor residual',
  '比价': 'Comparar',
  '汇率值': 'Tasa',
  '波次已释放': 'Ola liberada',
  '波次释放': 'Liberar ola',
  '活动名称': 'Nombre de campaña',
  '派单': 'Asignar',
  '测试投递': 'Entrega de prueba',
  '渠道名称': 'Nombre del canal',
  '漏斗阶段名称': 'Nombre de etapa',
  '点检任务': 'Tareas de inspección',
  '点检日期': 'Fecha de inspección',
  '父任务': 'Tarea padre',
  '父级 ID': 'ID padre',
  '状态已切换': 'Estado cambiado',
  '状态已更新': 'Estado actualizado',
  '生产领料': 'Salida de material',
  '用户数': 'Usuarios',
  '申请人': 'Solicitante',
  '界面语言': 'Idioma',
  '登录已过期，请重新登录': 'Sesión expirada, vuelva a iniciar sesión',
  '盘点任务名称': 'Nombre de inventario',
  '盘点单号': 'N.º de inventario',
  '目录': 'Directorio',
  '目标币种': 'Moneda destino',
  '目标类型': 'Tipo de objetivo',
  '直线法': 'Línea recta',
  '看板布局': 'Diseño del panel',
  '确认操作': 'Confirmar acción',
  '社保规则': 'Reglas de seguridad social',
  '票据号': 'N.º de factura',
  '票面金额': 'Valor nominal',
  '租户列表': 'Inquilinos',
  '租户已停用': 'Inquilino suspendido',
  '租户已启用': 'Inquilino reanudado',
  '租户管理': 'Gestión de inquilinos',
  '税号': 'N.º fiscal',
  '税率管理': 'Tasas de impuestos',
  '税额': 'Importe de impuesto',
  '第': 'Página',
  '签订日期': 'Fecha de firma',
  '算薪': 'Calcular nómina',
  '算薪完成': 'Nómina calculada',
  '纳税记录': 'Registros de impuestos',
  '线上': 'En línea',
  '组件名称': 'Nombre del widget',
  '组件类型': 'Tipo de widget',
  '结账': 'Cerrar período',
  '绩效模板': 'Plantillas de desempeño',
  '绩效考核': 'Evaluación de desempeño',
  '维修工单号': 'N.º de orden de reparación',
  '缴费基数上限': 'Techo base',
  '缴费基数下限': 'Suelo base',
  '考核批次已启动': 'Evaluación iniciada',
  '考核批次已归档': 'Evaluación archivada',
  '考核计划': 'Planes de evaluación',
  '考核评分': 'Puntuaciones de evaluación',
  '耗时(ms)': 'Transcurrido (ms)',
  '职位名称': 'Título del puesto',
  '职位已关闭': 'Puesto cerrado',
  '职位已发布': 'Puesto publicado',
  '职位编码': 'Código de puesto',
  '联系人名称': 'Nombre del contacto',
  '背书': 'Endosar',
  '自定义字段': 'Campos personalizados',
  '自定义报表': 'Informes personalizados',
  '获取面单': 'Obtener etiqueta',
  '菜单': 'Menú',
  '规则名称': 'Nombre de regla',
  '角色名': 'Nombre de rol',
  '角色权限': 'Roles',
  '计划年度': 'Año del plan',
  '计划数': 'Cant. planificada',
  '计划数量': 'Cantidad planificada',
  '计划日期': 'Fecha del plan',
  '计划月份': 'Mes del plan',
  '计划编码': 'Código del plan',
  '订单号': 'N.º de pedido',
  '订单履约': 'Cumplimiento de pedidos',
  '订单已取消': 'Pedido cancelado',
  '认领': 'Reclamación',
  '讲师': 'Docente',
  '设备': 'Equipo',
  '设备管理': 'Gestión de equipos',
  '询价单': 'RFQ',
  '询价单已关闭': 'RFQ cerrada',
  '请输入当前密码': 'Ingrese la contraseña actual',
  '请输入登录密码确认操作': 'Ingrese la contraseña de inicio de sesión para confirmar',
  '课时(小时)': 'Duración (horas)',
  '课程标题': 'Título del curso',
  '课程类型': 'Tipo de curso',
  '调出仓库': 'Desde almacén',
  '调拨单号': 'N.º de transferencia',
  '调拨日期': 'Fecha de transferencia',
  '财务管理': 'Gestión financiera',
  '账套期间': 'Períodos contables',
  '账户编码': 'Código de cuenta',
  '质量管理': 'Gestión de calidad',
  '购置日期': 'Fecha de compra',
  '购置金额': 'Monto de compra',
  '贴现': 'Descuento',
  '费用科目': 'Cuenta de gastos',
  '费用类型': 'Tipo de gasto',
  '资产名称': 'Nombre del activo',
  '资产类别': 'Categoría del activo',
  '资产编号': 'N.º de activo',
  '资产编码': 'Código de activo',
  '资料已保存': 'Perfil guardado',
  '赢单': 'Ganado',
  '跟进中': 'En seguimiento',
  '跟进人': 'Seguidor',
  '轮次': 'Ronda',
  '输单': 'Perdido',
  '过程检验': 'IPQC',
  '过程检验 IPQC': 'Inspección de proceso IPQC',
  '运单已发货': 'Envío enviado',
  '运算完成': 'Ejecución de MRP completada',
  '运费已支付': 'Flete pagado',
  '运费已确认': 'Flete confirmado',
  '运输服务': 'Servicios de transporte',
  '进行中': 'En progreso',
  '进项发票池': 'Grupo de facturas de entrada',
  '退换货 RMA': 'Devolución RMA',
  '退货仓库': 'Almacén de devoluciones',
  '退货入库': 'Recibir devolución',
  '退货金额': 'Importe de devolución',
  '部门名称': 'Nombre del departamento',
  '部门编码': 'Código del departamento',
  '配置键': 'Clave',
  '采购管理': 'Gestión de compras',
  '采购销售': 'Compras y ventas',
  '释放': 'Liberar',
  '重置密钥': 'Restablecer secreto',
  '销售管理': 'Gestión de ventas',
  '集团财务': 'Finanzas del grupo',
  '面单已生成': 'Etiqueta generada',
  '面试中': 'Entrevistando',
  '面试日期': 'Fecha de entrevista',
  '页': 'de',
  '项目名称': 'Nombre del proyecto',
  '项目成本': 'Costo del proyecto',
  '项目管理': 'Gestión de proyectos',
  '项目编号': 'Código del proyecto',
  '预到货 ASN': 'ASN',
  '预算名称': 'Nombre del presupuesto',
  '预算对比': 'Comparar presupuesto',
  '预算年度': 'Año presupuestario',
  '预算额': 'Importe presupuestado',
  '预计金额': 'Importe esperado',
  '领料单已审核': 'Emisión aprobada',
  '领料日期': 'Fecha de emisión',
  '验真': 'Verificar',
  '验证失败，请重试': 'La verificación falló, vuelve a intentarlo',
  '搜索菜单': 'Buscar menús',
  '关闭标签': 'Cerrar pestaña',
  '关闭其他标签': 'Cerrar otras pestañas',
  '关闭全部标签': 'Cerrar todas las pestañas',
  '关闭其他': 'Cerrar otras',
  '关闭全部': 'Cerrar todas',
  '页面不存在': 'Página no encontrada',
  '当前路由未注册': 'Ruta no registrada',
  '人机验证': 'Captcha',
  '点击文字验证': 'Haz clic en los caracteres',
  '验证码加载中…': 'Cargando captcha...',
  '暂无趋势数据': 'Aún no hay datos de tendencia',
  '账户状态分布': 'Estado de la cuenta',
  '最近操作日志': 'Registros recientes',
  '暂无日志': 'No hay registros',
  '近 30 天趋势': 'Tendencia de los últimos 30 días',
  '已完成人机验证，点击「登 录」继续': 'Captcha verificado. Haz clic en Iniciar sesión para continuar',
  '登录需先完成人机验证': 'Completa el captcha primero',
  '全部已读': 'Marcar todo como leído',
  '请选择': 'Seleccionar...',
  '条/页': 'registros/página',
  '较昨日': 'vs. ayer',
  '按顺序点击': 'Haz clic en orden',
  '请填写「{label}」': 'Por favor, completa {label}',
  '新增{name}': 'Nuevo {name}',
  '编辑{name}': 'Editar {name}',
  '确定执行「{act}」吗？': '¿Ejecutar {act}?',
  '确定删除「{name}」？该操作不可恢复。': '¿Eliminar {name}? Esto no se puede deshacer.',
  '请求失败（{code}）': 'La solicitud falló ({code})',
  '下载失败（{code}）': 'La descarga falló ({code})',
  'Open ERP · Web 控制台': 'Abrir ERP · Consola web',
  '业务模块': 'Módulos',
  '中英切换': 'Chino / Inglés',
  '第 {count} 个字位置不准，请再点一次': 'Vuelve a hacer clic en #{count}: el punto falló el objetivo',
  '仍未通过，请按顺序重新点击': 'Aún no coincide: vuelve a hacer clic en todos los caracteres en orden',
  '规格属性': 'Atributos de especificación',
  '费率(元/小时)': 'Tarifa (yuan/hora)',
  '订阅事件': 'Eventos suscritos',
  '0=全部': '0=Todos',
  '如 get.admin/user': 'p. ej. get.admin/user',
  '搜索用户/路径': 'Buscar usuario/ruta',
  '多个事件名用逗号或换行分隔；* 表示全部；仅允许字母、数字与 . _ -': 'Separa varios nombres de eventos con comas o saltos de línea; * significa todos; solo se permiten letras, dígitos y . _ -',
  '勾选父级即全选其下所有子项': 'Marcar un padre selecciona todos sus hijos',
  '父级': 'Padre',
  '点节点选父级；点已选节点取消（空 = 顶级）': 'Haz clic en un nodo para establecerlo como padre; haz clic en un nodo seleccionado para quitarlo (vacío = nivel superior)',
  'JSON 对象：属性名 → 值数组，如 {"颜色":["红","蓝"],"尺寸":["S","M","L"]}；留空 / {} 表示无属性': 'Objeto JSON: nombre del atributo → array de valores, p. ej. {"Color":["Rojo","Azul"],"Talla":["S","M","L"]}; deja vacío / {} para sin atributos',
};
