/*
 * Copyright (c) 2026 erik <erik@erik.xyz> — https://erik.xyz
 */

/**
 * 前端翻译词典：中文原文 → 英文。
 * 由后端 resource/translations（zh_CN/en）与 Flutter app_*.arb 合并生成，
 * 覆盖通用操作、模块名、导航与主要 UI 文案；缺词条时回退中文原文。
 * 新增文案在此手工补充即可（4 词条/行，保持文件紧凑）。
 */

/** 中文 → 英文 词典 */
export const zhEn: Record<string, string> = {
  ':attribute 不存在': 'The :attribute does not exist',
  ':attribute 不能为空': 'The :attribute field is required',
  ':attribute 不能大于 :max': 'The :attribute must not exceed :max',
  ':attribute 不能小于 :min': 'The :attribute must be at least :min',
  ':attribute 值无效': 'The :attribute value is invalid',
  ':attribute 已存在': 'The :attribute already exists',
  ':attribute 必须是字符串': 'The :attribute must be a string',
  ':attribute 必须是数字': 'The :attribute must be a number',
  ':attribute 必须是整数': 'The :attribute must be an integer',
  ':attribute 格式不正确': 'The :attribute format is invalid',
  BOM管理: 'BOM Management',
  'JSON 对象，含 current_assets、current_liabilities、total_liabilities、total_assets 字段，值为数字':
    'JSON object with numeric values for current_assets, current_liabilities, total_liabilities and total_assets',
  'JSON 对象，含 net_profit、revenue 字段，值为数字':
    'JSON object with numeric values for net_profit and revenue',
  MRP计划: 'MRP Planning',
  'OMS 订单': 'OMS Orders',
  OMS订单: 'OMS Order',
  Token已过期: 'Token expired',
  Token无效: 'Invalid token',
  X坐标: 'X Position',
  'YYYY-MM-DD，如 2026-09-05': 'YYYY-MM-DD, e.g. 2026-09-05',
  Y坐标: 'Y Position',
  erp开放管理后台: 'Open ERP Admin',
  erp管理后台: 'Open ERP Admin',
  '{field} 不是合法 JSON': '{field} is not valid JSON',
  '{field} 必须为 JSON 对象': '{field} must be a JSON object',
  '{field} 必须为 JSON 数组': '{field} must be a JSON array',
  '{page} / {pages} ({total}条)': '{page} / {pages} ({total})',
  '一个平台，管好全部业务': 'One platform for all your business',
  上传成功: 'Upload successful',
  上架管理: 'Putaway',
  上次保养日期: 'Last Maintenance Date',
  下单时间: 'Order Date',
  下次保养日期: 'Next Maintenance Date',
  下次日期: 'Next Date',
  不合格品: 'Nonconforming Products',
  不合格数量: 'Rejected Qty',
  不合格编号: 'Defect No.',
  两次密码不一致: 'Passwords do not match',
  严重程度: 'Severity',
  个人中心: 'Profile',
  个人信息更新成功: 'Profile updated successfully',
  个人所得税: 'Individual Income Tax',
  个税: 'Income Tax',
  主题: 'Subject',
  买家备注: 'Buyer Note',
  事假: 'Personal Leave',
  产假: 'Maternity Leave',
  人力资源: 'HR',
  从供应商列表页获取数字ID: 'Numeric ID from the supplier list page',
  从员工列表页获取数字ID: 'Numeric ID from the employee list page',
  从客户列表页获取数字ID: 'Numeric ID from the customer list page',
  '从科目列表获取数字ID，填了则按明细创建':
    'Numeric ID from the account list; when set, the voucher is created with line items',
  从销售订单列表页获取数字ID: 'Numeric ID from the sales order list page',
  仓储管理: 'Warehouse Management',
  仓库: 'Warehouse',
  仓库信息: 'Warehouse Info',
  付款单: 'Payment',
  付款单ID: 'Payment ID',
  付款单号: 'Payment No.',
  付款时间: 'Paid At',
  付款管理: 'Payments',
  仪表盘: 'Dashboard',
  价格: 'Price',
  任务: 'Task',
  任务管理: 'Tasks',
  企业所得税: 'Corporate Income Tax',
  优先级: 'Priority',
  优惠金额: 'Discount Amount',
  会计科目: 'Chart of Accounts',
  低库存预警: 'Low Stock Alerts',
  余额: 'Balance',
  供应商: 'Supplier',
  供应商ID: 'Supplier ID',
  供应商信息: 'Supplier Info',
  保修到期: 'Warranty Expiry',
  保养计划: 'Maintenance Plans',
  保养频率: 'Maintenance Frequency',
  保存: 'Save',
  '保存失败: {error}': 'Save failed: {error}',
  保存成功: 'Saved successfully',
  '修改失败: {error}': 'Change failed: {error}',
  修改密码: 'Change Password',
  借: 'Debit',
  借方合计: 'Total Debits',
  值: 'Value',
  全部: 'All',
  公海池: 'Lead Pool',
  公积金: 'Housing Fund',
  '共 {count} 个': '{count} total',
  '共 {total} 条': '{total} records',
  关联订单: 'Related Order',
  关联销售订单ID: 'Linked Sales Order ID',
  关闭: 'Close',
  其他: 'Other',
  内容: 'Content',
  冻结时间: 'Hold Until',
  净利率: 'Net Margin',
  '凭证ID: {id}': 'Voucher ID: {id}',
  凭证号: 'Voucher No.',
  凭证名称: 'Voucher Name',
  凭证日期: 'Voucher Date',
  出入库流水: 'Stock Movement',
  '出货检验(OQC)': 'Outgoing Inspection (OQC)',
  分区拣货: 'Pick by Zone',
  分类: 'Category',
  分组: 'Group',
  分配中: 'Allocating',
  分配库存: 'Allocate Stock',
  分配数量不能为空: 'Quantity is required',
  分配数量须为正数: 'Quantity must be a positive number',
  '创建失败: {error}': 'Create failed: {error}',
  创建履约: 'Create Fulfillment',
  创建成功: 'Created successfully',
  创建时间: 'Created At',
  删除: 'Delete',
  '删除({count})': 'Delete ({count})',
  '删除失败: {error}': 'Delete failed: {error}',
  删除成功: 'Deleted successfully',
  利润: 'Profit',
  利润中心: 'Profit Center',
  利润报表: 'Profit Report',
  '利润表 JSON *': 'Income Statement JSON *',
  到期日: 'Due Date',
  刷新: 'Refresh',
  加班费: 'Overtime Pay',
  '加载中...': 'Loading...',
  加载失败: 'Failed to load',
  '加载失败: {error}': 'Failed to load: {error}',
  '加载权限列表失败: {error}': 'Failed to load permissions: {error}',
  '加载用户列表失败: {error}': 'Failed to load users: {error}',
  '加载角色列表失败: {error}': 'Failed to load roles: {error}',
  包装类型: 'Package Type',
  单价: 'Price',
  单位: 'Unit',
  单据ID: 'Document ID',
  单据ID必须为数字: 'Document ID must be numeric',
  单据类型: 'Document Type',
  卖家备注: 'Seller Note',
  印花税: 'Stamp Duty',
  原因: 'Reason',
  原币ID: 'Source Currency ID',
  '参数(JSON)': 'Params (JSON)',
  参数验证失败: 'Validation failed',
  发放: 'Pay',
  '发放失败：{error}': 'Payment failed: {error}',
  发货仓库ID: 'Shipping Warehouse ID',
  发货单ID: 'Delivery ID',
  发货单号: 'Delivery No.',
  取消: 'Cancel',
  取消订单: 'Cancel Order',
  变更说明: 'Change Notes',
  合同名称: 'Contract Name',
  合同状态流转: 'Contract Status Transition',
  合同管理: 'Contracts',
  合同编号: 'Contract No.',
  '合并中...': 'Consolidating...',
  合并报表: 'Consolidated Reports',
  合格数量: 'Passed Qty',
  名称: 'Name',
  后端要求提供发货仓库: 'A shipping warehouse is required by the server',
  否: 'No',
  启用: 'Enable',
  员工: 'Employee',
  员工ID: 'Employee ID',
  员工档案: 'Employees',
  品牌: 'Brand',
  品牌管理: 'Brands',
  商品: 'Product',
  商品ID: 'Product ID',
  商品ID须为正整数: 'Product ID must be a positive integer',
  '商品ID（数字）': 'Product ID (numeric)',
  商品信息: 'Product Info',
  商品分类: 'Categories',
  商品列表: 'Product List',
  商品名称: 'Product Name',
  商品明细: 'Items',
  商品编码: 'Product Code',
  商机: 'Opportunity',
  商机管理: 'Opportunities',
  商品规格: 'Product Specs',
  固定: 'Fixed',
  固定资产: 'Fixed Asset',
  图表名称: 'Chart Name',
  图表管理: 'Manage Charts',
  '图表管理 — {name}': 'Manage Charts — {name}',
  图表类型: 'Chart Type',
  地址: 'Address',
  地点: 'Location',
  型号: 'Model',
  基本信息: 'Basic Info',
  基本工资: 'Base Salary',
  增值税: 'Value-Added Tax',
  处置方式: 'Disposition',
  备件: 'Spare Parts',
  备件名称: 'Spare Part Name',
  备件编码: 'Spare Part Code',
  备注: 'Notes',
  '多币种/汇率': 'Multi-Currency / FX Rates',
  天数: 'Days',
  失效日期: 'Valid To',
  '如 1.5': 'e.g. 1.5',
  '如 10.00': 'e.g. 10.00',
  '如 100.00': 'e.g. 100.00',
  '如 1000.00': 'e.g. 1000.00',
  '如 61000000000000001=CNY': 'e.g. 61000000000000001=CNY',
  '如 7.250000': 'e.g. 7.250000',
  '如 8000.00': 'e.g. 8000.00',
  '如 purchase_order / expense': 'e.g. purchase_order / expense',
  '如 {amount}': 'e.g. {amount}',
  姓名: 'Employee Name',
  婚假: 'Marriage Leave',
  '子公司报表 JSON 数组 *': 'Subsidiary Reports JSON Array *',
  存放位置: 'Location',
  季: 'Quarter',
  完成: 'Finish',
  定时调度: 'Schedules',
  实发工资: 'Net Pay',
  实时库存: 'Stock on Hand',
  审批: 'Approve',
  审批中: 'Approving',
  审批工作流: 'Workflow',
  审批意见为必填项: 'An approval comment is required',
  '审批意见（必填）': 'Approval Comment (required)',
  '审批意见（选填）': 'Approval Comment (optional)',
  审批流程: 'Workflow',
  审批记录: 'Approval Records',
  客户: 'Customer',
  客户ID: 'Customer ID',
  客户信息: 'Customer Info',
  客户分析: 'Customer Analytics',
  宽度: 'Width',
  密码: 'Password',
  密码修改成功: 'Password changed successfully',
  密码验证失败: 'Password verification failed',
  导入失败: 'Import failed',
  导入成功: 'Import successful',
  导出: 'Export',
  导出Excel: 'Export Excel',
  导出PDF: 'Export PDF',
  导出成功: 'Export successful',
  展开菜单: 'Expand menu',
  履约: 'Fulfill',
  履约单: 'Fulfillments',
  履约状态: 'Fulfillment Status',
  履约管理: 'Fulfillment',
  工作日期: 'Work Date',
  工作流定义: 'Workflows',
  工作站: 'Workstation',
  工作站ID: 'Workstation ID',
  工单ID: 'Work Order ID',
  工单编码: 'Work Order Code',
  工序号: 'Seq',
  工时: 'Timesheet',
  '工时(小时)': 'Hours',
  工时记录: 'Timesheets',
  工艺路线: 'Routing',
  已付金额: 'Paid Amount',
  已入库: 'Received',
  已关闭: 'Closed',
  已出库: 'Issued',
  已分配: 'Assigned',
  已发放: 'Paid',
  已发货: 'Shipped',
  已取件: 'Picked Up',
  已取消: 'Cancelled',
  已失效: 'Expired',
  已完成: 'Completed',
  已审批: 'Approved',
  已审核: 'Reviewed',
  已打包: 'Packed',
  已打款: 'Paid',
  已批准: 'Approved',
  已报价: 'Quoted',
  已拒绝: 'Rejected',
  已拣货: 'Picked',
  已撤回: 'Withdrawn',
  已支付: 'Paid',
  已收货: 'Received',
  已收金额: 'Received Amount',
  已核销: 'Settled',
  '已点击 {count}/{total}': 'Clicked {count}/{total}',
  已签收: 'Signed For',
  已终止: 'Terminated',
  已结算: 'Settled',
  已转订单: 'Converted to Order',
  已退回: 'Returned',
  已退款: 'Refunded',
  已送达: 'Delivered',
  已通过: 'Approved',
  已驳回: 'Rejected',
  币种: 'Currency',
  '币种列表中的数字ID，如 61000000000000002=USD':
    'Numeric ID from the currency list, e.g. 61000000000000002=USD',
  布局配置: 'Layout Config',
  年: 'Year',
  年份: 'Year',
  年假: 'Annual Leave',
  年度: 'Year',
  序列号: 'Serial Number',
  库位: 'Location',
  库位管理: 'Location Management',
  库区: 'Zone',
  库区管理: 'Zones',
  库存: 'Inventory',
  库存不足: 'Insufficient stock',
  库存总值: 'Inventory Value',
  库存数量: 'Stock Qty',
  库存流水: 'Stock Movements',
  库存调拨: 'Stock Transfer',
  库存预警: 'Stock Alerts',
  应付: 'Payable',
  应付账龄: 'AP Aging',
  应付金额: 'Payable Amount',
  应发工资: 'Gross Pay',
  应收: 'Receivable',
  应收应付: 'AR/AP',
  应收账龄: 'AR Aging',
  应收金额: 'Receivable Amount',
  应纳税所得额: 'Taxable Income',
  开始日期: 'Start Date',
  开始时间: 'Start Time',
  开始维修: 'Start Repair',
  开户银行: 'Bank Name',
  异常: 'Exception',
  当前状态不允许此操作: 'Operation not allowed in current status',
  当前状态无可流转的目标状态: 'No target status available for the current status',
  当前节点: 'Current Node',
  往来单位: 'Counterparty',
  '往来单位与所选类型不匹配，请重新选择':
    'Counterparty does not match the selected type, please re-select',
  待入库: 'Pending Receipt',
  待出库: 'Pending Issue',
  待发货: 'Ready to Ship',
  待处理: 'Pending',
  待审批: 'Pending',
  待审核: 'Pending Review',
  待打包: 'Pending Pack',
  待拣货: 'Pending Pick',
  待支付: 'Pending Payment',
  微信: 'WeChat',
  '必填（后端校验）': 'Required (validated by server)',
  '必填（后端校验），如 OM+时间戳': 'Required (validated by server), e.g. OM+timestamp',
  总览: 'Overview',
  '总账/明细账': 'General / Detail Ledger',
  总金额: 'Total Amount',
  恢复成功: 'Restored successfully',
  成功: 'Success',
  '成本/利润中心': 'Cost / Profit Centers',
  成本中心: 'Cost Center',
  成本价: 'Unit Cost',
  我的审批: 'My Approvals',
  '截止重量(kg)': 'Weight To (kg)',
  所有者权益: "Owner\\'s Equity",
  手机号: 'Phone',
  打包中: 'Packing',
  打包任务: 'Pack Task',
  打包单: 'Pack Task',
  打包管理: 'Packing',
  扣款: 'Deductions',
  执行: 'Run',
  执行中: 'Active',
  执行合并: 'Run Consolidation',
  '执行失败：{error}': 'Execution failed: {error}',
  批准: 'Approve',
  批准时间: 'Approved At',
  批准请假: 'Approve Leave',
  批次号: 'Batch No.',
  '批量删除失败: {error}': 'Batch delete failed: {error}',
  批量删除完成: 'Selected users deleted',
  批量删除成功: 'Batch delete successful',
  批量启用: 'Enable Selected',
  批量启用完成: 'Selected users enabled',
  批量拣货: 'Pick by Batch',
  批量操作成功: 'Batch operation successful',
  批量禁用: 'Disable Selected',
  批量禁用完成: 'Selected users disabled',
  承运商: 'Carrier',
  承运商服务: 'Carrier Service',
  承运服务: 'Carrier Service',
  投资活动净额: 'Net Investing Cash Flow',
  投资活动流入: 'Investing Inflows',
  投资活动流出: 'Investing Outflows',
  折旧年份: 'Depreciation Year',
  折旧月份: 'Depreciation Month',
  折旧计提成功: 'Depreciation recorded',
  报价单: 'Quotation',
  报价单号: 'Quotation No.',
  报价时间: 'Quoted At',
  报价转合同: 'Quotation to Contract',
  报价金额: 'Quotation Amount',
  报告人: 'Reporter',
  报表: 'Report',
  报表名称: 'Report Name',
  报表管理: 'Reports',
  报表类型: 'Report Type',
  '报表结果：{name}': 'Report Result: {name}',
  '报表说明: {note}': 'Report note: {note}',
  抽样方案: 'Sampling Plan',
  拒绝: 'Reject',
  拣货中: 'Picking',
  拣货任务: 'Pick Task',
  拣货单: 'Pick Task',
  拣货管理: 'Picking',
  指标名称: 'Metric Name',
  指标类型: 'Metric Type',
  指标键名: 'Metric Key',
  指派: 'Assign',
  指派人: 'Assignee',
  指派工单: 'Assign Ticket',
  按单拣货: 'Pick by Order',
  换一张: 'Refresh',
  换货: 'Exchange',
  排序: 'Sort Order',
  接收人: 'Recipient',
  描述: 'Description',
  提交: 'Submit',
  '提交中...': 'Submitting...',
  提交人: 'Submitted By',
  '提交失败：{error}': 'Submit failed: {error}',
  提交审批: 'Submit for Approval',
  '提交审批：{name}': 'Submit for Approval: {name}',
  提交成功: 'Submitted successfully',
  提交时间: 'Submitted At',
  提示: 'Info',
  搜索: 'Search',
  '搜索...': 'Search...',
  '搜索商品名称/编码/批次号': 'Search product name, code or batch',
  '搜索用户名/姓名': 'Search username/name',
  摘要: 'Summary',
  撤回: 'Withdraw',
  '撤回失败: {error}': 'Withdraw failed: {error}',
  撤回审批: 'Withdraw Approval',
  操作: 'Actions',
  操作失败: 'Operation failed',
  '操作失败，请重试': 'Operation failed, please retry',
  '操作失败：{error}': 'Operation failed: {error}',
  操作成功: 'Operation successful',
  操作日志: 'Operation Log',
  操作筛选: 'Filter by action',
  操作者: 'Operator',
  支付宝: 'Alipay',
  支付状态: 'Payment Status',
  收入结转: 'Revenue Carryforward',
  收款单: 'Receipt',
  收款单ID: 'Receipt ID',
  收款单号: 'Receipt No.',
  收款时间: 'Received At',
  收款管理: 'Receipts',
  收货仓库ID: 'Receiving Warehouse ID',
  收货单ID: 'Receiving ID',
  收货单号: 'Receiving No.',
  收货时间: 'Received At',
  收货管理: 'Receiving',
  收起菜单: 'Collapse menu',
  故障描述: 'Fault Description',
  敏感操作需要输入密码确认: 'Password confirmation required for sensitive operations',
  '数据趋势（近30天）': 'Data Trend (Last 30 Days)',
  数据集: 'Datasets',
  数据集ID: 'Dataset ID',
  '数据集ID: {value}': 'Dataset ID: {value}',
  数据集名称: 'Dataset Name',
  数量: 'Quantity',
  文档列表: 'Document List',
  文档标题: 'Document Title',
  文档编码: 'Document Code',
  新增: 'Add',
  新增OMS订单: 'Add OMS Order',
  新增图表: 'Add Chart',
  新增报价单: 'Add Quotation',
  新增汇率: 'Add Exchange Rate',
  新增用户: 'Add User',
  新增结算: 'Add Settlement',
  新增薪资记录: 'Add Payroll Record',
  新增薪资项: 'Add Salary Item',
  新增角色: 'Add Role',
  新增记账凭证: 'Add Voucher',
  新增请假: 'Add Leave',
  新增账户: 'Add Account',
  新增跟进: 'Add Follow-up',
  新增跟进记录: 'Add Follow-up',
  新增配置: 'Add Setting',
  新增采购申请: 'Add Purchase Request',
  '新增采购结算（付款核销）': 'Add Purchase Settlement (payment write-off)',
  新增采购订单: 'Add Purchase Order',
  新增银行账户: 'Add Bank Account',
  '新增销售结算（收款核销）': 'Add Sales Settlement (receipt write-off)',
  新增销售订单: 'Add Sales Order',
  新增阶段: 'Add Stage',
  '新密码 (6-32位)': 'New Password (6-32 chars)',
  '新密码（留空不修改）': 'New password (leave blank to keep unchanged)',
  新建指标: 'New Metric',
  方向: 'Direction',
  方式: 'Method',
  方法: 'Method',
  无效的ID: 'Invalid ID',
  无权限访问: 'Access denied',
  日期: 'Date',
  旧密码: 'Old Password',
  时间: 'Time',
  '明细-借方金额': 'Item Debit',
  '明细-摘要': 'Item Summary',
  '明细-科目ID': 'Item Account ID',
  '明细-贷方金额': 'Item Credit',
  明细分类账: 'Subsidiary Ledgers',
  是: 'Yes',
  '是否计税(0/1)': 'Taxable (0/1)',
  暂无可选用户: 'No assignable users',
  '暂无图表，点击「新增图表」创建': 'No charts yet; click "Add Chart" to create one',
  暂无数据: 'No data',
  暂无明细数据: 'No detail data',
  暂无角色: 'No roles yet',
  '更新失败: {error}': 'Update failed: {error}',
  更新成功: 'Updated successfully',
  最低: 'Lowest',
  最低库存: 'Min Stock',
  最后登录: 'Last Login',
  最近操作: 'Recent Operations',
  最高: 'Highest',
  最高库存: 'Max Stock',
  月: 'Month',
  月份: 'Month',
  服务器内部错误: 'Internal server error',
  服务工单: 'Service Ticket',
  期初借方: 'Opening Debit',
  期初现金: 'Beginning Cash',
  期初贷方: 'Opening Credit',
  期末借方: 'Closing Debit',
  期末现金: 'Ending Cash',
  期末结转: 'Period-End Closing',
  期末贷方: 'Closing Credit',
  期间: 'Period',
  '期间 YYYY-MM': 'Period YYYY-MM',
  '期间 YYYY-MM(可选)': 'Period YYYY-MM (optional)',
  期间值: 'Period Value',
  期间类型: 'Period Type',
  未分配: 'Unassigned',
  未发放: 'Unpaid',
  未填写则留空: 'Leave blank to keep unchanged',
  未授权访问: 'Unauthorized',
  未核销: 'Unsettled',
  未知: 'Unknown',
  未结算: 'Unsettled',
  本位币: 'Base Currency',
  本年利润: 'Profit for the Year',
  本期借方: 'Current Debit',
  本期贷方: 'Current Credit',
  权限: 'Permission',
  '权限分配:': 'Permissions:',
  条码: 'Barcode',
  '来料检验(IQC)': 'Incoming Inspection (IQC)',
  来源: 'Source',
  来源类型: 'Source Type',
  来源记录ID: 'Source ID',
  查看单据: 'View Document',
  查询: 'Query',
  查询SQL: 'Query SQL',
  '查询中...': 'Querying...',
  '查询成功，暂无数据行': 'Query succeeded, no result rows',
  标准名称: 'Standard Name',
  标准编码: 'Standard Code',
  标签: 'Tags',
  标记全部已读: 'Mark All as Read',
  标识: 'Slug',
  '标识: {slug} | 用户数: {count} | {desc}': 'Slug: {slug} | Users: {count} | {desc}',
  标题: 'Title',
  核销金额: 'Write-off Amount',
  根本原因: 'Root Cause',
  '格式 YYYY-MM-DD': 'Format YYYY-MM-DD',
  '格式 YYYY-MM-DD HH:mm:ss': 'Format YYYY-MM-DD HH:mm:ss',
  '格式 YYYY-MM-DD HH:mm:ss，可留空': 'Format YYYY-MM-DD HH:mm:ss, optional',
  '检验/合格/不合格': 'Inspected/Passed/Rejected',
  检验单号: 'Inspection No.',
  检验员: 'Inspector',
  检验数量: 'Inspected Qty',
  检验标准: 'Inspection Standards',
  检验标准ID: 'Inspection Standard ID',
  检验类型: 'Inspection Type',
  检验结果: 'Inspection Result',
  检验规格: 'Inspection Spec',
  模块: 'Module',
  模板: 'Template',
  模板ID: 'Template ID',
  正常: 'Normal',
  每公斤单价: 'Per-kg Rate',
  每周: 'Weekly',
  每天: 'Daily',
  每月: 'Monthly',
  汇兑损益: 'Exchange Gain/Loss',
  汇率: 'Exchange Rate',
  汇率管理: 'Exchange Rates',
  没有需要保存的修改: 'No changes to save',
  波次拣货: 'Pick by Wave',
  波次管理: 'Wave',
  派送中: 'Out for Delivery',
  流动比率: 'Current Ratio',
  流动负债: 'Current Liabilities',
  流动资产: 'Current Assets',
  流转: 'Transition',
  浮动: 'Variable',
  渠道: 'Channel',
  渠道店铺名称: 'Channel Store Name',
  渠道管理: 'Channels',
  渠道订单号: 'Channel Order No.',
  '热销商品 TOP 5': 'Top 5 Products',
  '燃油附加费(%)': 'Fuel Surcharge (%)',
  版本: 'Version',
  物流轨迹: 'Tracking',
  状态: 'Status',
  状态流转: 'Status Transition',
  状态流转成功: 'Status transitioned',
  现金: 'Cash',
  现金日记账: 'Cash Journals',
  现金流量表: 'Cash Flow Statement',
  生产制造: 'Manufacturing',
  生产工单: 'Production Order',
  生产工单ID: 'Work Order ID',
  生成报表: 'Generate Report',
  生成时间: 'Generated At',
  '生成时间: {value}': 'Generated at: {value}',
  生效日期: 'Effective Date',
  用户: 'User',
  用户ID: 'User ID',
  用户创建成功: 'User created',
  用户名: 'Username',
  用户名或密码错误: 'Invalid username or password',
  用户更新成功: 'User updated',
  用户状态分布: 'User Status Distribution',
  用户管理: 'Users',
  申请人ID: 'Requester ID',
  申请单号: 'Request No.',
  申请部门: 'Department',
  电话: 'Phone',
  留空为0: 'Leave blank for 0',
  '留空自动生成 CT+时间戳': 'Leave blank to auto-generate CT+timestamp',
  '留空自动生成 PA+时间戳': 'Leave blank to auto-generate PA+timestamp',
  '留空自动生成 PAY+时间戳': 'Leave blank to auto-generate PAY+timestamp',
  '留空自动生成 PO+时间戳': 'Leave blank to auto-generate PO+timestamp',
  '留空自动生成 PRN+时间戳': 'Auto PRN+timestamp when blank',
  '留空自动生成 QT+时间戳': 'Leave blank to auto-generate QT+timestamp',
  '留空自动生成 RCV+时间戳': 'Leave blank to auto-generate RCV+timestamp',
  '留空自动生成 SO+时间戳': 'Leave blank to auto-generate SO+timestamp',
  '留空自动生成 SRN+时间戳': 'Auto SRN+timestamp when blank',
  '留空自动生成 VCH+时间戳': 'Leave blank to auto-generate VCH+timestamp',
  '留空默认 合同-报价单号': 'Leave blank to default to Contract-quotation No.',
  病假: 'Sick Leave',
  '登 录': 'Log In',
  登出成功: 'Logged out successfully',
  登录失败: 'Login failed',
  登录成功: 'Login successful',
  '登录状态已失效，请重新登录': 'Session expired, please log in again',
  盘点: 'Stocktaking',
  盘点任务: 'Stocktakes',
  目标币ID: 'Target Currency ID',
  目标状态: 'Target Status',
  目的区域: 'Destination Zone',
  目的国家: 'Destination Country',
  看板名称: 'Dashboard Name',
  真实姓名: 'Real Name',
  确定: 'OK',
  '确定执行「{action}」？': 'Confirm “{action}”?',
  '确定要删除「{name}」吗？': 'Are you sure you want to delete "{name}"?',
  '确定要删除图表「{name}」吗？': 'Are you sure you want to delete chart "{name}"?',
  '确定要删除用户「{name}」吗？': 'Are you sure you want to delete user "{name}"?',
  '确定要删除角色「{name}」吗？': 'Are you sure you want to delete role "{name}"?',
  '确定要删除该汇率记录吗？': 'Are you sure you want to delete this exchange rate?',
  '确定要删除该薪资记录吗？': 'Are you sure you want to delete this payroll record?',
  '确定要删除该请假记录吗？': 'Are you sure you want to delete this leave record?',
  '确定要删除该采购结算记录吗？':
    'Are you sure you want to delete this purchase settlement record?',
  '确定要删除该销售结算记录吗？': 'Are you sure you want to delete this sales settlement record?',
  '确定要删除选中的 {count} 个用户吗？': 'Delete the {count} selected users?',
  '确定要删除配置「{key}」吗？': 'Are you sure you want to delete setting "{key}"?',
  '确定要删除银行账户「{name}」吗？': 'Are you sure you want to delete bank account "{name}"?',
  '确定要将工单「{code}」流转为「{status}」吗？': 'Move work order "{code}" to "{status}"?',
  '确定要撤回该审批吗？': 'Withdraw this approval request?',
  '确定要退出登录吗？': 'Are you sure you want to log out?',
  确定退出: 'Confirm',
  确认: 'Confirm',
  确认删除: 'Confirm delete',
  确认发放: 'Confirm Payment',
  '确认将「{period}」的薪资标记为已发放吗？': 'Mark salary for "{period}" as paid?',
  '确认批准该请假申请吗？': 'Approve this leave request?',
  确认批量删除: 'Confirm Batch Delete',
  确认收货: 'Confirm Receipt',
  确认新密码: 'Confirm New Password',
  确认解决: 'Confirm Resolution',
  确认计提: 'Confirm',
  确认退出: 'Confirm Log Out',
  '确认驳回该请假申请吗？': 'Reject this leave request?',
  '社保(个人)': 'Social Insurance (employee)',
  禁用: 'Disable',
  科目ID: 'Account ID',
  科目余额: 'Account Balances',
  税务管理: 'Taxes',
  税率: 'Tax Rate',
  '第 {page} 页 / 共 {pages} 页 ({total} 条)': 'Page {page} of {pages} ({total} records)',
  等级: 'Level',
  筹资活动净额: 'Net Financing Cash Flow',
  筹资活动流入: 'Financing Inflows',
  筹资活动流出: 'Financing Outflows',
  管理后台: 'Admin Console',
  管理员: 'Administrator',
  类型: 'Type',
  '类型(0=固定 1=浮动)': 'Type (0=fixed 1=variable)',
  '类型: {type}': 'Type: {type}',
  系统: 'System',
  系统管理: 'System',
  系统配置: 'System Config',
  纠正措施: 'Corrective Action',
  经营: 'Business',
  经营活动净额: 'Net Operating Cash Flow',
  经营活动流入: 'Operating Inflows',
  经营活动流出: 'Operating Outflows',
  结束日期: 'End Date',
  结束时间: 'End Time',
  结果: 'Result',
  '结果: {value}': 'Result: {value}',
  '结果行数: {value}': 'Result rows: {value}',
  结算: 'Settle',
  结算时间: 'Settled At',
  结算状态: 'Settlement Status',
  结转状态: 'Closing Status',
  绩效工资: 'Performance Pay',
  维修: 'Repair',
  维修人: 'Repairer',
  维修工单: 'Repair Orders',
  维修类型: 'Repair Type',
  维修费用: 'Repair Cost',
  编号: 'No.',
  编码: 'Code',
  编辑: 'Edit',
  编辑OMS订单: 'Edit OMS Order',
  编辑图表: 'Edit Chart',
  编辑报价单: 'Edit Quotation',
  '编辑收货单（仅备注）': 'Edit Receiving Record (remark only)',
  编辑汇率: 'Edit Exchange Rate',
  编辑用户: 'Edit User',
  编辑薪资: 'Edit Payroll Record',
  编辑薪资项: 'Edit Salary Item',
  编辑角色: 'Edit Role',
  编辑记账凭证: 'Edit Voucher',
  编辑请假: 'Edit Leave',
  编辑跟进记录: 'Edit Follow-up',
  编辑配置: 'Edit Setting',
  编辑采购申请: 'Edit Purchase Request',
  编辑采购结算: 'Edit Purchase Settlement',
  编辑采购订单: 'Edit Purchase Order',
  编辑银行账户: 'Edit Bank Account',
  编辑销售结算: 'Edit Sales Settlement',
  编辑销售订单: 'Edit Sales Order',
  编辑阶段: 'Edit Stage',
  缺陷数量: 'Defect Qty',
  缺陷类型: 'Defect Type',
  '网络连接失败，请检查网络': 'Network connection failed, please check your network',
  '网络错误，请检查连接': 'Network error, please check your connection',
  考勤: 'Attendance',
  考勤管理: 'Attendance',
  职位: 'Position',
  职位管理: 'Positions',
  联系人: 'Contact',
  草稿: 'Draft',
  营业成本: 'Operating Cost',
  营业收入: 'Operating Revenue',
  营销活动: 'Campaign',
  薪资: 'Salary',
  薪资发放: 'Pay Salaries',
  薪资已发放: 'Salary marked as paid',
  薪资年度: 'Salary Year',
  薪资月份: 'Salary Month',
  薪资管理: 'Payroll',
  薪资试算: 'Salary Calculation',
  薪资项配置: 'Payroll Items',
  行数: 'Rows',
  规格: 'Spec',
  规格名称: 'Spec Name',
  规格型号: 'Model/Spec',
  角色: 'Role',
  角色创建成功: 'Role created',
  角色删除成功: 'Role deleted',
  角色更新成功: 'Role updated',
  角色管理: 'Roles',
  解决: 'Resolve',
  解决工单: 'Resolve Ticket',
  解决说明: 'Resolution Notes',
  计划名称: 'Plan Name',
  计划生产数量: 'Planned Quantity',
  计提折旧: 'Record Depreciation',
  计税: 'Taxable',
  '计算中...': 'Calculating...',
  计算比率: 'Calculate Ratios',
  计算薪资: 'Calculate Salary',
  订单: 'Order',
  订单名称: 'Order Name',
  订单总金额: 'Order Total Amount',
  订单状态分布: 'Order Status Distribution',
  订单管理: 'Order Management',
  订单编号: 'Order No.',
  订单编码: 'Order Code',
  记录不存在: 'Record not found',
  记录已存在: 'Record already exists',
  记账凭证: 'Voucher',
  设备ID: 'Equipment ID',
  设备分类: 'Equipment Category',
  设备台账: 'Equipment Ledger',
  设备名称: 'Equipment Name',
  设备编码: 'Equipment Code',
  试算平衡表: 'Trial Balance',
  试算结果: 'Calculation Result',
  详情: 'Details',
  说明: 'Description',
  请假: 'Leave',
  请假原因: 'Reason',
  请假天数: 'Leave Days',
  请假日期: 'Leave Period',
  请假管理: 'Leave',
  请假类型: 'Leave Type',
  请先选择用户: 'Please select users first',
  请加载验证码: 'Please load the captcha',
  '请按顺序点击图中文字: {text}': 'Click the characters in the image in order: {text}',
  '请按顺序点击图中文字『{text}』': "Click the character \\'{text}\\' in order",
  请求失败: 'Request failed',
  '请求超时，请稍后重试': 'Request timed out, please retry later',
  '请求过于频繁，请稍后重试': 'Too many requests, please try again later',
  请至少填写一行分配明细: 'Add at least one allocation line',
  '请输入{label}': 'Please enter {label}',
  请输入密码: 'Please enter your password',
  请输入用户名和密码: 'Please enter username and password',
  '请输入科目ID（account_subject_id 必填）': 'Enter Account ID (account_subject_id is required)',
  请选择目标状态: 'Please select a target status',
  调休: 'Compensatory Leave',
  负债总计: 'Total Liabilities',
  负责人: 'Assignee',
  财务: 'Finance',
  财务比率: 'Financial Ratios',
  账号已被锁定: 'Account is locked',
  账户余额: 'Account Balance',
  账户名称: 'Account Name',
  购买日期: 'Purchase Date',
  贷: 'Credit',
  贷方合计: 'Total Credits',
  费用: 'Expense',
  费用合计: 'Total Expenses',
  费用报销: 'Expense',
  费用结转: 'Expense Carryforward',
  资产总计: 'Total Assets',
  资产收益率: 'Return on Assets',
  资产负债率: 'Debt-to-Asset Ratio',
  资产负债表: 'Balance Sheet',
  '资产负债表 JSON *': 'Balance Sheet JSON *',
  起始区域: 'Origin Zone',
  起始国家: 'Origin Country',
  '起始重量(kg)': 'Weight From (kg)',
  起步价: 'Base Rate',
  跟进主题: 'Follow-up Subject',
  跟进内容: 'Follow-up Content',
  跟进记录: 'Follow-up',
  路径: 'Path',
  路径筛选: 'Filter by path',
  转合同: 'Convert to Contract',
  输入关键词搜索: 'Enter keywords to search',
  输入密码确认: 'Enter password to confirm',
  '过程检验(IPQC)': 'In-process Inspection (IPQC)',
  运单: 'Shipment',
  运单号: 'Tracking No.',
  运单管理: 'Shipments',
  运费: 'Shipping Fee',
  运费发票: 'Freight Invoice',
  运费费率: 'Freight Rate',
  运输中: 'In Transit',
  运输管理: 'Transport Management',
  退出登录: 'Log Out',
  退回时间: 'Returned At',
  退回运费: 'Return Shipping Fee',
  退换单号: 'RMA No.',
  退换货: 'RMA',
  '退换货(RMA)': 'Returns (RMA)',
  退款: 'Refund',
  退款金额: 'Refund Amount',
  退货: 'Return',
  退货单号: 'Return No.',
  退货时间: 'Returned At',
  选填: 'Optional',
  通知: 'Notification',
  通知中心: 'Notifications',
  通过: 'Approve',
  通过审批: 'Approve',
  邮箱: 'Email',
  部分发货: 'Partially Shipped',
  部分收货: 'Partially Received',
  部分核销: 'Partially Settled',
  部分结算: 'Partially Settled',
  部分退款: 'Partially Refunded',
  部门: 'Department',
  部门ID: 'Department ID',
  部门管理: 'Departments',
  配置JSON: 'Config JSON',
  配送方式: 'Shipping Method',
  采购: 'Purchase',
  采购收货: 'Purchase Receiving',
  采购申请: 'Purchase Requisition',
  采购申请ID: 'Purchase Request ID',
  采购结算: 'Purchase Settlement',
  采购订单: 'Purchase Order',
  采购退货: 'Purchase Return',
  释放回公海: 'Release to Pool',
  重试: 'Retry',
  金额: 'Amount',
  金额超出限额: 'Amount exceeds limit',
  银行: 'Bank',
  银行账号: 'Bank Account Number',
  银行账户: 'Bank Accounts',
  销售: 'Sales',
  销售发货: 'Sales Delivery',
  销售报价: 'Sales Quotations',
  销售渠道: 'Sales Channel',
  销售漏斗: 'Sales Funnel',
  销售结算: 'Sales Settlements',
  销售订单: 'Sales Order',
  '销售趋势（近30天）': 'Sales Trend (Last 30 Days)',
  销售退货: 'Sales Return',
  错误: 'Error',
  键: 'Key',
  阶段: 'Stage',
  阶段名称: 'Stage Name',
  '需已审核的付款单 hashid': 'Hashid of an approved payment record',
  '需已审核的收款单 hashid': 'Hashid of an approved receipt record',
  非流动负债: 'Non-Current Liabilities',
  非流动资产: 'Non-Current Assets',
  '非空 JSON 数组，每项须含 ledger_id 或 company_id（后端数字ID，非 hashid）与 report_year（≥2000）、report_month（1-12）':
    'Non-empty JSON array; each item must have ledger_id or company_id (numeric backend ID, not hashid) plus report_year (≥2000) and report_month (1-12)',
  项目: 'Project',
  项目列表: 'Project List',
  '预到货(ASN)': 'Expected Receipts (ASN)',
  预到货通知: 'ASN',
  预算: 'Budget',
  预算管理: 'Budgets',
  领取: 'Claim',
  领取客户: 'Claim Customer',
  频率: 'Frequency',
  驳回: 'Reject',
  驳回审批: 'Reject',
  驳回请假: 'Reject Leave',
  验证码加载失败: 'Failed to load captcha',
  '验证码错误，请重试': 'Incorrect captcha, please retry',
  旋转图片验证: 'Rotate Image Captcha',
  滑块拼图验证: 'Slider Puzzle Captcha',
  '尝试次数过多，请更换验证码': 'Too many attempts, please refresh the captcha',
  转动图片使其摆正后提交: 'Rotate the image upright, then submit',
  拖动拼图块使其对齐图中缺口: 'Drag the puzzle piece to the gap in the image',
  高库存预警: 'Overstock Alerts',
  高度: 'Height',
  '默认 0': 'Default 0',
  默认金额: 'Default Amount',
  '0 为顶级': '0 for top level',
  '3-50 字符': '3-50 characters',
  '6-32 字符': '6-32 characters',
  '6-32 位': '6-32 characters',
  'BI 看板': 'BI Dashboard',
  'BOM 名称': 'BOM Name',
  'BOM 管理': 'BOM Management',
  'BOM 编码': 'BOM Code',
  'CRM 报价单': 'CRM Quotation',
  'LOGO 地址': 'Logo URL',
  'MRP 计划': 'MRP Plan',
  'MRP 运算': 'Run MRP',
  'Offer 已发出': 'Offer sent',
  'Offer 薪资': 'Offer Salary',
  erp开放平台: 'Open ERP Platform',
  上一页: 'Previous',
  上架: 'Publish',
  上架完成: 'Shelving done',
  上架已完成: 'Shelving completed',
  上次登录: 'Last Login',
  上班打卡: 'Clock In',
  上级部门: 'Parent Department',
  下一页: 'Next',
  下架: 'Unpublish',
  下班打卡: 'Clock Out',
  不合格: 'Reject',
  不合格品单号: 'NCR Number',
  不通过: 'Not Pass',
  '两位小数，如 30000.00': 'Up to 2 decimals, e.g. 30000.00',
  '两位小数，如 5000.00': 'Up to 2 decimals, e.g. 5000.00',
  两次输入的新密码不一致: 'The two new passwords do not match',
  中标转订单: 'Award to Purchase Order',
  产品: 'Product',
  人工: 'Labor',
  仓库名称: 'Warehouse Name',
  仓库管理: 'Warehouse Management',
  仓库编码: 'Warehouse Code',
  付款方式: 'Payment Method',
  付款日期: 'Payment Date',
  付款账户: 'Payment Account',
  任务名称: 'Task Name',
  任职要求: 'Requirements',
  作废: 'Void',
  使用年限: 'Useful Life',
  供应商名称: 'Supplier Name',
  供应商报价: 'Supplier Quotes',
  供应商评估: 'Supplier Assessment',
  保存失败: 'Save failed',
  保存资料: 'Save Profile',
  '信用账期(天)': 'Credit Term (days)',
  信用额度: 'Credit Limit',
  修改失败: 'Update failed',
  候选人: 'Candidate',
  停用: 'Suspend',
  兑付: 'Cash',
  入职日期: 'Onboard Date',
  全部通知已标记为已读: 'All notifications marked as read',
  共: 'of',
  关联任务: 'Linked Task',
  内训: 'Internal',
  再次输入新密码: 'Enter the new password again',
  净值: 'Net Value',
  出库仓库: 'Issue Warehouse',
  出票人: 'Drawer',
  出票日期: 'Issue Date',
  出货检验: 'Final Inspection OQC',
  '出货检验 OQC': 'Final Inspection OQC',
  分类名称: 'Category Name',
  初筛通过: 'Screen Passed',
  利润表: 'Income Statement',
  到期: 'Expired',
  到期预警: 'Expiry Alerts',
  制费: 'Overhead',
  加工单价: 'Processing Price',
  '加载中…': 'Loading...',
  勾选: 'Check',
  协同管理: 'Collaboration',
  原值: 'Original Value',
  发出: 'Send',
  发布: 'Publish',
  发布中: 'Published',
  发料仓库: 'Issue Warehouse',
  发料单号: 'Issue Slip No.',
  发料单已审核: 'Issue slip approved',
  发料日期: 'Issue Date',
  发生日期: 'Occur Date',
  发票号: 'Invoice No.',
  发票管理: 'Invoice Management',
  发货: 'Ship',
  发货单: 'Delivery Note',
  发货日期: 'Ship Date',
  发起审批: 'Start Approval',
  取消点检: 'Cancel Inspection',
  合同号: 'Contract No.',
  合同金额: 'Contract Amount',
  合格: 'Pass',
  合格数: 'Passed Qty',
  合计: 'Total',
  启停: 'Toggle',
  启动: 'Start',
  启用日期: 'In Service Date',
  员工姓名: 'Employee Name',
  员工编码: 'Employee Code',
  周期类型: 'Period Type',
  品牌名称: 'Brand Name',
  品牌描述: 'Brand Description',
  品项数: 'Line Items',
  商品描述: 'Description',
  商品管理: 'Product Management',
  商品资料: 'Product Master',
  商机名称: 'Opportunity Name',
  回复: 'Reply',
  回调地址: 'Callback URL',
  图标: 'Icon',
  图表组件: 'Chart Widget',
  城市: 'City',
  培训社保: 'Training & Social Security',
  培训课程: 'Training Courses',
  基本资料: 'Basic Profile',
  处理中: 'Processing',
  备件管理: 'Spare Parts',
  外训: 'External',
  多币种: 'Currencies',
  多组织公司: 'Companies',
  '如 admin、viewer': 'e.g. admin, viewer',
  '如 monthly': 'e.g. monthly',
  '如 上海': 'e.g. Shanghai',
  '如 人民币': 'e.g. CNY',
  委外产品: 'Outsourced Product',
  委外加工: 'Subcontracting',
  委外发料: 'Subcontract Issue',
  委外收货: 'Subcontract Receiving',
  委外数量: 'Subcontract Qty',
  委外订单: 'Subcontract Order',
  字符串: 'String',
  季度: 'Quarterly',
  学分: 'Credits',
  完工: 'Complete',
  完工数: 'Completed Qty',
  实发: 'Net Pay',
  审批已发起: 'Approval started',
  审核: 'Approve',
  客户名称: 'Customer Name',
  客户管理: 'Customer Management',
  密码已修改: 'Password changed',
  密钥已重置: 'Secret reset',
  小计: 'Subtotal',
  工作站名称: 'Workstation Name',
  工作站编码: 'Workstation Code',
  工单分类: 'Ticket Category',
  工单号: 'Ticket No.',
  工单已完工: 'Work order completed',
  工单已开工: 'Work order started',
  工单已解决: 'Ticket resolved',
  工单标题: 'Ticket Title',
  工序: 'Operation',
  工序名称: 'Operation Name',
  工序序号: 'Sequence',
  工序报工: 'Work Report',
  工时数: 'Hours',
  工资条: 'Payslip',
  已作废: 'Voided',
  已入职: 'Onboarded',
  '已发 Offer': 'Offer Sent',
  已发出: 'Sent',
  已回复: 'Replied',
  已完成库存分配: 'Stock allocated',
  已归档: 'Archived',
  已接受: 'Accepted',
  已提交: 'Submitted',
  已撤销: 'Withdrawn',
  已标记为已读: 'Marked as read',
  已派单: 'Assigned',
  已淘汰: 'Rejected',
  已生成合同: 'Contract generated',
  已生成履约单: 'Fulfillment created',
  已生成采购订单: 'Purchase order created',
  已生效: 'Effective',
  已用: 'Used',
  已结: 'Settled',
  已认领: 'Claimed',
  已读: 'Read',
  已释放回公海: 'Released back to pool',
  币种名称: 'Currency Name',
  币种管理: 'Currency Management',
  币种编码: 'Currency Code',
  布尔: 'Boolean',
  库位名称: 'Location Name',
  库位编码: 'Location Code',
  库区名称: 'Zone Name',
  库区编码: 'Zone Code',
  库存分配: 'Allocate Stock',
  库存管理: 'Inventory Management',
  应发: 'Gross Pay',
  应用名称: 'App Name',
  应聘职位: 'Applied Job',
  开工: 'Start',
  开户行: 'Bank',
  开放应用: 'OpenAPI Apps',
  开票: 'Issue Invoice',
  开票日期: 'Invoice Date',
  归档: 'Archive',
  归集日期: 'Posting Date',
  当前密码: 'Current Password',
  '录用 Offer': 'Offer Letter',
  往来方: 'Counterparty',
  待定: 'Pending',
  待开通: 'Pending Provision',
  总账: 'General Ledger',
  成本: 'Cost',
  成本归集: 'Cost Entry',
  成本类别: 'Cost Category',
  所属仓库: 'Warehouse',
  所属应用: 'App',
  所属模块: 'Module',
  所属看板: 'Dashboard',
  所属部门: 'Department',
  所属项目: 'Project',
  手机: 'Phone',
  打包完成: 'Pack Done',
  打包已完成: 'Packing completed',
  打卡成功: 'Punched successfully',
  托收: 'Collect',
  托收账户: 'Collection Account',
  执行报表: 'Run Report',
  批次效期预警: 'Batch Expiry Alerts',
  承兑人: 'Acceptor',
  承兑汇票: 'Banker Acceptance',
  承运商名称: 'Carrier Name',
  投递测试完成: 'Test delivery done',
  折扣: 'Discount',
  折旧已计提: 'Depreciation posted',
  折旧方法: 'Depreciation Method',
  报工员工: 'Reporting Employee',
  报工已审核: 'Work report approved',
  报工数量: 'Reported Qty',
  报工日期: 'Report Date',
  报表已执行: 'Report executed',
  报表模板: 'Report Template',
  报销金额: 'Reimbursement Amount',
  抵扣: 'Deduct',
  拒付: 'Reject',
  招聘人数: 'Headcount',
  招聘候选人: 'Candidates',
  招聘管理: 'Recruitment',
  招聘职位: 'Job Postings',
  招聘部门: 'Hiring Department',
  招聘面试: 'Interviews',
  拣货已确认: 'Pick confirmed',
  拣货确认: 'Confirm Pick',
  按钮: 'Button',
  提交数: 'Submitted Qty',
  搜索通知内容: 'Search notification content',
  搜索配置键: 'Search config key',
  撤销: 'Withdraw',
  操作人: 'Operator',
  支付: 'Pay',
  收料仓库: 'Receiving Warehouse',
  收料单号: 'Receipt Slip No.',
  收料单已审核: 'Receipt slip approved',
  收料数量: 'Received Qty',
  收料日期: 'Receive Date',
  收款人: 'Payee',
  收款方式: 'Receipt Method',
  收款日期: 'Receipt Date',
  收款账户: 'Receipt Account',
  收款金额: 'Receipt Amount',
  收票: 'Received',
  收货单: 'Receiving Note',
  收货完成: 'Receiving Done',
  收货已完成: 'Receiving completed',
  收货日期: 'Receipt Date',
  数组: 'Array',
  整数: 'Integer',
  文档内容: 'Content',
  文档分类: 'Category',
  文档管理: 'Document Management',
  新增成功: 'Created',
  新密码: 'New Password',
  '新密码长度需为 6-32 位': 'New password must be 6-32 characters',
  新简历: 'New Resume',
  是否启用: 'Enabled',
  更新时间: 'Updated At',
  最大库存阈值: 'Max Stock Threshold',
  最小库存阈值: 'Min Stock Threshold',
  月度: 'Monthly',
  服务名称: 'Service Name',
  期望薪资: 'Expected Salary',
  期间已结账: 'Period closed',
  未开始: 'Not Started',
  未结: 'Unsettled',
  未设置: 'Not Set',
  未读: 'Unread',
  权限名: 'Permission Name',
  权限管理: 'Permission Management',
  材料: 'Material',
  条: 'records',
  来料检验: 'IQC',
  '来料检验 IQC': 'Incoming Inspection IQC',
  来源币种: 'From Currency',
  来源渠道: 'Source',
  标记已读: 'Mark Read',
  模板名称: 'Template Name',
  模板已启用: 'Template enabled',
  模板编码: 'Template Code',
  残值: 'Salvage Value',
  比价: 'Compare',
  汇率值: 'Rate',
  波次已释放: 'Wave released',
  波次释放: 'Release Wave',
  活动名称: 'Campaign Name',
  派单: 'Assign',
  测试投递: 'Test Delivery',
  渠道名称: 'Channel Name',
  漏斗阶段名称: 'Stage Name',
  点检任务: 'Inspection Tasks',
  点检日期: 'Inspection Date',
  父任务: 'Parent Task',
  '父级 ID': 'Parent ID',
  状态已切换: 'Status toggled',
  状态已更新: 'Status updated',
  生产领料: 'Material Issue',
  用户数: 'Users',
  申请人: 'Applicant',
  界面语言: 'Language',
  '登录已过期，请重新登录': 'Session expired, please log in again',
  盘点任务名称: 'Stocktake Name',
  盘点单号: 'Stocktake No.',
  目录: 'Directory',
  目标币种: 'To Currency',
  目标类型: 'Target Type',
  直线法: 'Straight Line',
  看板布局: 'Dashboard Layout',
  确认操作: 'Confirm Action',
  社保规则: 'Social Security Rules',
  票据号: 'Bill No.',
  票面金额: 'Face Amount',
  租户列表: 'Tenants',
  租户已停用: 'Tenant suspended',
  租户已启用: 'Tenant resumed',
  租户管理: 'Tenant Management',
  税号: 'Tax No.',
  税率管理: 'Tax Rates',
  税额: 'Tax Amount',
  第: 'Page',
  签订日期: 'Sign Date',
  算薪: 'Calculate Payroll',
  算薪完成: 'Payroll calculated',
  纳税记录: 'Tax Records',
  线上: 'Online',
  组件名称: 'Widget Name',
  组件类型: 'Widget Type',
  结账: 'Close Period',
  绩效模板: 'Perf Templates',
  绩效考核: 'Performance Review',
  维修工单号: 'Repair Order No.',
  缴费基数上限: 'Base Ceiling',
  缴费基数下限: 'Base Floor',
  考核批次已启动: 'Review started',
  考核批次已归档: 'Review archived',
  考核计划: 'Review Plans',
  考核评分: 'Review Scores',
  '耗时(ms)': 'Elapsed (ms)',
  职位名称: 'Job Title',
  职位已关闭: 'Job closed',
  职位已发布: 'Job published',
  职位编码: 'Position Code',
  联系人名称: 'Contact Name',
  背书: 'Endorse',
  自定义字段: 'Custom Fields',
  自定义报表: 'Custom Reports',
  获取面单: 'Get Label',
  菜单: 'Menu',
  规则名称: 'Rule Name',
  角色名: 'Role Name',
  角色权限: 'Roles',
  计划年度: 'Plan Year',
  计划数: 'Planned Qty',
  计划数量: 'Planned Quantity',
  计划日期: 'Plan Date',
  计划月份: 'Plan Month',
  计划编码: 'Plan Code',
  订单号: 'Order No.',
  订单履约: 'Order Fulfillment',
  订单已取消: 'Order cancelled',
  认领: 'Claim',
  讲师: 'Lecturer',
  设备: 'Equipment',
  设备管理: 'Equipment Management',
  询价单: 'RFQ',
  询价单已关闭: 'RFQ closed',
  请输入当前密码: 'Enter current password',
  请输入登录密码确认操作: 'Enter login password to confirm',
  '课时(小时)': 'Duration (hours)',
  课程标题: 'Course Title',
  课程类型: 'Course Type',
  调出仓库: 'From Warehouse',
  调拨单号: 'Transfer No.',
  调拨日期: 'Transfer Date',
  财务管理: 'Finance Management',
  账套期间: 'Ledger Periods',
  账户编码: 'Account Code',
  质量管理: 'Quality Management',
  购置日期: 'Purchase Date',
  购置金额: 'Purchase Amount',
  贴现: 'Discount',
  费用科目: 'Expense Account',
  费用类型: 'Expense Type',
  资产名称: 'Asset Name',
  资产类别: 'Asset Category',
  资产编号: 'Asset No.',
  资产编码: 'Asset Code',
  资料已保存: 'Profile saved',
  赢单: 'Won',
  跟进中: 'Following Up',
  跟进人: 'Follower',
  轮次: 'Round',
  输单: 'Lost',
  过程检验: 'IPQC',
  '过程检验 IPQC': 'Process Inspection IPQC',
  运单已发货: 'Shipment shipped',
  运算完成: 'MRP run complete',
  运费已支付: 'Freight paid',
  运费已确认: 'Freight confirmed',
  运输服务: 'Transport Services',
  进行中: 'In Progress',
  进项发票池: 'Input Invoice Pool',
  '退换货 RMA': 'Return RMA',
  退货仓库: 'Return Warehouse',
  退货入库: 'Receive Return',
  退货金额: 'Return Amount',
  部门名称: 'Department Name',
  部门编码: 'Department Code',
  配置键: 'Key',
  采购管理: 'Purchase Management',
  采购销售: 'Procurement & Sales',
  释放: 'Release',
  重置密钥: 'Reset Secret',
  销售管理: 'Sales Management',
  集团财务: 'Group Finance',
  面单已生成: 'Label generated',
  面试中: 'Interviewing',
  面试日期: 'Interview Date',
  页: 'of',
  项目名称: 'Project Name',
  项目成本: 'Project Cost',
  项目管理: 'Project Management',
  项目编号: 'Project Code',
  '预到货 ASN': 'ASN',
  预算名称: 'Budget Name',
  预算对比: 'Compare Budget',
  预算年度: 'Budget Year',
  预算额: 'Budget Amount',
  预计金额: 'Expected Amount',
  领料单已审核: 'Issue approved',
  领料日期: 'Issue Date',
  验真: 'Verify',
  '验证失败，请重试': 'Verification failed, please retry',
  搜索菜单: 'Search menus',
  关闭标签: 'Close tab',
  关闭其他标签: 'Close other tabs',
  关闭全部标签: 'Close all tabs',
  关闭其他: 'Close Others',
  关闭全部: 'Close All',
  页面不存在: 'Page Not Found',
  当前路由未注册: 'Route not registered',
  人机验证: 'Captcha',
  点击文字验证: 'Click the characters',
  '验证码加载中…': 'Loading captcha...',
  暂无趋势数据: 'No trend data yet',
  账户状态分布: 'Account Status',
  最近操作日志: 'Recent Logs',
  暂无日志: 'No logs',
  '近 30 天趋势': 'Last 30 Days Trend',
  '已完成人机验证，点击「登 录」继续': 'Captcha verified. Click Log In to continue',
  登录需先完成人机验证: 'Complete the captcha first',
  全部已读: 'Mark All Read',
  请选择: 'Select...',
  '条/页': 'records/page',
  较昨日: 'vs yesterday',
  按顺序点击: 'Click in order',
  '请填写「{label}」': 'Please fill in {label}',
  '新增{name}': 'New {name}',
  '编辑{name}': 'Edit {name}',
  '确定执行「{act}」吗？': 'Execute {act}?',
  '确定删除「{name}」？该操作不可恢复。': 'Delete {name}? This cannot be undone.',
  '请求失败（{code}）': 'Request failed ({code})',
  '下载失败（{code}）': 'Download failed ({code})',
  'Open ERP · Web 控制台': 'Open ERP · Web Console',
  业务模块: 'Modules',
  中英切换: 'Chinese / English',
  '第 {count} 个字位置不准，请再点一次': 'Click #{count} again - the point missed the target',
  '仍未通过，请按顺序重新点击': 'Still not matched - click all characters in order again',
};
