/*
 * Copyright (c) 2026 erik <erik@erik.xyz> — https://erik.xyz
 */

/**
 * 中文原文 → Indonesian 词典（id）。由 scripts/gen-fe-locales.mjs 生成，**请勿手工编辑**。
 * 缺词条时回退中文原文；键集须与 core/zh-en 完全一致。
 */
export const zhId: Record<string, string> = {
  ':attribute 不存在': ':attribute tidak ada',
  ':attribute 不能为空': 'Bidang :attribute wajib diisi',
  ':attribute 不能大于 :max': ':attribute tidak boleh melebihi :max',
  ':attribute 不能小于 :min': ':attribute minimal :min',
  ':attribute 值无效': 'Nilai :attribute tidak valid',
  ':attribute 已存在': ':attribute sudah ada',
  ':attribute 必须是字符串': ':attribute harus berupa string',
  ':attribute 必须是数字': ':attribute harus berupa angka',
  ':attribute 必须是整数': ':attribute harus berupa bilangan bulat',
  ':attribute 格式不正确': 'Format :attribute tidak valid',
  'BOM管理': 'Manajemen BOM',
  'JSON 对象，含 current_assets、current_liabilities、total_liabilities、total_assets 字段，值为数字': 'Objek JSON dengan nilai numerik untuk current_assets, current_liabilities, total_liabilities, dan total_assets',
  'JSON 对象，含 net_profit、revenue 字段，值为数字': 'Objek JSON dengan nilai numerik untuk net_profit dan revenue',
  'MRP计划': 'Perencanaan MRP',
  'OMS 订单': 'Pesanan OMS',
  'OMS订单': 'Pesanan OMS',
  'Token已过期': 'Token kedaluwarsa',
  'Token无效': 'Token tidak valid',
  'X坐标': 'Posisi X',
  'YYYY-MM-DD，如 2026-09-05': 'YYYY-MM-DD, mis. 2026-09-05',
  'Y坐标': 'Posisi Y',
  'erp开放管理后台': 'Buka Admin ERP',
  'erp管理后台': 'Buka Admin ERP',
  '{field} 不是合法 JSON': '{field} bukan JSON yang valid',
  '{field} 必须为 JSON 对象': '{field} harus berupa objek JSON',
  '{field} 必须为 JSON 数组': '{field} harus berupa array JSON',
  '{page} / {pages} ({total}条)': '{page} / {pages} ({total})',
  '一个平台，管好全部业务': 'Satu platform untuk semua bisnis Anda',
  '上传成功': 'Unggah berhasil',
  '上架管理': 'Penempatan',
  '上次保养日期': 'Tanggal Pemeliharaan Terakhir',
  '下单时间': 'Tanggal Pesanan',
  '下次保养日期': 'Tanggal Pemeliharaan Berikutnya',
  '下次日期': 'Tanggal Berikutnya',
  '不合格品': 'Produk Tidak Sesuai',
  '不合格数量': 'Jumlah Ditolak',
  '不合格编号': 'No. Cacat',
  '两次密码不一致': 'Kata sandi tidak cocok',
  '严重程度': 'Tingkat Keparahan',
  '个人中心': 'Profil',
  '个人信息更新成功': 'Profil berhasil diperbarui',
  '个人所得税': 'Pajak Penghasilan Pribadi',
  '个税': 'Pajak Penghasilan',
  '主题': 'Subjek',
  '买家备注': 'Catatan Pembeli',
  '事假': 'Cuti Pribadi',
  '产假': 'Cuti Melahirkan',
  '人力资源': 'SDM',
  '从供应商列表页获取数字ID': 'ID numerik dari halaman daftar pemasok',
  '从员工列表页获取数字ID': 'ID numerik dari halaman daftar karyawan',
  '从客户列表页获取数字ID': 'ID numerik dari halaman daftar pelanggan',
  '从科目列表获取数字ID，填了则按明细创建': 'ID numerik dari halaman daftar akun; jika diisi, voucher dibuat dengan item baris',
  '从销售订单列表页获取数字ID': 'ID numerik dari halaman daftar pesanan penjualan',
  '仓储管理': 'Manajemen Gudang',
  '仓库': 'Gudang',
  '仓库信息': 'Info Gudang',
  '付款单': 'Pembayaran',
  '付款单ID': 'ID Pembayaran',
  '付款单号': 'No. Pembayaran',
  '付款时间': 'Dibayar Pada',
  '付款管理': 'Pembayaran',
  '仪表盘': 'Dasbor',
  '价格': 'Harga',
  '任务': 'Tugas',
  '任务管理': 'Tugas',
  '企业所得税': 'Pajak Penghasilan Badan',
  '优先级': 'Prioritas',
  '优惠金额': 'Jumlah Diskon',
  '会计科目': 'Bagan Akun',
  '低库存预警': 'Peringatan Stok Rendah',
  '余额': 'Saldo',
  '供应商': 'Pemasok',
  '供应商ID': 'ID Pemasok',
  '供应商信息': 'Info Pemasok',
  '保修到期': 'Kedaluwarsa Garansi',
  '保养计划': 'Rencana Pemeliharaan',
  '保养频率': 'Frekuensi Pemeliharaan',
  '保存': 'Simpan',
  '保存失败: {error}': 'Gagal menyimpan: {error}',
  '保存成功': 'Berhasil disimpan',
  '修改失败: {error}': 'Gagal mengubah: {error}',
  '修改密码': 'Ubah Kata Sandi',
  '借': 'Debit',
  '借方合计': 'Total Debit',
  '值': 'Nilai',
  '全部': 'Semua',
  '公海池': 'Kumpulan Lead',
  '公积金': 'Dana Perumahan',
  '共 {count} 个': '{count} total',
  '共 {total} 条': '{total} catatan',
  '关联订单': 'Pesanan Terkait',
  '关联销售订单ID': 'ID Pesanan Penjualan Tertaut',
  '关闭': 'Tutup',
  '其他': 'Lainnya',
  '内容': 'Konten',
  '冻结时间': 'Tahan Hingga',
  '净利率': 'Margin Bersih',
  '凭证ID: {id}': 'ID Voucher: {id}',
  '凭证号': 'No. Voucher',
  '凭证名称': 'Nama Voucher',
  '凭证日期': 'Tanggal Voucher',
  '出入库流水': 'Pergerakan Stok',
  '出货检验(OQC)': 'Inspeksi Keluar (OQC)',
  '分区拣货': 'Ambil per Zona',
  '分类': 'Kategori',
  '分组': 'Grup',
  '分配中': 'Mengalokasikan',
  '分配库存': 'Alokasikan Stok',
  '分配数量不能为空': 'Kuantitas wajib diisi',
  '分配数量须为正数': 'Kuantitas harus berupa angka positif',
  '创建失败: {error}': 'Gagal membuat: {error}',
  '创建履约': 'Buat Pemenuhan',
  '创建成功': 'Berhasil dibuat',
  '创建时间': 'Dibuat Pada',
  '删除': 'Hapus',
  '删除({count})': 'Hapus ({count})',
  '删除失败: {error}': 'Gagal menghapus: {error}',
  '删除成功': 'Berhasil dihapus',
  '利润': 'Laba',
  '利润中心': 'Pusat Laba',
  '利润报表': 'Laporan Laba',
  '利润表 JSON *': 'Laporan Laba Rugi JSON *',
  '到期日': 'Jatuh Tempo',
  '刷新': 'Muat Ulang',
  '加班费': 'Upah Lembur',
  '加载中...': 'Memuat...',
  '加载失败': 'Gagal memuat',
  '加载失败: {error}': 'Gagal memuat: {error}',
  '加载权限列表失败: {error}': 'Gagal memuat izin: {error}',
  '加载用户列表失败: {error}': 'Gagal memuat pengguna: {error}',
  '加载角色列表失败: {error}': 'Gagal memuat peran: {error}',
  '包装类型': 'Jenis Paket',
  '单价': 'Harga',
  '单位': 'Satuan',
  '单据ID': 'ID Dokumen',
  '单据ID必须为数字': 'ID Dokumen harus berupa angka',
  '单据类型': 'Jenis Dokumen',
  '卖家备注': 'Catatan Penjual',
  '印花税': 'Bea Meterai',
  '原因': 'Alasan',
  '原币ID': 'ID Mata Uang Sumber',
  '参数(JSON)': 'Parameter (JSON)',
  '参数验证失败': 'Validasi gagal',
  '发放': 'Bayar',
  '发放失败：{error}': 'Pembayaran gagal: {error}',
  '发货仓库ID': 'ID Gudang Pengiriman',
  '发货单ID': 'ID Pengiriman',
  '发货单号': 'No. Pengiriman',
  '取消': 'Batal',
  '取消订单': 'Batalkan Pesanan',
  '变更说明': 'Catatan Perubahan',
  '合同名称': 'Nama Kontrak',
  '合同状态流转': 'Transisi Status Kontrak',
  '合同管理': 'Kontrak',
  '合同编号': 'No. Kontrak',
  '合并中...': 'Mengonsolidasikan...',
  '合并报表': 'Laporan Konsolidasi',
  '合格数量': 'Jumlah Lulus',
  '名称': 'Nama',
  '后端要求提供发货仓库': 'Server memerlukan gudang pengiriman',
  '否': 'No',
  '启用': 'Aktifkan',
  '员工': 'Karyawan',
  '员工ID': 'ID Karyawan',
  '员工档案': 'Karyawan',
  '品牌': 'Merek',
  '品牌管理': 'Merek',
  '商品': 'Produk',
  '商品ID': 'ID Produk',
  '商品ID须为正整数': 'ID Produk harus berupa bilangan bulat positif',
  '商品ID（数字）': 'ID Produk (numerik)',
  '商品信息': 'Info Produk',
  '商品分类': 'Kategori',
  '商品列表': 'Daftar Produk',
  '商品名称': 'Nama Produk',
  '商品明细': 'Item',
  '商品编码': 'Kode Produk',
  '商机': 'Peluang',
  '商机管理': 'Peluang',
  '商品规格': 'Spesifikasi Produk',
  '固定': 'Tetap',
  '固定资产': 'Aset Tetap',
  '图表名称': 'Nama Bagan',
  '图表管理': 'Kelola Bagan',
  '图表管理 — {name}': 'Kelola Bagan — {name}',
  '图表类型': 'Jenis Bagan',
  '地址': 'Alamat',
  '地点': 'Lokasi',
  '型号': 'Model',
  '基本信息': 'Info Dasar',
  '基本工资': 'Gaji Pokok',
  '增值税': 'Pajak Pertambahan Nilai',
  '处置方式': 'Disposisi',
  '备件': 'Suku Cadang',
  '备件名称': 'Nama Suku Cadang',
  '备件编码': 'Kode Suku Cadang',
  '备注': 'Catatan',
  '多币种/汇率': 'Multi-Mata Uang / Kurs Valas',
  '天数': 'Hari',
  '失效日期': 'Berlaku Hingga',
  '如 1.5': 'mis. 1,5',
  '如 10.00': 'mis. 10,00',
  '如 100.00': 'mis. 100,00',
  '如 1000.00': 'mis. 1.000,00',
  '如 61000000000000001=CNY': 'mis. 61000000000000001=CNY',
  '如 7.250000': 'mis. 7,250000',
  '如 8000.00': 'mis. 8.000,00',
  '如 purchase_order / expense': 'mis. purchase_order / expense',
  '如 {amount}': 'mis. {amount}',
  '姓名': 'Nama Karyawan',
  '婚假': 'Cuti Menikah',
  '子公司报表 JSON 数组 *': 'Array JSON Laporan Anak Perusahaan *',
  '存放位置': 'Lokasi',
  '季': 'Kuartal',
  '完成': 'Selesai',
  '定时调度': 'Jadwal',
  '实发工资': 'Gaji Bersih',
  '实时库存': 'Stok Tersedia',
  '审批': 'Setujui',
  '审批中': 'Menyetujui',
  '审批工作流': 'Alur Kerja',
  '审批意见为必填项': 'Komentar persetujuan wajib diisi',
  '审批意见（必填）': 'Komentar Persetujuan (wajib)',
  '审批意见（选填）': 'Komentar Persetujuan (opsional)',
  '审批流程': 'Alur Kerja',
  '审批记录': 'Catatan Persetujuan',
  '客户': 'Pelanggan',
  '客户ID': 'ID Pelanggan',
  '客户信息': 'Info Pelanggan',
  '客户分析': 'Analitik Pelanggan',
  '宽度': 'Lebar',
  '密码': 'Kata Sandi',
  '密码修改成功': 'Kata sandi berhasil diubah',
  '密码验证失败': 'Verifikasi kata sandi gagal',
  '导入失败': 'Impor gagal',
  '导入成功': 'Impor berhasil',
  '导出': 'Ekspor',
  '导出Excel': 'Ekspor Excel',
  '导出PDF': 'Ekspor PDF',
  '导出成功': 'Ekspor berhasil',
  '展开菜单': 'Perluas menu',
  '履约': 'Penuhi',
  '履约单': 'Pemenuhan',
  '履约状态': 'Status Pemenuhan',
  '履约管理': 'Pemenuhan',
  '工作日期': 'Tanggal Kerja',
  '工作流定义': 'Alur Kerja',
  '工作站': 'Stasiun Kerja',
  '工作站ID': 'ID Stasiun Kerja',
  '工单ID': 'ID Perintah Kerja',
  '工单编码': 'Kode Perintah Kerja',
  '工序号': 'Urut',
  '工时': 'Lembar Waktu',
  '工时(小时)': 'Jam',
  '工时记录': 'Lembar Waktu',
  '工艺路线': 'Rute',
  '已付金额': 'Jumlah Dibayar',
  '已入库': 'Diterima',
  '已关闭': 'Ditutup',
  '已出库': 'Diterbitkan',
  '已分配': 'Ditugaskan',
  '已发放': 'Dibayar',
  '已发货': 'Dikirim',
  '已取件': 'Diambil',
  '已取消': 'Dibatalkan',
  '已失效': 'Kedaluwarsa',
  '已完成': 'Selesai',
  '已审批': 'Disetujui',
  '已审核': 'Ditinjau',
  '已打包': 'Dikemas',
  '已打款': 'Dibayar',
  '已批准': 'Disetujui',
  '已报价': 'Dikutip',
  '已拒绝': 'Ditolak',
  '已拣货': 'Diambil',
  '已撤回': 'Ditarik',
  '已支付': 'Dibayar',
  '已收货': 'Diterima',
  '已收金额': 'Jumlah Diterima',
  '已核销': 'Lunas',
  '已点击 {count}/{total}': 'Diklik {count}/{total}',
  '已签收': 'Ditandatangani',
  '已终止': 'Dihentikan',
  '已结算': 'Selesai',
  '已转订单': 'Dikonversi menjadi Pesanan',
  '已退回': 'Dikembalikan',
  '已退款': 'Dana Dikembalikan',
  '已送达': 'Terkirim',
  '已通过': 'Disetujui',
  '已驳回': 'Ditolak',
  '币种': 'Mata Uang',
  '币种列表中的数字ID，如 61000000000000002=USD': 'ID numerik dari daftar mata uang, mis. 61000000000000002=USD',
  '布局配置': 'Konfigurasi Tata Letak',
  '年': 'Tahun',
  '年份': 'Tahun',
  '年假': 'Cuti Tahunan',
  '年度': 'Tahun',
  '序列号': 'Nomor Seri',
  '库位': 'Lokasi',
  '库位管理': 'Manajemen Lokasi',
  '库区': 'Zona',
  '库区管理': 'Zona',
  '库存': 'Persediaan',
  '库存不足': 'Stok tidak mencukupi',
  '库存总值': 'Nilai Persediaan',
  '库存数量': 'Jumlah Stok',
  '库存流水': 'Pergerakan Stok',
  '库存调拨': 'Transfer Stok',
  '库存预警': 'Peringatan Stok',
  '应付': 'Utang',
  '应付账龄': 'Umur Utang',
  '应付金额': 'Jumlah Utang',
  '应发工资': 'Gaji Bruto',
  '应收': 'Piutang',
  '应收应付': 'Piutang/Utang',
  '应收账龄': 'Umur Piutang',
  '应收金额': 'Jumlah Piutang',
  '应纳税所得额': 'Penghasilan Kena Pajak',
  '开始日期': 'Tanggal Mulai',
  '开始时间': 'Waktu Mulai',
  '开始维修': 'Mulai Perbaikan',
  '开户银行': 'Nama Bank',
  '异常': 'Pengecualian',
  '当前状态不允许此操作': 'Operasi tidak diizinkan dalam status saat ini',
  '当前状态无可流转的目标状态': 'Tidak ada status target yang tersedia untuk status saat ini',
  '当前节点': 'Node Saat Ini',
  '往来单位': 'Pihak Lawan',
  '往来单位与所选类型不匹配，请重新选择': 'Pihak Lawan tidak cocok dengan tipe yang dipilih, silakan pilih ulang',
  '待入库': 'Menunggu Penerimaan',
  '待出库': 'Menunggu Pengeluaran',
  '待发货': 'Siap Kirim',
  '待处理': 'Menunggu',
  '待审批': 'Menunggu',
  '待审核': 'Menunggu Tinjauan',
  '待打包': 'Menunggu Pengemasan',
  '待拣货': 'Menunggu Pengambilan',
  '待支付': 'Menunggu Pembayaran',
  '微信': 'WeChat',
  '必填（后端校验）': 'Wajib (divalidasi oleh server)',
  '必填（后端校验），如 OM+时间戳': 'Wajib (divalidasi oleh server), mis. OM+timestamp',
  '总览': 'Ikhtisar',
  '总账/明细账': 'Buku Besar Umum / Detail',
  '总金额': 'Jumlah Total',
  '恢复成功': 'Berhasil dipulihkan',
  '成功': 'Berhasil',
  '成本/利润中心': 'Pusat Biaya / Laba',
  '成本中心': 'Pusat Biaya',
  '成本价': 'Biaya Satuan',
  '我的审批': 'Persetujuan Saya',
  '截止重量(kg)': 'Berat Hingga (kg)',
  '所有者权益': 'Ekuitas Pemilik',
  '手机号': 'Telepon',
  '打包中': 'Pengemasan',
  '打包任务': 'Tugas Pengemasan',
  '打包单': 'Tugas Pengemasan',
  '打包管理': 'Pengemasan',
  '扣款': 'Potongan',
  '执行': 'Jalankan',
  '执行中': 'Aktif',
  '执行合并': 'Jalankan Konsolidasi',
  '执行失败：{error}': 'Eksekusi gagal: {error}',
  '批准': 'Setujui',
  '批准时间': 'Disetujui Pada',
  '批准请假': 'Setujui Cuti',
  '批次号': 'No. Batch',
  '批量删除失败: {error}': 'Hapus batch gagal: {error}',
  '批量删除完成': 'Pengguna terpilih dihapus',
  '批量删除成功': 'Hapus batch berhasil',
  '批量启用': 'Aktifkan Terpilih',
  '批量启用完成': 'Pengguna terpilih diaktifkan',
  '批量拣货': 'Pilih per Batch',
  '批量操作成功': 'Operasi batch berhasil',
  '批量禁用': 'Nonaktifkan Terpilih',
  '批量禁用完成': 'Pengguna terpilih dinonaktifkan',
  '承运商': 'Kurir',
  '承运商服务': 'Layanan Kurir',
  '承运服务': 'Layanan Kurir',
  '投资活动净额': 'Arus Kas Investasi Bersih',
  '投资活动流入': 'Arus Masuk Investasi',
  '投资活动流出': 'Arus Keluar Investasi',
  '折旧年份': 'Tahun Penyusutan',
  '折旧月份': 'Bulan Penyusutan',
  '折旧计提成功': 'Penyusutan dicatat',
  '报价单': 'Penawaran',
  '报价单号': 'No. Penawaran',
  '报价时间': 'Ditawarkan Pada',
  '报价转合同': 'Penawaran ke Kontrak',
  '报价金额': 'Jumlah Penawaran',
  '报告人': 'Pelapor',
  '报表': 'Laporan',
  '报表名称': 'Nama Laporan',
  '报表管理': 'Laporan',
  '报表类型': 'Jenis Laporan',
  '报表结果：{name}': 'Hasil Laporan: {name}',
  '报表说明: {note}': 'Catatan laporan: {note}',
  '抽样方案': 'Rencana Sampling',
  '拒绝': 'Tolak',
  '拣货中': 'Pengambilan',
  '拣货任务': 'Tugas Pengambilan',
  '拣货单': 'Tugas Pengambilan',
  '拣货管理': 'Pengambilan',
  '指标名称': 'Nama Metrik',
  '指标类型': 'Jenis Metrik',
  '指标键名': 'Kunci Metrik',
  '指派': 'Tugaskan',
  '指派人': 'Penerima Tugas',
  '指派工单': 'Tugaskan Tiket',
  '按单拣货': 'Ambil berdasarkan Pesanan',
  '换一张': 'Segarkan',
  '换货': 'Tukar',
  '排序': 'Urutan Sortir',
  '接收人': 'Penerima',
  '描述': 'Deskripsi',
  '提交': 'Kirim',
  '提交中...': 'Mengirim...',
  '提交人': 'Dikirim Oleh',
  '提交失败：{error}': 'Gagal mengirim: {error}',
  '提交审批': 'Ajukan untuk Persetujuan',
  '提交审批：{name}': 'Ajukan untuk Persetujuan: {name}',
  '提交成功': 'Berhasil dikirim',
  '提交时间': 'Dikirim Pada',
  '提示': 'Info',
  '搜索': 'Cari',
  '搜索...': 'Cari...',
  '搜索商品名称/编码/批次号': 'Cari nama produk, kode, atau batch',
  '搜索用户名/姓名': 'Cari nama pengguna/nama',
  '摘要': 'Ringkasan',
  '撤回': 'Tarik',
  '撤回失败: {error}': 'Gagal menarik: {error}',
  '撤回审批': 'Penarikan Persetujuan',
  '操作': 'Tindakan',
  '操作失败': 'Operasi gagal',
  '操作失败，请重试': 'Operasi gagal, silakan coba lagi',
  '操作失败：{error}': 'Operasi gagal: {error}',
  '操作成功': 'Operasi berhasil',
  '操作日志': 'Log Operasi',
  '操作筛选': 'Filter berdasarkan tindakan',
  '操作者': 'Operator',
  '支付宝': 'Alipay',
  '支付状态': 'Status Pembayaran',
  '收入结转': 'Pembawaan Pendapatan',
  '收款单': 'Kwitansi',
  '收款单ID': 'ID Kwitansi',
  '收款单号': 'No. Kwitansi',
  '收款时间': 'Diterima Pada',
  '收款管理': 'Kwitansi',
  '收货仓库ID': 'ID Gudang Penerimaan',
  '收货单ID': 'ID Penerimaan',
  '收货单号': 'No. Penerimaan',
  '收货时间': 'Diterima Pada',
  '收货管理': 'Penerimaan',
  '收起菜单': 'Tutup menu',
  '故障描述': 'Deskripsi Kesalahan',
  '敏感操作需要输入密码确认': 'Konfirmasi kata sandi diperlukan untuk operasi sensitif',
  '数据趋势（近30天）': 'Tren Data (30 Hari Terakhir)',
  '数据集': 'Kumpulan Data',
  '数据集ID': 'ID Dataset',
  '数据集ID: {value}': 'ID Dataset: {value}',
  '数据集名称': 'Nama Dataset',
  '数量': 'Jumlah',
  '文档列表': 'Daftar Dokumen',
  '文档标题': 'Judul Dokumen',
  '文档编码': 'Kode Dokumen',
  '新增': 'Tambah',
  '新增OMS订单': 'Tambah Pesanan OMS',
  '新增图表': 'Tambah Grafik',
  '新增报价单': 'Tambah Penawaran',
  '新增汇率': 'Tambah Kurs',
  '新增用户': 'Tambah Pengguna',
  '新增结算': 'Tambah Penyelesaian',
  '新增薪资记录': 'Tambah Catatan Gaji',
  '新增薪资项': 'Tambah Item Gaji',
  '新增角色': 'Tambah Peran',
  '新增记账凭证': 'Tambah Voucher',
  '新增请假': 'Tambah Cuti',
  '新增账户': 'Tambah Akun',
  '新增跟进': 'Tambah Tindak Lanjut',
  '新增跟进记录': 'Tambah Tindak Lanjut',
  '新增配置': 'Tambah Pengaturan',
  '新增采购申请': 'Tambah Permintaan Pembelian',
  '新增采购结算（付款核销）': 'Tambah Penyelesaian Pembelian (penghapusan pembayaran)',
  '新增采购订单': 'Tambah Pesanan Pembelian',
  '新增银行账户': 'Tambah Rekening Bank',
  '新增销售结算（收款核销）': 'Tambah Penyelesaian Penjualan (penghapusan penerimaan)',
  '新增销售订单': 'Tambah Pesanan Penjualan',
  '新增阶段': 'Tambah Tahap',
  '新密码 (6-32位)': 'Kata Sandi Baru (6-32 karakter)',
  '新密码（留空不修改）': 'Kata sandi baru (biarkan kosong agar tidak berubah)',
  '新建指标': 'Metrik Baru',
  '方向': 'Arah',
  '方式': 'Metode',
  '方法': 'Metode',
  '无效的ID': 'ID Tidak Valid',
  '无权限访问': 'Akses ditolak',
  '日期': 'Tanggal',
  '旧密码': 'Kata Sandi Lama',
  '时间': 'Waktu',
  '明细-借方金额': 'Debit Item',
  '明细-摘要': 'Ringkasan Item',
  '明细-科目ID': 'ID Akun Item',
  '明细-贷方金额': 'Kredit Item',
  '明细分类账': 'Buku Besar Pembantu',
  '是': 'Ya',
  '是否计税(0/1)': 'Kena Pajak (0/1)',
  '暂无可选用户': 'Tidak ada pengguna yang dapat ditugaskan',
  '暂无图表，点击「新增图表」创建': 'Belum ada bagan; klik "Tambah Bagan" untuk membuatnya',
  '暂无数据': 'Tidak ada data',
  '暂无明细数据': 'Tidak ada data detail',
  '暂无角色': 'Belum ada peran',
  '更新失败: {error}': 'Pembaruan gagal: {error}',
  '更新成功': 'Berhasil diperbarui',
  '最低': 'Terendah',
  '最低库存': 'Stok Min',
  '最后登录': 'Login Terakhir',
  '最近操作': 'Operasi Terbaru',
  '最高': 'Tertinggi',
  '最高库存': 'Stok Maks',
  '月': 'Bulan',
  '月份': 'Bulan',
  '服务器内部错误': 'Kesalahan server internal',
  '服务工单': 'Tiket Layanan',
  '期初借方': 'Debit Awal',
  '期初现金': 'Kas Awal',
  '期初贷方': 'Kredit Awal',
  '期末借方': 'Debit Akhir',
  '期末现金': 'Kas Akhir',
  '期末结转': 'Penutupan Akhir Periode',
  '期末贷方': 'Kredit Akhir',
  '期间': 'Periode',
  '期间 YYYY-MM': 'Periode YYYY-MM',
  '期间 YYYY-MM(可选)': 'Periode YYYY-MM (opsional)',
  '期间值': 'Nilai Periode',
  '期间类型': 'Tipe Periode',
  '未分配': 'Belum Ditugaskan',
  '未发放': 'Belum Dibayar',
  '未填写则留空': 'Biarkan kosong agar tidak berubah',
  '未授权访问': 'Tidak Diizinkan',
  '未核销': 'Belum Diselesaikan',
  '未知': 'Tidak Diketahui',
  '未结算': 'Belum Diselesaikan',
  '本位币': 'Mata Uang Dasar',
  '本年利润': 'Laba Tahun Berjalan',
  '本期借方': 'Debit Berjalan',
  '本期贷方': 'Kredit Berjalan',
  '权限': 'Izin',
  '权限分配:': 'Izin:',
  '条码': 'Barcode',
  '来料检验(IQC)': 'Inspeksi Masuk (IQC)',
  '来源': 'Sumber',
  '来源类型': 'Tipe Sumber',
  '来源记录ID': 'ID Sumber',
  '查看单据': 'Lihat Dokumen',
  '查询': 'Kueri',
  '查询SQL': 'Kueri SQL',
  '查询中...': 'Mengkueri...',
  '查询成功，暂无数据行': 'Kueri berhasil, tidak ada baris hasil',
  '标准名称': 'Nama Standar',
  '标准编码': 'Kode Standar',
  '标签': 'Tag',
  '标记全部已读': 'Tandai Semua sebagai Sudah Dibaca',
  '标识': 'Slug',
  '标识: {slug} | 用户数: {count} | {desc}': 'Slug: {slug} | Pengguna: {count} | {desc}',
  '标题': 'Judul',
  '核销金额': 'Jumlah Penghapusan',
  '根本原因': 'Akar Masalah',
  '格式 YYYY-MM-DD': 'Format YYYY-MM-DD',
  '格式 YYYY-MM-DD HH:mm:ss': 'Format YYYY-MM-DD HH:mm:ss',
  '格式 YYYY-MM-DD HH:mm:ss，可留空': 'Format YYYY-MM-DD HH:mm:ss, opsional',
  '检验/合格/不合格': 'Diperiksa/Lulus/Ditolak',
  '检验单号': 'No. Inspeksi',
  '检验员': 'Inspektur',
  '检验数量': 'Jumlah Diperiksa',
  '检验标准': 'Standar Inspeksi',
  '检验标准ID': 'ID Standar Inspeksi',
  '检验类型': 'Jenis Inspeksi',
  '检验结果': 'Hasil Inspeksi',
  '检验规格': 'Spesifikasi Inspeksi',
  '模块': 'Modul',
  '模板': 'Templat',
  '模板ID': 'ID Templat',
  '正常': 'Normal',
  '每公斤单价': 'Tarif per kg',
  '每周': 'Mingguan',
  '每天': 'Harian',
  '每月': 'Bulanan',
  '汇兑损益': 'Keuntungan/Kerugian Selisih Kurs',
  '汇率': 'Kurs',
  '汇率管理': 'Kurs',
  '没有需要保存的修改': 'Tidak ada perubahan untuk disimpan',
  '波次拣货': 'Picking per Gelombang',
  '波次管理': 'Gelombang',
  '派送中': 'Dalam Pengiriman',
  '流动比率': 'Rasio Lancar',
  '流动负债': 'Liabilitas Lancar',
  '流动资产': 'Aset Lancar',
  '流转': 'Transisi',
  '浮动': 'Variabel',
  '渠道': 'Kanal',
  '渠道店铺名称': 'Nama Toko Kanal',
  '渠道管理': 'Kanal',
  '渠道订单号': 'No. Pesanan Saluran',
  '热销商品 TOP 5': '5 Produk Teratas',
  '燃油附加费(%)': 'Biaya Tambahan Bahan Bakar (%)',
  '版本': 'Versi',
  '物流轨迹': 'Pelacakan',
  '状态': 'Status',
  '状态流转': 'Transisi Status',
  '状态流转成功': 'Status dialihkan',
  '现金': 'Kas',
  '现金日记账': 'Jurnal Kas',
  '现金流量表': 'Laporan Arus Kas',
  '生产制造': 'Manufaktur',
  '生产工单': 'Perintah Produksi',
  '生产工单ID': 'ID Perintah Kerja',
  '生成报表': 'Buat Laporan',
  '生成时间': 'Dibuat Pada',
  '生成时间: {value}': 'Dibuat pada: {value}',
  '生效日期': 'Tanggal Efektif',
  '用户': 'Pengguna',
  '用户ID': 'ID Pengguna',
  '用户创建成功': 'Pengguna dibuat',
  '用户名': 'Nama Pengguna',
  '用户名或密码错误': 'Nama pengguna atau kata sandi salah',
  '用户更新成功': 'Pengguna diperbarui',
  '用户状态分布': 'Distribusi Status Pengguna',
  '用户管理': 'Pengguna',
  '申请人ID': 'ID Pemohon',
  '申请单号': 'No. Permintaan',
  '申请部门': 'Departemen',
  '电话': 'Telepon',
  '留空为0': 'Biarkan kosong untuk 0',
  '留空自动生成 CT+时间戳': 'Biarkan kosong untuk menghasilkan otomatis CT+timestamp',
  '留空自动生成 PA+时间戳': 'Biarkan kosong untuk menghasilkan otomatis PA+timestamp',
  '留空自动生成 PAY+时间戳': 'Biarkan kosong untuk menghasilkan otomatis PAY+timestamp',
  '留空自动生成 PO+时间戳': 'Biarkan kosong untuk menghasilkan otomatis PO+timestamp',
  '留空自动生成 PRN+时间戳': 'Otomatis PRN+timestamp jika kosong',
  '留空自动生成 QT+时间戳': 'Biarkan kosong untuk menghasilkan otomatis QT+timestamp',
  '留空自动生成 RCV+时间戳': 'Biarkan kosong untuk menghasilkan otomatis RCV+timestamp',
  '留空自动生成 SO+时间戳': 'Biarkan kosong untuk menghasilkan otomatis SO+timestamp',
  '留空自动生成 SRN+时间戳': 'Otomatis SRN+timestamp jika kosong',
  '留空自动生成 VCH+时间戳': 'Biarkan kosong untuk membuat VCH+timestamp otomatis',
  '留空默认 合同-报价单号': 'Biarkan kosong untuk default ke No. Kontrak-penawaran',
  '病假': 'Cuti Sakit',
  '登 录': 'Masuk',
  '登出成功': 'Berhasil keluar',
  '登录失败': 'Gagal masuk',
  '登录成功': 'Berhasil masuk',
  '登录状态已失效，请重新登录': 'Sesi berakhir, silakan masuk lagi',
  '盘点': 'Stok Opname',
  '盘点任务': 'Stok Opname',
  '目标币ID': 'ID Mata Uang Target',
  '目标状态': 'Status Target',
  '目的区域': 'Zona Tujuan',
  '目的国家': 'Negara Tujuan',
  '看板名称': 'Nama Dasbor',
  '真实姓名': 'Nama Asli',
  '确定': 'OK',
  '确定执行「{action}」？': 'Konfirmasi “{action}”?',
  '确定要删除「{name}」吗？': 'Anda yakin ingin menghapus "{name}"?',
  '确定要删除图表「{name}」吗？': 'Anda yakin ingin menghapus grafik "{name}"?',
  '确定要删除用户「{name}」吗？': 'Anda yakin ingin menghapus pengguna "{name}"?',
  '确定要删除角色「{name}」吗？': 'Anda yakin ingin menghapus peran "{name}"?',
  '确定要删除该汇率记录吗？': 'Anda yakin ingin menghapus nilai tukar ini?',
  '确定要删除该薪资记录吗？': 'Anda yakin ingin menghapus catatan penggajian ini?',
  '确定要删除该请假记录吗？': 'Anda yakin ingin menghapus catatan cuti ini?',
  '确定要删除该采购结算记录吗？': 'Anda yakin ingin menghapus catatan penyelesaian pembelian ini?',
  '确定要删除该销售结算记录吗？': 'Anda yakin ingin menghapus catatan penyelesaian penjualan ini?',
  '确定要删除选中的 {count} 个用户吗？': 'Hapus {count} pengguna terpilih?',
  '确定要删除配置「{key}」吗？': 'Anda yakin ingin menghapus pengaturan "{key}"?',
  '确定要删除银行账户「{name}」吗？': 'Anda yakin ingin menghapus rekening bank "{name}"?',
  '确定要将工单「{code}」流转为「{status}」吗？': 'Pindahkan perintah kerja "{code}" ke "{status}"?',
  '确定要撤回该审批吗？': 'Tarik permintaan persetujuan ini?',
  '确定要退出登录吗？': 'Anda yakin ingin keluar?',
  '确定退出': 'Konfirmasi',
  '确认': 'Konfirmasi',
  '确认删除': 'Konfirmasi Hapus',
  '确认发放': 'Konfirmasi Pembayaran',
  '确认将「{period}」的薪资标记为已发放吗？': 'Tandai gaji untuk "{period}" sebagai sudah dibayar?',
  '确认批准该请假申请吗？': 'Setujui permintaan cuti ini?',
  '确认批量删除': 'Konfirmasi Hapus Massal',
  '确认收货': 'Konfirmasi Penerimaan',
  '确认新密码': 'Konfirmasi Kata Sandi Baru',
  '确认解决': 'Konfirmasi Penyelesaian',
  '确认计提': 'Konfirmasi',
  '确认退出': 'Konfirmasi Keluar',
  '确认驳回该请假申请吗？': 'Tolak permintaan cuti ini?',
  '社保(个人)': 'Asuransi Sosial (karyawan)',
  '禁用': 'Nonaktifkan',
  '科目ID': 'ID Akun',
  '科目余额': 'Saldo Akun',
  '税务管理': 'Pajak',
  '税率': 'Tarif Pajak',
  '第 {page} 页 / 共 {pages} 页 ({total} 条)': 'Halaman {page} dari {pages} ({total} catatan)',
  '等级': 'Level',
  '筹资活动净额': 'Arus Kas Bersih dari Pendanaan',
  '筹资活动流入': 'Arus Masuk Pendanaan',
  '筹资活动流出': 'Arus Keluar Pendanaan',
  '管理后台': 'Konsol Admin',
  '管理员': 'Administrator',
  '类型': 'Tipe',
  '类型(0=固定 1=浮动)': 'Tipe (0=tetap 1=variabel)',
  '类型: {type}': 'Tipe: {type}',
  '系统': 'Sistem',
  '系统管理': 'Sistem',
  '系统配置': 'Konfigurasi Sistem',
  '纠正措施': 'Tindakan Korektif',
  '经营': 'Bisnis',
  '经营活动净额': 'Arus Kas Bersih Operasional',
  '经营活动流入': 'Arus Masuk Operasional',
  '经营活动流出': 'Arus Keluar Operasional',
  '结束日期': 'Tanggal Berakhir',
  '结束时间': 'Waktu Berakhir',
  '结果': 'Hasil',
  '结果: {value}': 'Hasil: {value}',
  '结果行数: {value}': 'Baris hasil: {value}',
  '结算': 'Selesaikan',
  '结算时间': 'Diselesaikan Pada',
  '结算状态': 'Status Penyelesaian',
  '结转状态': 'Status Penutupan',
  '绩效工资': 'Bayaran Kinerja',
  '维修': 'Perbaikan',
  '维修人': 'Teknisi',
  '维修工单': 'Pesanan Perbaikan',
  '维修类型': 'Jenis Perbaikan',
  '维修费用': 'Biaya Perbaikan',
  '编号': 'No.',
  '编码': 'Kode',
  '编辑': 'Ubah',
  '编辑OMS订单': 'Ubah Order OMS',
  '编辑图表': 'Ubah Grafik',
  '编辑报价单': 'Ubah Penawaran',
  '编辑收货单（仅备注）': 'Ubah Catatan Penerimaan (hanya keterangan)',
  '编辑汇率': 'Ubah Kurs',
  '编辑用户': 'Ubah Pengguna',
  '编辑薪资': 'Ubah Catatan Penggajian',
  '编辑薪资项': 'Ubah Item Gaji',
  '编辑角色': 'Ubah Peran',
  '编辑记账凭证': 'Ubah Voucher',
  '编辑请假': 'Ubah Cuti',
  '编辑跟进记录': 'Ubah Tindak Lanjut',
  '编辑配置': 'Ubah Pengaturan',
  '编辑采购申请': 'Ubah Permintaan Pembelian',
  '编辑采购结算': 'Ubah Penyelesaian Pembelian',
  '编辑采购订单': 'Ubah Pesanan Pembelian',
  '编辑银行账户': 'Ubah Rekening Bank',
  '编辑销售结算': 'Ubah Penyelesaian Penjualan',
  '编辑销售订单': 'Ubah Pesanan Penjualan',
  '编辑阶段': 'Ubah Tahap',
  '缺陷数量': 'Jumlah Cacat',
  '缺陷类型': 'Jenis Cacat',
  '网络连接失败，请检查网络': 'Koneksi jaringan gagal, silakan periksa jaringan Anda',
  '网络错误，请检查连接': 'Kesalahan jaringan, silakan periksa koneksi Anda',
  '考勤': 'Kehadiran',
  '考勤管理': 'Kehadiran',
  '职位': 'Jabatan',
  '职位管理': 'Jabatan',
  '联系人': 'Kontak',
  '草稿': 'Draf',
  '营业成本': 'Biaya Operasional',
  '营业收入': 'Pendapatan Operasional',
  '营销活动': 'Kampanye',
  '薪资': 'Gaji',
  '薪资发放': 'Bayar Gaji',
  '薪资已发放': 'Gaji ditandai sebagai dibayar',
  '薪资年度': 'Tahun Gaji',
  '薪资月份': 'Bulan Gaji',
  '薪资管理': 'Penggajian',
  '薪资试算': 'Perhitungan Gaji',
  '薪资项配置': 'Item Penggajian',
  '行数': 'Baris',
  '规格': 'Spesifikasi',
  '规格名称': 'Nama Spesifikasi',
  '规格型号': 'Model/Spesifikasi',
  '角色': 'Peran',
  '角色创建成功': 'Peran dibuat',
  '角色删除成功': 'Peran dihapus',
  '角色更新成功': 'Peran diperbarui',
  '角色管理': 'Peran',
  '解决': 'Selesaikan',
  '解决工单': 'Selesaikan Tiket',
  '解决说明': 'Catatan Penyelesaian',
  '计划名称': 'Nama Rencana',
  '计划生产数量': 'Kuantitas Rencana',
  '计提折旧': 'Catat Penyusutan',
  '计税': 'Kena Pajak',
  '计算中...': 'Menghitung...',
  '计算比率': 'Hitung Rasio',
  '计算薪资': 'Hitung Gaji',
  '订单': 'Pesanan',
  '订单名称': 'Nama Pesanan',
  '订单总金额': 'Total Pesanan',
  '订单状态分布': 'Distribusi Status Pesanan',
  '订单管理': 'Manajemen Pesanan',
  '订单编号': 'No. Pesanan',
  '订单编码': 'Kode Pesanan',
  '记录不存在': 'Data tidak ditemukan',
  '记录已存在': 'Data sudah ada',
  '记账凭证': 'Voucher',
  '设备ID': 'ID Peralatan',
  '设备分类': 'Kategori Peralatan',
  '设备台账': 'Buku Besar Peralatan',
  '设备名称': 'Nama Peralatan',
  '设备编码': 'Kode Peralatan',
  '试算平衡表': 'Neraca Saldo',
  '试算结果': 'Hasil Perhitungan',
  '详情': 'Detail',
  '说明': 'Deskripsi',
  '请假': 'Cuti',
  '请假原因': 'Alasan',
  '请假天数': 'Hari Cuti',
  '请假日期': 'Periode Cuti',
  '请假管理': 'Cuti',
  '请假类型': 'Jenis Cuti',
  '请先选择用户': 'Pilih pengguna terlebih dahulu',
  '请加载验证码': 'Muat captcha terlebih dahulu',
  '请按顺序点击图中文字: {text}': 'Klik karakter pada gambar secara berurutan: {text}',
  '请按顺序点击图中文字『{text}』': 'Klik karakter \\\'{text}\\\' secara berurutan',
  '请求失败': 'Permintaan gagal',
  '请求超时，请稍后重试': 'Waktu permintaan habis, harap coba lagi nanti',
  '请求过于频繁，请稍后重试': 'Terlalu banyak permintaan, coba lagi nanti',
  '请至少填写一行分配明细': 'Tambahkan setidaknya satu baris alokasi',
  '请输入{label}': 'Harap masukkan {label}',
  '请输入密码': 'Harap masukkan kata sandi Anda',
  '请输入用户名和密码': 'Harap masukkan nama pengguna dan kata sandi',
  '请输入科目ID（account_subject_id 必填）': 'Masukkan ID Akun (account_subject_id wajib diisi)',
  '请选择目标状态': 'Pilih status target',
  '调休': 'Cuti Kompensasi',
  '负债总计': 'Total Liabilitas',
  '负责人': 'Penerima Tugas',
  '财务': 'Keuangan',
  '财务比率': 'Rasio Keuangan',
  '账号已被锁定': 'Akun terkunci',
  '账户余额': 'Saldo Akun',
  '账户名称': 'Nama Akun',
  '购买日期': 'Tanggal Pembelian',
  '贷': 'Kredit',
  '贷方合计': 'Total Kredit',
  '费用': 'Beban',
  '费用合计': 'Total Beban',
  '费用报销': 'Beban',
  '费用结转': 'Pembawaan Beban',
  '资产总计': 'Total Aset',
  '资产收益率': 'Pengembalian atas Aset',
  '资产负债率': 'Rasio Utang terhadap Aset',
  '资产负债表': 'Neraca',
  '资产负债表 JSON *': 'Neraca JSON *',
  '起始区域': 'Zona Asal',
  '起始国家': 'Negara Asal',
  '起始重量(kg)': 'Berat Dari (kg)',
  '起步价': 'Tarif Dasar',
  '跟进主题': 'Subjek Tindak Lanjut',
  '跟进内容': 'Isi Tindak Lanjut',
  '跟进记录': 'Tindak Lanjut',
  '路径': 'Jalur',
  '路径筛选': 'Filter berdasarkan jalur',
  '转合同': 'Konversi ke Kontrak',
  '输入关键词搜索': 'Masukkan kata kunci untuk mencari',
  '输入密码确认': 'Masukkan kata sandi untuk konfirmasi',
  '过程检验(IPQC)': 'Inspeksi Dalam Proses (IPQC)',
  '运单': 'Pengiriman',
  '运单号': 'No. Pelacakan',
  '运单管理': 'Pengiriman',
  '运费': 'Biaya Pengiriman',
  '运费发票': 'Faktur Angkutan',
  '运费费率': 'Tarif Angkutan',
  '运输中': 'Dalam Perjalanan',
  '运输管理': 'Manajemen Transportasi',
  '退出登录': 'Keluar',
  '退回时间': 'Dikembalikan Pada',
  '退回运费': 'Biaya Pengiriman Retur',
  '退换单号': 'No. RMA',
  '退换货': 'RMA',
  '退换货(RMA)': 'Retur (RMA)',
  '退款': 'Pengembalian Dana',
  '退款金额': 'Jumlah Pengembalian Dana',
  '退货': 'Retur',
  '退货单号': 'No. Retur',
  '退货时间': 'Dikembalikan Pada',
  '选填': 'Opsional',
  '通知': 'Notifikasi',
  '通知中心': 'Notifikasi',
  '通过': 'Setujui',
  '通过审批': 'Setujui',
  '邮箱': 'Email',
  '部分发货': 'Dikirim Sebagian',
  '部分收货': 'Diterima Sebagian',
  '部分核销': 'Diselesaikan Sebagian',
  '部分结算': 'Diselesaikan Sebagian',
  '部分退款': 'Dikembalikan Sebagian',
  '部门': 'Departemen',
  '部门ID': 'ID Departemen',
  '部门管理': 'Departemen',
  '配置JSON': 'Konfigurasi JSON',
  '配送方式': 'Metode Pengiriman',
  '采购': 'Pembelian',
  '采购收货': 'Penerimaan Pembelian',
  '采购申请': 'Permintaan Pembelian',
  '采购申请ID': 'ID Permintaan Pembelian',
  '采购结算': 'Penyelesaian Pembelian',
  '采购订单': 'Pesanan Pembelian',
  '采购退货': 'Retur Pembelian',
  '释放回公海': 'Lepaskan ke Pool',
  '重试': 'Coba Lagi',
  '金额': 'Jumlah',
  '金额超出限额': 'Jumlah melebihi batas',
  '银行': 'Bank',
  '银行账号': 'Nomor Rekening Bank',
  '银行账户': 'Rekening Bank',
  '销售': 'Penjualan',
  '销售发货': 'Pengiriman Penjualan',
  '销售报价': 'Penawaran Penjualan',
  '销售渠道': 'Saluran Penjualan',
  '销售漏斗': 'Corong Penjualan',
  '销售结算': 'Penyelesaian Penjualan',
  '销售订单': 'Pesanan Penjualan',
  '销售趋势（近30天）': 'Tren Penjualan (30 Hari Terakhir)',
  '销售退货': 'Retur Penjualan',
  '错误': 'Kesalahan',
  '键': 'Kunci',
  '阶段': 'Tahap',
  '阶段名称': 'Nama Tahap',
  '需已审核的付款单 hashid': 'Hashid dari catatan pembayaran yang disetujui',
  '需已审核的收款单 hashid': 'Hashid dari catatan penerimaan yang disetujui',
  '非流动负债': 'Liabilitas Tidak Lancar',
  '非流动资产': 'Aset Tidak Lancar',
  '非空 JSON 数组，每项须含 ledger_id 或 company_id（后端数字ID，非 hashid）与 report_year（≥2000）、report_month（1-12）': 'Array JSON tidak boleh kosong; setiap item harus memiliki ledger_id atau company_id (ID backend numerik, bukan hashid) ditambah report_year (≥2000) dan report_month (1-12)',
  '项目': 'Proyek',
  '项目列表': 'Daftar Proyek',
  '预到货(ASN)': 'Penerimaan yang Diharapkan (ASN)',
  '预到货通知': 'ASN',
  '预算': 'Anggaran',
  '预算管理': 'Anggaran',
  '领取': 'Klaim',
  '领取客户': 'Klaim Pelanggan',
  '频率': 'Frekuensi',
  '驳回': 'Tolak',
  '驳回审批': 'Tolak',
  '驳回请假': 'Tolak Cuti',
  '验证码加载失败': 'Gagal memuat captcha',
  '验证码错误，请重试': 'Captcha salah, silakan coba lagi',
  '旋转图片验证': 'Captcha Putar Gambar',
  '滑块拼图验证': 'Captcha Puzzle Geser',
  '尝试次数过多，请更换验证码': 'Terlalu banyak percobaan, silakan muat ulang captcha',
  '转动图片使其摆正后提交': 'Putar gambar hingga tegak, lalu kirim',
  '拖动拼图块使其对齐图中缺口': 'Seret potongan puzzle ke celah pada gambar',
  '高库存预警': 'Peringatan Kelebihan Stok',
  '高度': 'Tinggi',
  '默认 0': 'Default 0',
  '默认金额': 'Jumlah Default',
  '0 为顶级': '0 untuk level teratas',
  '3-50 字符': '3-50 karakter',
  '6-32 字符': '6-32 karakter',
  '6-32 位': '6-32 karakter',
  'BI 看板': 'Dasbor BI',
  'BOM 名称': 'Nama BOM',
  'BOM 管理': 'Manajemen BOM',
  'BOM 编码': 'Kode BOM',
  'CRM 报价单': 'Penawaran CRM',
  'LOGO 地址': 'URL Logo',
  'MRP 计划': 'Rencana MRP',
  'MRP 运算': 'Jalankan MRP',
  'Offer 已发出': 'Penawaran terkirim',
  'Offer 薪资': 'Tawaran Gaji',
  'erp开放平台': 'Buka Platform ERP',
  '上一页': 'Sebelumnya',
  '上架': 'Terbitkan',
  '上架完成': 'Penempatan rak selesai',
  '上架已完成': 'Penempatan rak telah selesai',
  '上次登录': 'Login Terakhir',
  '上班打卡': 'Absen Masuk',
  '上级部门': 'Departemen Induk',
  '下一页': 'Berikutnya',
  '下架': 'Batalkan Terbit',
  '下班打卡': 'Absen Keluar',
  '不合格': 'Tolak',
  '不合格品单号': 'Nomor NCR',
  '不通过': 'Tidak Lulus',
  '两位小数，如 30000.00': 'Hingga 2 desimal, mis. 30000.00',
  '两位小数，如 5000.00': 'Hingga 2 desimal, mis. 5000.00',
  '两次输入的新密码不一致': 'Dua kata sandi baru tidak cocok',
  '中标转订单': 'Tetapkan ke Pesanan Pembelian',
  '产品': 'Produk',
  '人工': 'Tenaga Kerja',
  '仓库名称': 'Nama Gudang',
  '仓库管理': 'Manajemen Gudang',
  '仓库编码': 'Kode Gudang',
  '付款方式': 'Metode Pembayaran',
  '付款日期': 'Tanggal Pembayaran',
  '付款账户': 'Akun Pembayaran',
  '任务名称': 'Nama Tugas',
  '任职要求': 'Persyaratan',
  '作废': 'Batalkan',
  '使用年限': 'Masa Manfaat',
  '供应商名称': 'Nama Pemasok',
  '供应商报价': 'Penawaran Pemasok',
  '供应商评估': 'Penilaian Pemasok',
  '保存失败': 'Gagal menyimpan',
  '保存资料': 'Simpan Profil',
  '信用账期(天)': 'Termin Kredit (hari)',
  '信用额度': 'Batas Kredit',
  '修改失败': 'Pembaruan gagal',
  '候选人': 'Kandidat',
  '停用': 'Tangguhkan',
  '兑付': 'Kas',
  '入职日期': 'Tanggal Bergabung',
  '全部通知已标记为已读': 'Semua notifikasi ditandai telah dibaca',
  '共': 'dari',
  '关联任务': 'Tugas Tertaut',
  '内训': 'Internal',
  '再次输入新密码': 'Masukkan kata sandi baru lagi',
  '净值': 'Nilai Bersih',
  '出库仓库': 'Gudang Pengeluaran',
  '出票人': 'Laci',
  '出票日期': 'Tanggal Pengeluaran',
  '出货检验': 'Inspeksi Akhir OQC',
  '出货检验 OQC': 'Inspeksi Akhir OQC',
  '分类名称': 'Nama Kategori',
  '初筛通过': 'Lolos Seleksi',
  '利润表': 'Laporan Laba Rugi',
  '到期': 'Kedaluwarsa',
  '到期预警': 'Peringatan Kedaluwarsa',
  '制费': 'Overhead',
  '加工单价': 'Harga Proses',
  '加载中…': 'Memuat...',
  '勾选': 'Periksa',
  '协同管理': 'Kolaborasi',
  '原值': 'Nilai Asli',
  '发出': 'Kirim',
  '发布': 'Terbitkan',
  '发布中': 'Diterbitkan',
  '发料仓库': 'Gudang Pengeluaran',
  '发料单号': 'No. Slip Pengeluaran',
  '发料单已审核': 'Slip pengeluaran disetujui',
  '发料日期': 'Tanggal Pengeluaran',
  '发生日期': 'Tanggal Terjadi',
  '发票号': 'No. Invoice',
  '发票管理': 'Manajemen Invoice',
  '发货': 'Kirim',
  '发货单': 'Surat Jalan',
  '发货日期': 'Tanggal Pengiriman',
  '发起审批': 'Mulai Persetujuan',
  '取消点检': 'Batalkan Inspeksi',
  '合同号': 'No. Kontrak',
  '合同金额': 'Jumlah Kontrak',
  '合格': 'Lulus',
  '合格数': 'Kuantitas Lulus',
  '合计': 'Total',
  '启停': 'Alih',
  '启动': 'Mulai',
  '启用日期': 'Tanggal Mulai Digunakan',
  '员工姓名': 'Nama Karyawan',
  '员工编码': 'Kode Karyawan',
  '周期类型': 'Jenis Periode',
  '品牌名称': 'Nama Merek',
  '品牌描述': 'Deskripsi Merek',
  '品项数': 'Item Baris',
  '商品描述': 'Deskripsi',
  '商品管理': 'Manajemen Produk',
  '商品资料': 'Master Produk',
  '商机名称': 'Nama Peluang',
  '回复': 'Balas',
  '回调地址': 'URL Callback',
  '图标': 'Ikon',
  '图表组件': 'Widget Grafik',
  '城市': 'Kota',
  '培训社保': 'Pelatihan & Jaminan Sosial',
  '培训课程': 'Kursus Pelatihan',
  '基本资料': 'Profil Dasar',
  '处理中': 'Memproses',
  '备件管理': 'Suku Cadang',
  '外训': 'Eksternal',
  '多币种': 'Mata Uang',
  '多组织公司': 'Perusahaan',
  '如 admin、viewer': 'mis. admin, viewer',
  '如 monthly': 'mis. bulanan',
  '如 上海': 'mis. Shanghai',
  '如 人民币': 'mis. CNY',
  '委外产品': 'Produk Outsourcing',
  '委外加工': 'Subkontrak',
  '委外发料': 'Pengeluaran Subkontrak',
  '委外收货': 'Penerimaan Subkontrak',
  '委外数量': 'Jumlah Subkontrak',
  '委外订单': 'Pesanan Subkontrak',
  '字符串': 'String',
  '季度': 'Triwulan',
  '学分': 'Kredit',
  '完工': 'Selesai',
  '完工数': 'Jumlah Selesai',
  '实发': 'Gaji Bersih',
  '审批已发起': 'Persetujuan dimulai',
  '审核': 'Setujui',
  '客户名称': 'Nama Pelanggan',
  '客户管理': 'Manajemen Pelanggan',
  '密码已修改': 'Kata sandi diubah',
  '密钥已重置': 'Rahasia direset',
  '小计': 'Subtotal',
  '工作站名称': 'Nama Workstation',
  '工作站编码': 'Kode Workstation',
  '工单分类': 'Kategori Tiket',
  '工单号': 'No. Tiket',
  '工单已完工': 'Perintah kerja selesai',
  '工单已开工': 'Perintah kerja dimulai',
  '工单已解决': 'Tiket diselesaikan',
  '工单标题': 'Judul Tiket',
  '工序': 'Operasi',
  '工序名称': 'Nama Operasi',
  '工序序号': 'Urutan',
  '工序报工': 'Laporan Kerja',
  '工时数': 'Jam',
  '工资条': 'Slip Gaji',
  '已作废': 'Dibatalkan',
  '已入职': 'Telah Onboard',
  '已发 Offer': 'Tawaran Terkirim',
  '已发出': 'Terkirim',
  '已回复': 'Dibalas',
  '已完成库存分配': 'Stok dialokasikan',
  '已归档': 'Diarsipkan',
  '已接受': 'Diterima',
  '已提交': 'Diajukan',
  '已撤销': 'Ditarik',
  '已标记为已读': 'Ditandai telah dibaca',
  '已派单': 'Ditugaskan',
  '已淘汰': 'Ditolak',
  '已生成合同': 'Kontrak dibuat',
  '已生成履约单': 'Pemenuhan dibuat',
  '已生成采购订单': 'Pesanan pembelian dibuat',
  '已生效': 'Berlaku',
  '已用': 'Digunakan',
  '已结': 'Diselesaikan',
  '已认领': 'Diklaim',
  '已读': 'Dibaca',
  '已释放回公海': 'Dikembalikan ke pool',
  '币种名称': 'Nama Mata Uang',
  '币种管理': 'Manajemen Mata Uang',
  '币种编码': 'Kode Mata Uang',
  '布尔': 'Boolean',
  '库位名称': 'Nama Lokasi',
  '库位编码': 'Kode Lokasi',
  '库区名称': 'Nama Zona',
  '库区编码': 'Kode Zona',
  '库存分配': 'Alokasikan Stok',
  '库存管理': 'Manajemen Persediaan',
  '应发': 'Gaji Bruto',
  '应用名称': 'Nama Aplikasi',
  '应聘职位': 'Pekerjaan Dilamar',
  '开工': 'Mulai',
  '开户行': 'Bank',
  '开放应用': 'Aplikasi OpenAPI',
  '开票': 'Terbitkan Faktur',
  '开票日期': 'Tanggal Faktur',
  '归档': 'Arsipkan',
  '归集日期': 'Tanggal Posting',
  '当前密码': 'Kata Sandi Saat Ini',
  '录用 Offer': 'Surat Penawaran',
  '往来方': 'Pihak Lawan',
  '待定': 'Tertunda',
  '待开通': 'Penyisihan Tertunda',
  '总账': 'Buku Besar',
  '成本': 'Biaya',
  '成本归集': 'Entri Biaya',
  '成本类别': 'Kategori Biaya',
  '所属仓库': 'Gudang',
  '所属应用': 'Aplikasi',
  '所属模块': 'Modul',
  '所属看板': 'Dasbor',
  '所属部门': 'Departemen',
  '所属项目': 'Proyek',
  '手机': 'Telepon',
  '打包完成': 'Kemas Selesai',
  '打包已完成': 'Pengepakan selesai',
  '打卡成功': 'Berhasil absen',
  '托收': 'Kumpulkan',
  '托收账户': 'Akun Penagihan',
  '执行报表': 'Jalankan Laporan',
  '批次效期预警': 'Peringatan Kedaluwarsa Batch',
  '承兑人': 'Akseptor',
  '承兑汇票': 'Akseptasi Banker',
  '承运商名称': 'Nama Kurir',
  '投递测试完成': 'Tes pengiriman selesai',
  '折扣': 'Diskon',
  '折旧已计提': 'Penyusutan diposting',
  '折旧方法': 'Metode Penyusutan',
  '报工员工': 'Karyawan Pelapor',
  '报工已审核': 'Laporan kerja disetujui',
  '报工数量': 'Jumlah Dilaporkan',
  '报工日期': 'Tanggal Laporan',
  '报表已执行': 'Laporan dijalankan',
  '报表模板': 'Template Laporan',
  '报销金额': 'Jumlah Penggantian',
  '抵扣': 'Potong',
  '拒付': 'Tolak',
  '招聘人数': 'Jumlah Karyawan',
  '招聘候选人': 'Kandidat',
  '招聘管理': 'Rekrutmen',
  '招聘职位': 'Lowongan Pekerjaan',
  '招聘部门': 'Departemen Perekrutan',
  '招聘面试': 'Wawancara',
  '拣货已确认': 'Pengambilan dikonfirmasi',
  '拣货确认': 'Konfirmasi Pengambilan',
  '按钮': 'Tombol',
  '提交数': 'Kuantitas Diajukan',
  '搜索通知内容': 'Cari isi notifikasi',
  '搜索配置键': 'Cari kunci konfigurasi',
  '撤销': 'Tarik',
  '操作人': 'Operator',
  '支付': 'Bayar',
  '收料仓库': 'Gudang Penerima',
  '收料单号': 'No. Slip Penerimaan',
  '收料单已审核': 'Slip penerimaan disetujui',
  '收料数量': 'Kuantitas Diterima',
  '收料日期': 'Tanggal Terima',
  '收款人': 'Penerima Pembayaran',
  '收款方式': 'Metode Penerimaan',
  '收款日期': 'Tanggal Penerimaan',
  '收款账户': 'Akun Penerimaan',
  '收款金额': 'Jumlah Penerimaan',
  '收票': 'Diterima',
  '收货单': 'Catatan Penerimaan',
  '收货完成': 'Penerimaan Selesai',
  '收货已完成': 'Penerimaan selesai',
  '收货日期': 'Tanggal Penerimaan',
  '数组': 'Array',
  '整数': 'Integer',
  '文档内容': 'Konten',
  '文档分类': 'Kategori',
  '文档管理': 'Manajemen Dokumen',
  '新增成功': 'Dibuat',
  '新密码': 'Kata Sandi Baru',
  '新密码长度需为 6-32 位': 'Kata sandi baru harus 6-32 karakter',
  '新简历': 'Resume Baru',
  '是否启用': 'Aktif',
  '更新时间': 'Diperbarui Pada',
  '最大库存阈值': 'Batas Stok Maksimum',
  '最小库存阈值': 'Batas Stok Minimum',
  '月度': 'Bulanan',
  '服务名称': 'Nama Layanan',
  '期望薪资': 'Gaji yang Diharapkan',
  '期间已结账': 'Periode ditutup',
  '未开始': 'Belum Dimulai',
  '未结': 'Belum Diselesaikan',
  '未设置': 'Belum Diatur',
  '未读': 'Belum Dibaca',
  '权限名': 'Nama Izin',
  '权限管理': 'Manajemen Izin',
  '材料': 'Material',
  '条': 'catatan',
  '来料检验': 'IQC',
  '来料检验 IQC': 'Inspeksi Kedatangan IQC',
  '来源币种': 'Dari Mata Uang',
  '来源渠道': 'Sumber',
  '标记已读': 'Tandai Dibaca',
  '模板名称': 'Nama Template',
  '模板已启用': 'Template diaktifkan',
  '模板编码': 'Kode Template',
  '残值': 'Nilai Sisa',
  '比价': 'Bandingkan',
  '汇率值': 'Kurs',
  '波次已释放': 'Gelombang Dirilis',
  '波次释放': 'Rilis Gelombang',
  '活动名称': 'Nama Kampanye',
  '派单': 'Tetapkan',
  '测试投递': 'Tes Pengiriman',
  '渠道名称': 'Nama Saluran',
  '漏斗阶段名称': 'Nama Tahap',
  '点检任务': 'Tugas Inspeksi',
  '点检日期': 'Tanggal Inspeksi',
  '父任务': 'Tugas Induk',
  '父级 ID': 'ID Induk',
  '状态已切换': 'Status diubah',
  '状态已更新': 'Status diperbarui',
  '生产领料': 'Pengeluaran Material',
  '用户数': 'Pengguna',
  '申请人': 'Pemohon',
  '界面语言': 'Bahasa',
  '登录已过期，请重新登录': 'Sesi berakhir, silakan masuk lagi',
  '盘点任务名称': 'Nama Stok Opname',
  '盘点单号': 'No. Stok Opname',
  '目录': 'Direktori',
  '目标币种': 'Ke Mata Uang',
  '目标类型': 'Jenis Target',
  '直线法': 'Garis Lurus',
  '看板布局': 'Tata Letak Dasbor',
  '确认操作': 'Konfirmasi Tindakan',
  '社保规则': 'Aturan Jaminan Sosial',
  '票据号': 'No. Tagihan',
  '票面金额': 'Nilai Nominal',
  '租户列表': 'Penyewa',
  '租户已停用': 'Penyewa ditangguhkan',
  '租户已启用': 'Penyewa diaktifkan kembali',
  '租户管理': 'Manajemen Penyewa',
  '税号': 'No. Pajak',
  '税率管理': 'Tarif Pajak',
  '税额': 'Jumlah Pajak',
  '第': 'Halaman',
  '签订日期': 'Tanggal Tanda Tangan',
  '算薪': 'Hitung Penggajian',
  '算薪完成': 'Penggajian dihitung',
  '纳税记录': 'Catatan Pajak',
  '线上': 'Daring',
  '组件名称': 'Nama Widget',
  '组件类型': 'Jenis Widget',
  '结账': 'Tutup Periode',
  '绩效模板': 'Template Kinerja',
  '绩效考核': 'Penilaian Kinerja',
  '维修工单号': 'No. Perintah Perbaikan',
  '缴费基数上限': 'Batas Atas Dasar',
  '缴费基数下限': 'Batas Bawah Dasar',
  '考核批次已启动': 'Penilaian dimulai',
  '考核批次已归档': 'Penilaian diarsipkan',
  '考核计划': 'Rencana Penilaian',
  '考核评分': 'Skor Penilaian',
  '耗时(ms)': 'Waktu Berlalu (ms)',
  '职位名称': 'Jabatan',
  '职位已关闭': 'Lowongan ditutup',
  '职位已发布': 'Lowongan dipublikasikan',
  '职位编码': 'Kode Posisi',
  '联系人名称': 'Nama Kontak',
  '背书': 'Endosemen',
  '自定义字段': 'Bidang Kustom',
  '自定义报表': 'Laporan Kustom',
  '获取面单': 'Ambil Label',
  '菜单': 'Menu',
  '规则名称': 'Nama Aturan',
  '角色名': 'Nama Peran',
  '角色权限': 'Peran',
  '计划年度': 'Tahun Rencana',
  '计划数': 'Jml Rencana',
  '计划数量': 'Kuantitas Rencana',
  '计划日期': 'Tanggal Rencana',
  '计划月份': 'Bulan Rencana',
  '计划编码': 'Kode Rencana',
  '订单号': 'No. Pesanan',
  '订单履约': 'Pemenuhan Pesanan',
  '订单已取消': 'Pesanan dibatalkan',
  '认领': 'Klaim',
  '讲师': 'Dosen',
  '设备': 'Peralatan',
  '设备管理': 'Manajemen Peralatan',
  '询价单': 'RFQ',
  '询价单已关闭': 'RFQ ditutup',
  '请输入当前密码': 'Masukkan kata sandi saat ini',
  '请输入登录密码确认操作': 'Masukkan kata sandi login untuk konfirmasi',
  '课时(小时)': 'Durasi (jam)',
  '课程标题': 'Judul Kursus',
  '课程类型': 'Jenis Kursus',
  '调出仓库': 'Dari Gudang',
  '调拨单号': 'No. Transfer',
  '调拨日期': 'Tanggal Transfer',
  '财务管理': 'Manajemen Keuangan',
  '账套期间': 'Periode Buku Besar',
  '账户编码': 'Kode Akun',
  '质量管理': 'Manajemen Mutu',
  '购置日期': 'Tanggal Pembelian',
  '购置金额': 'Jumlah Pembelian',
  '贴现': 'Diskon',
  '费用科目': 'Akun Beban',
  '费用类型': 'Jenis Beban',
  '资产名称': 'Nama Aset',
  '资产类别': 'Kategori Aset',
  '资产编号': 'No. Aset',
  '资产编码': 'Kode Aset',
  '资料已保存': 'Profil disimpan',
  '赢单': 'Menang',
  '跟进中': 'Tindak Lanjut',
  '跟进人': 'Pengikut',
  '轮次': 'Ronde',
  '输单': 'Kalah',
  '过程检验': 'IPQC',
  '过程检验 IPQC': 'Inspeksi Proses IPQC',
  '运单已发货': 'Pengiriman dikirim',
  '运算完成': 'MRP selesai',
  '运费已支付': 'Biaya angkut dibayar',
  '运费已确认': 'Biaya angkut dikonfirmasi',
  '运输服务': 'Layanan Transportasi',
  '进行中': 'Dalam Proses',
  '进项发票池': 'Pool Faktur Masukan',
  '退换货 RMA': 'RMA Pengembalian',
  '退货仓库': 'Gudang Pengembalian',
  '退货入库': 'Terima Pengembalian',
  '退货金额': 'Jumlah Pengembalian',
  '部门名称': 'Nama Departemen',
  '部门编码': 'Kode Departemen',
  '配置键': 'Kunci',
  '采购管理': 'Manajemen Pembelian',
  '采购销售': 'Pengadaan & Penjualan',
  '释放': 'Rilis',
  '重置密钥': 'Reset Rahasia',
  '销售管理': 'Manajemen Penjualan',
  '集团财务': 'Keuangan Grup',
  '面单已生成': 'Label dibuat',
  '面试中': 'Wawancara',
  '面试日期': 'Tanggal Wawancara',
  '页': 'dari',
  '项目名称': 'Nama Proyek',
  '项目成本': 'Biaya Proyek',
  '项目管理': 'Manajemen Proyek',
  '项目编号': 'Kode Proyek',
  '预到货 ASN': 'ASN',
  '预算名称': 'Nama Anggaran',
  '预算对比': 'Bandingkan Anggaran',
  '预算年度': 'Tahun Anggaran',
  '预算额': 'Jumlah Anggaran',
  '预计金额': 'Jumlah Diharapkan',
  '领料单已审核': 'Penerbitan disetujui',
  '领料日期': 'Tanggal Terbit',
  '验真': 'Verifikasi',
  '验证失败，请重试': 'Verifikasi gagal, silakan coba lagi',
  '搜索菜单': 'Cari menu',
  '关闭标签': 'Tutup tab',
  '关闭其他标签': 'Tutup tab lain',
  '关闭全部标签': 'Tutup semua tab',
  '关闭其他': 'Tutup Lainnya',
  '关闭全部': 'Tutup Semua',
  '页面不存在': 'Halaman Tidak Ditemukan',
  '当前路由未注册': 'Rute tidak terdaftar',
  '人机验证': 'Captcha',
  '点击文字验证': 'Klik karakter',
  '验证码加载中…': 'Memuat captcha...',
  '暂无趋势数据': 'Belum ada data tren',
  '账户状态分布': 'Status Akun',
  '最近操作日志': 'Log Terbaru',
  '暂无日志': 'Tidak ada log',
  '近 30 天趋势': 'Tren 30 Hari Terakhir',
  '已完成人机验证，点击「登 录」继续': 'Captcha terverifikasi. Klik Masuk untuk melanjutkan',
  '登录需先完成人机验证': 'Selesaikan captcha terlebih dahulu',
  '全部已读': 'Tandai Semua Dibaca',
  '请选择': 'Pilih...',
  '条/页': 'data/halaman',
  '较昨日': 'vs kemarin',
  '按顺序点击': 'Klik secara berurutan',
  '请填写「{label}」': 'Silakan isi {label}',
  '新增{name}': 'Tambah {name}',
  '编辑{name}': 'Edit {name}',
  '确定执行「{act}」吗？': 'Jalankan {act}?',
  '确定删除「{name}」？该操作不可恢复。': 'Hapus {name}? Tindakan ini tidak dapat dibatalkan.',
  '请求失败（{code}）': 'Permintaan gagal ({code})',
  '下载失败（{code}）': 'Gagal mengunduh ({code})',
  'Open ERP · Web 控制台': 'Buka ERP · Konsol Web',
  '业务模块': 'Modul',
  '中英切换': 'Mandarin / Inggris',
  '第 {count} 个字位置不准，请再点一次': 'Klik #{count} lagi - titiknya meleset dari sasaran',
  '仍未通过，请按顺序重新点击': 'Masih belum cocok - klik semua karakter secara berurutan lagi',
  '规格属性': 'Atribut Spesifikasi',
  '费率(元/小时)': 'Tarif (yuan/jam)',
  '订阅事件': 'Event yang Dilanggan',
  '0=全部': '0=Semua',
  '如 get.admin/user': 'mis. get.admin/user',
  '搜索用户/路径': 'Cari pengguna/path',
  '多个事件名用逗号或换行分隔；* 表示全部；仅允许字母、数字与 . _ -': 'Pisahkan beberapa nama event dengan koma atau baris baru; * berarti semua; hanya huruf, angka, dan . _ - yang diizinkan',
  '勾选父级即全选其下所有子项': 'Mencentang induk akan memilih semua anaknya',
  '父级': 'Induk',
  '点节点选父级；点已选节点取消（空 = 顶级）': 'Klik node untuk menetapkannya sebagai induk; klik node yang dipilih untuk menghapus (kosong = tingkat teratas)',
  'JSON 对象：属性名 → 值数组，如 {"颜色":["红","蓝"],"尺寸":["S","M","L"]}；留空 / {} 表示无属性': 'Objek JSON: nama atribut → array nilai, mis. {"Color":["Red","Blue"],"Size":["S","M","L"]}; biarkan kosong / {} untuk tanpa atribut',
};
